# Colors (Abandoned)

[colors.bright]
black = '#c9c8b8'
blue = '#9cb9c1'
cyan = '#91c3bd'
green = '#a9bf9f'
magenta = '#bea6b4'
red = '#e9a689'
white = '#f0ecdc'
yellow = '#dcc87f'

[colors.cursor]
cursor = '#e9a689'
text = '#433d2d'

[colors.normal]
black = '#c2c0ae'
blue = '#8eafb8'
cyan = '#82bbb4'
green = '#9db692'
magenta = '#bda6b4'
red = '#e69a79'
white = '#eee9d7'
yellow = '#d7c06e'

[colors.primary]
background = '#433d2d'
foreground = '#eee9d7'

[colors.selection]
background = '#c9c8b8'
text = '#979383'
