# Colors (Electron Highlighter)

[colors.bright]
black = '#4b5b8c'
blue = '#77abff'
cyan = '#00e5ff'
green = '#00ffc3'
magenta = '#daa4f4'
red = '#ff6c8d'
white = '#c3cde2'
yellow = '#ffebb1'

[colors.cursor]
cursor = '#a5b6d4'
text = '#171b29'

[colors.normal]
black = '#15161f'
blue = '#77abff'
cyan = '#00e5ff'
green = '#00ffc3'
magenta = '#daa4f4'
red = '#ff6c8d'
white = '#7187b7'
yellow = '#ffebb1'

[colors.primary]
background = '#23283d'
foreground = '#a5b6d4'

[colors.selection]
background = '#293257'
text = '#a5b6d4'
