[colors]
background = '#4a0710'
foreground = '#f2e2c8'
selection-background = '#c5b4b7'
selection-foreground = '#fff2dc'
cursor = '#e48e81'
black = '#bdaaad'
red = '#e07f70'
green = '#9eae80'
yellow = '#d0af63'
blue = '#849caf'
magenta = '#b78ea6'
cyan = '#7bb2aa'
white = '#f2e2c8'
light_black = '#c5b4b7'
light_red = '#e48e81'
light_green = '#aab88f'
light_yellow = '#d6b976'
light_blue = '#93a8b9'
light_magenta = '#c09cb1'
light_cyan = '#8bbbb4'
light_white = '#f4e5cf'
