[colors]
background = '#ffffff'
foreground = '#1d1d20'
selection-background = '#1d1d20'
selection-foreground = '#ffffff'
cursor = '#1d1d20'
black = '#1d1d20'
red = '#c01c28'
green = '#26a269'
yellow = '#a2734c'
blue = '#12488b'
magenta = '#a347ba'
cyan = '#2aa1b3'
white = '#c2c2c2'
light_black = '#5d5d5d'
light_red = '#f66151'
light_green = '#33d17a'
light_yellow = '#e9ad0c'
light_blue = '#2a7bde'
light_magenta = '#c061cb'
light_cyan = '#33c7de'
light_white = '#ffffff'
