[colors]
background = '#000000'
foreground = '#ffffff'
selection-background = '#1e3a5f'
selection-foreground = '#ffffff'
cursor = '#3b82f6'
black = '#000000'
red = '#ff8080'
green = '#99ffe4'
yellow = '#2563eb'
blue = '#a0a0a0'
magenta = '#3b82f6'
cyan = '#99ffe4'
white = '#ffffff'
light_black = '#505050'
light_red = '#ff9999'
light_green = '#b3ffe4'
light_yellow = '#60a5fa'
light_blue = '#b0b0b0'
light_magenta = '#93c5fd'
light_cyan = '#99ffe4'
light_white = '#ffffff'
