[colors]
background = '#fbf6fb'
foreground = '#3a3340'
selection-background = '#ebe2ee'
selection-foreground = '#aea9ae'
cursor = '#ae3f84'
black = '#33293f'
red = '#c0303a'
green = '#2e7d6e'
yellow = '#8c610c'
blue = '#4a3cc0'
magenta = '#8a4bc0'
cyan = '#ae3f84'
white = '#b2b2b2'
light_black = '#9a8fa8'
light_red = '#c0303a'
light_green = '#2e7d6e'
light_yellow = '#ae3f84'
light_blue = '#4a3cc0'
light_magenta = '#d8b670'
light_cyan = '#ae3f84'
light_white = '#3a3340'
