[colors]
background = '#15141b'
foreground = '#cdccce'
selection-background = '#cdccce'
selection-foreground = '#15141b'
cursor = '#a277ff'
black = '#15141b'
red = '#ff6767'
green = '#61ffca'
yellow = '#ffca85'
blue = '#a277ff'
magenta = '#61ffca'
cyan = '#a277ff'
white = '#cdccce'
light_black = '#464646'
light_red = '#ffca85'
light_green = '#a277ff'
light_yellow = '#ffca85'
light_blue = '#a277ff'
light_magenta = '#61ffca'
light_cyan = '#61ffca'
light_white = '#edecee'
