[colors]
background = '#021012'
foreground = '#095b67'
selection-background = '#041f23'
selection-foreground = '#425052'
cursor = '#16c2d9'
black = '#021012'
red = '#16c2d9'
green = '#4dd0e1'
yellow = '#80deea'
blue = '#00bcd4'
magenta = '#00adc1'
cyan = '#26c6d6'
white = '#095b67'
light_black = '#1e484e'
light_red = '#b3ebf2'
light_green = '#4dd0e1'
light_yellow = '#80deea'
light_blue = '#00bcd4'
light_magenta = '#00adc1'
light_cyan = '#26c6d6'
light_white = '#0c7c7c'
