[colors]
background = '#55452f'
foreground = '#fff0d5'
selection-background = '#74634c'
selection-foreground = '#fff8e8'
cursor = '#f0bd5b'
black = '#c9c4b5'
red = '#ebad90'
green = '#87c79e'
yellow = '#dfbf68'
blue = '#91c1d6'
magenta = '#d2afc4'
cyan = '#76c9c4'
white = '#fff0d5'
light_black = '#d8d3c5'
light_red = '#eeaa89'
light_green = '#99d0aa'
light_yellow = '#e9d087'
light_blue = '#9bc9dc'
light_magenta = '#d8b6c8'
light_cyan = '#94d7d2'
light_white = '#fff9e9'
