[colors]
background = '#ffffff'
foreground = '#3a4851'
selection-background = '#e5ecf1'
selection-foreground = '#b2b2b2'
cursor = '#919191'
black = '#2d3840'
red = '#b45648'
green = '#6caa71'
yellow = '#c4ac62'
blue = '#5685a8'
magenta = '#ad64be'
cyan = '#69c6c9'
white = '#b4bbbf'
light_black = '#506573'
light_red = '#df6c5a'
light_green = '#79be7e'
light_yellow = '#d8bb65'
light_blue = '#49a2e1'
light_magenta = '#d389e5'
light_cyan = '#5ec7cb'
light_white = '#d8e1e7'
