[colors]
background = '#f4f9ff'
foreground = '#102235'
selection-background = '#dce9f5'
selection-foreground = '#102235'
cursor = '#0b5f83'
black = '#29394a'
red = '#842121'
green = '#0c5935'
yellow = '#644b00'
blue = '#17468f'
magenta = '#5e3188'
cyan = '#005969'
white = '#3b4b5b'
light_black = '#40505f'
light_red = '#902727'
light_green = '#10613b'
light_yellow = '#6c5100'
light_blue = '#123a78'
light_magenta = '#653890'
light_cyan = '#004b59'
light_white = '#455565'
