[colors]
background = '#f1f6fd'
foreground = '#292e35'
selection-background = '#ced3d9'
selection-foreground = '#292e35'
cursor = '#983472'
black = '#292e35'
red = '#a44602'
green = '#107c5a'
yellow = '#756f1d'
blue = '#0068a4'
magenta = '#983472'
cyan = '#0b7b80'
white = '#b4b9bf'
light_black = '#616a76'
light_red = '#976700'
light_green = '#107c5a'
light_yellow = '#4d3919'
light_blue = '#2f516c'
light_magenta = '#633750'
light_cyan = '#154b4e'
light_white = '#e7ecf2'
