[colors]
background = '#f3efe8'
foreground = '#44413b'
selection-background = '#e2daca'
selection-foreground = '#a6a29b'
cursor = '#a25327'
black = '#44413b'
red = '#af2817'
green = '#3c6a12'
yellow = '#795900'
blue = '#186875'
magenta = '#754193'
cyan = '#006a62'
white = '#6e6b62'
light_black = '#8c8579'
light_red = '#c03a27'
light_green = '#538625'
light_yellow = '#9a4c1f'
light_blue = '#207887'
light_magenta = '#8552a3'
light_cyan = '#087a71'
light_white = '#2e2c27'
