[colors]
background = '#5a2032'
foreground = '#fff0df'
selection-background = '#7d4050'
selection-foreground = '#fff7ed'
cursor = '#f4bd63'
black = '#c9b9b8'
red = '#ff978b'
green = '#94d1a1'
yellow = '#edc96d'
blue = '#8fc4e8'
magenta = '#dfa2c9'
cyan = '#82d7d2'
white = '#fff0df'
light_black = '#dacbca'
light_red = '#ffaea3'
light_green = '#a9dcaf'
light_yellow = '#f8d98b'
light_blue = '#acd4ef'
light_magenta = '#e9bad7'
light_cyan = '#a2e4df'
light_white = '#fffaf2'
