[colors]
background = '#140c07'
foreground = '#f4e2c8'
selection-background = '#33220f'
selection-foreground = '#544c47'
cursor = '#ff6a1f'
black = '#241810'
red = '#ff4733'
green = '#c4c24a'
yellow = '#ffb347'
blue = '#f0a24f'
magenta = '#ff6a4d'
cyan = '#ffd27a'
white = '#e6d2b6'
light_black = '#7a6248'
light_red = '#ff4733'
light_green = '#c4c24a'
light_yellow = '#ff7a2d'
light_blue = '#f0a24f'
light_magenta = '#ff6a4d'
light_cyan = '#ffd27a'
light_white = '#f4e2c8'
