[colors]
background = '#eef3ea'
foreground = '#6e6e6e'
selection-background = '#6e6e6e'
selection-foreground = '#eef3ea'
cursor = '#6e6e6e'
black = '#eef3ea'
red = '#c33f3d'
green = '#347b47'
yellow = '#856b31'
blue = '#2f6bcf'
magenta = '#9242d6'
cyan = '#306f72'
white = '#6e6e6e'
light_black = '#8c8c8c'
light_red = '#d0272f'
light_green = '#1f7d3f'
light_yellow = '#896a1c'
light_blue = '#1a67e1'
light_magenta = '#982ae9'
light_cyan = '#1c7175'
light_white = '#6e6e6e'
