[colors]
background = '#191a1c'
foreground = '#bcbec4'
selection-background = '#2a4371'
selection-foreground = '#d1d3d9'
cursor = '#ced0d6'
black = '#191a1c'
red = '#f75464'
green = '#6aab73'
yellow = '#cf8e6d'
blue = '#56a8f5'
magenta = '#c77dbb'
cyan = '#2aacb8'
white = '#bcbec4'
light_black = '#7a7e85'
light_red = '#f57e84'
light_green = '#6db083'
light_yellow = '#f0ac81'
light_blue = '#548af7'
light_magenta = '#b189f5'
light_cyan = '#16baac'
light_white = '#ffffff'
