[colors]
background = '#14181f'
foreground = '#e2def0'
selection-background = '#2f2d3d'
selection-foreground = '#e2def0'
cursor = '#ebd870'
black = '#14181f'
red = '#e87691'
green = '#82c891'
yellow = '#ebd870'
blue = '#6cc4d2'
magenta = '#a892d4'
cyan = '#6cc4d2'
white = '#a8a4ae'
light_black = '#5c5a5f'
light_red = '#e8869c'
light_green = '#98cea4'
light_yellow = '#ebd870'
light_blue = '#80c8d2'
light_magenta = '#b6a4d6'
light_cyan = '#80c8d2'
light_white = '#e2def0'
