[colors]
background = '#0e0c0e'
foreground = '#e8e0c8'
selection-background = '#2a2228'
selection-foreground = '#e8e0c8'
cursor = '#e85aa8'
black = '#1a1418'
red = '#d65a3a'
green = '#6a8a4a'
yellow = '#e8b048'
blue = '#5a7ab8'
magenta = '#d76aa8'
cyan = '#88a8c8'
white = '#e8e0c8'
light_black = '#44403c'
light_red = '#ec7654'
light_green = '#88a868'
light_yellow = '#f5c25c'
light_blue = '#7a96d0'
light_magenta = '#ed85bc'
light_cyan = '#a0bcd6'
light_white = '#fdf6df'
