[colors]
background = '#1a0e17'
foreground = '#f4e7d7'
selection-background = '#ff6633'
selection-foreground = '#ffeb83'
cursor = '#ff3e3e'
black = '#3b1919'
red = '#8b1e3e'
green = '#d25944'
yellow = '#59ae08'
blue = '#fbbf24'
magenta = '#a855f7'
cyan = '#ef4444'
white = '#f472b6'
light_black = '#5a3a2e'
light_red = '#fb7185'
light_green = '#34d399'
light_yellow = '#fde047'
light_blue = '#60a5fa'
light_magenta = '#c084fc'
light_cyan = '#22d3ee'
light_white = '#fff7e6'
