[colors]
background = '#f5f7ea'
foreground = '#354029'
selection-background = '#dde7cc'
selection-foreground = '#a8aa9d'
cursor = '#4e8c2e'
black = '#354029'
red = '#c2452a'
green = '#4e8c2e'
yellow = '#927000'
blue = '#2e7c78'
magenta = '#7e5ba6'
cyan = '#2a8585'
white = '#56664a'
light_black = '#97a887'
light_red = '#c2452a'
light_green = '#4e8c2e'
light_yellow = '#b05a1e'
light_blue = '#2e7c78'
light_magenta = '#7e5ba6'
light_cyan = '#2a8585'
light_white = '#354029'
