[colors]
background = '#120b2e'
foreground = '#fce7ff'
selection-background = '#34215c'
selection-foreground = '#5e577a'
cursor = '#ff2e97'
black = '#2a1a4a'
red = '#ff3d7f'
green = '#2ee6b6'
yellow = '#ffcb52'
blue = '#29b6ff'
magenta = '#b86bff'
cyan = '#18e0ff'
white = '#e6d4ff'
light_black = '#5e5388'
light_red = '#ff2e97'
light_green = '#2ee6b6'
light_yellow = '#ff7847'
light_blue = '#29b6ff'
light_magenta = '#b86bff'
light_cyan = '#18e0ff'
light_white = '#fce7ff'
