[colors]
background = '#e4e2e0'
foreground = '#061f4a'
selection-background = '#b8d2e5'
selection-foreground = '#061f4a'
cursor = '#061f4a'
black = '#080808'
red = '#7a0047'
green = '#145b0e'
yellow = '#733a11'
blue = '#002fa7'
magenta = '#5400a8'
cyan = '#00566b'
white = '#9c958d'
light_black = '#494440'
light_red = '#af1608'
light_green = '#4c6129'
light_yellow = '#7a5000'
light_blue = '#0d50c5'
light_magenta = '#952197'
light_cyan = '#006092'
light_white = '#ffffff'
