[colors]
background = '#17191d'
foreground = '#e8eaed'
selection-background = '#36393c'
selection-foreground = '#e8eaed'
cursor = '#e3b341'
black = '#0e1012'
red = '#e5484d'
green = '#33d17a'
yellow = '#e3b341'
blue = '#4d7cfe'
magenta = '#c86ad8'
cyan = '#3fc8b0'
white = '#c9cfd6'
light_black = '#9da4af'
light_red = '#ef8f92'
light_green = '#76e0a5'
light_yellow = '#edcf88'
light_blue = '#9eb8fe'
light_magenta = '#e0abe9'
light_cyan = '#7edaca'
light_white = '#e8eaed'
