[colors]
background = '#07100b'
foreground = '#ecf5ef'
selection-background = '#173425'
selection-foreground = '#f5fff8'
cursor = '#7ff0bd'
black = '#afbeb5'
red = '#ef8088'
green = '#72d1a0'
yellow = '#e6cb69'
blue = '#83b3e7'
magenta = '#cba0df'
cyan = '#72d3d0'
white = '#ecf5ef'
light_black = '#c4d0c9'
light_red = '#f19ba1'
light_green = '#91dfb7'
light_yellow = '#eddb8b'
light_blue = '#a3c8ef'
light_magenta = '#dabbe8'
light_cyan = '#94e2df'
light_white = '#ffffff'
