[colors]
background = '#131121'
foreground = '#ece9f7'
selection-background = '#2c2748'
selection-foreground = '#535161'
cursor = '#ffb3d6'
black = '#201b33'
red = '#ff6b92'
green = '#86e6b4'
yellow = '#ffc2ae'
blue = '#8fb4ff'
magenta = '#be9bff'
cyan = '#5fe3d8'
white = '#ece9f7'
light_black = '#6b678f'
light_red = '#ff81a2'
light_green = '#95e9bd'
light_yellow = '#f4d27e'
light_blue = '#b79bff'
light_magenta = '#ff9ed2'
light_cyan = '#72e6dd'
light_white = '#ffffff'
