[colors]
background = '#0e1317'
foreground = '#d6dad4'
selection-background = '#23384a'
selection-foreground = '#f0f2ec'
cursor = '#ffb23d'
black = '#222b34'
red = '#e8705e'
green = '#94c27e'
yellow = '#e9ad4e'
blue = '#6fa3d8'
magenta = '#d08aa3'
cyan = '#4dbaae'
white = '#b4bbb6'
light_black = '#76828d'
light_red = '#ff7b5e'
light_green = '#b3dd9d'
light_yellow = '#ffc03d'
light_blue = '#98c4f2'
light_magenta = '#f2afc2'
light_cyan = '#86ddd2'
light_white = '#f0f2ec'
