[colors]
background = '#3d3c1c'
foreground = '#f3edcf'
selection-background = '#5d5c37'
selection-foreground = '#fff8e3'
cursor = '#ded157'
black = '#c0bd9f'
red = '#e69a72'
green = '#a8c97c'
yellow = '#d9c164'
blue = '#91bdb5'
magenta = '#bd9eb0'
cyan = '#83c5b5'
white = '#f3edcf'
light_black = '#d1ceb2'
light_red = '#ecae8b'
light_green = '#bad598'
light_yellow = '#e4d181'
light_blue = '#a8ccc4'
light_magenta = '#cdb6c1'
light_cyan = '#9dd4c7'
light_white = '#fff8e5'
