[colors]
background = '#073b25'
foreground = '#efffdc'
selection-background = '#245c42'
selection-foreground = '#fbfff3'
cursor = '#9cf04d'
black = '#aec2b4'
red = '#f19a72'
green = '#9be86b'
yellow = '#f0cc58'
blue = '#86c8e3'
magenta = '#d99ed4'
cyan = '#7ad9ce'
white = '#efffdc'
light_black = '#c3d2c8'
light_red = '#f6ae8c'
light_green = '#b3ef88'
light_yellow = '#f6dc7b'
light_blue = '#a4d7eb'
light_magenta = '#e5b7df'
light_cyan = '#9ae5dc'
light_white = '#fbfff3'
