[colors]
background = '#ffffff'
foreground = '#333333'
selection-background = '#333333'
selection-foreground = '#ffffff'
cursor = '#333333'
black = '#ffffff'
red = '#333333'
green = '#444444'
yellow = '#555555'
blue = '#666666'
magenta = '#777777'
cyan = '#888888'
white = '#333333'
light_black = '#333333'
light_red = '#444444'
light_green = '#555555'
light_yellow = '#666666'
light_blue = '#777777'
light_magenta = '#888888'
light_cyan = '#999999'
light_white = '#aaaaaa'
