[colors]
background = '#050505'
foreground = '#f7f1ff'
selection-background = '#f7f1ff'
selection-foreground = '#050505'
cursor = '#f7f1ff'
black = '#0a0a0a'
red = '#fc618d'
green = '#7bd88f'
yellow = '#fce566'
blue = '#fd9353'
magenta = '#948ae3'
cyan = '#5ad4e6'
white = '#f7f1ff'
light_black = '#424242'
light_red = '#fc618d'
light_green = '#7bd88f'
light_yellow = '#fce566'
light_blue = '#fd9353'
light_magenta = '#948ae3'
light_cyan = '#5ad4e6'
light_white = '#f7f1ff'
