# EVH FrankenTone
[colors]
foreground = "#e10600"
background = "#0a0a0a"
cursor_bg = "#ffd400"
cursor_border = "#ffd400"
cursor_fg = "#2b82ff"
selection_bg = "#ff3b30"
selection_fg = "#a6e22e"

ansi = ["#151515","#e10600","#8fbd32","#ffd400","#2b82ff","#ff2d6d","#20bde5","#f4f4f4"]
brights = ["#474747","#ff5555","#b8e986","#ffe066","#66b3ff","#ff8fb1","#22d3ee","#f7f7f7"]
