# Green Phosphor CRT
[colors]
foreground = "#33ff33"
background = "#0b0f0b"
cursor_bg = "#33ff33"
cursor_border = "#33ff33"
cursor_fg = "#0b0f0b"
selection_bg = "#0a3a0a"
selection_fg = "#575b57"

ansi = ["#002200","#00aa00","#33ff33","#66ff66","#00cc44","#00ff88","#66ffaa","#b6ffb6"]
brights = ["#0a5a0a","#19cc19","#66ff66","#99ff99","#33ff77","#66ffaa","#99ffcc","#e6ffe6"]
