# Haunted House
[colors]
foreground = "#f1f4ed"
background = "#23394e"
cursor_bg = "#d5e2ee"
cursor_border = "#d5e2ee"
cursor_fg = "#23394e"
selection_bg = "#40566a"
selection_fg = "#ffffff"

ansi = ["#b9c2c9","#ed9b8c","#9fcba7","#e5cb7c","#9fc7e5","#c2add8","#93d0d0","#f1f4ed"]
brights = ["#ccd3d8","#f1afa3","#b3d8ba","#edda99","#b8d6ec","#d0c2e0","#addddd","#ffffff"]
