# Karma Dark HC
[colors]
foreground = "#ffffff"
background = "#000000"
cursor_bg = "#fce566"
cursor_border = "#fce566"
cursor_fg = "#000000"
selection_bg = "#4d4a5e"
selection_fg = "#ffffff"

ansi = ["#000000","#ff5c87","#80e598","#fce566","#61dceb","#b9a3ee","#61dceb","#d6d2db"]
brights = ["#69676c","#ff8aab","#a3e9b1","#fff080","#87e5f1","#cab6f4","#87e5f1","#ffffff"]
