# Karma Light
[colors]
foreground = "#0a0e14"
background = "#ffffff"
cursor_bg = "#a86efd"
cursor_border = "#a86efd"
cursor_fg = "#ffffff"
selection_bg = "#e5e3ea"
selection_fg = "#0a0e14"

ansi = ["#0a0e14","#fc618d","#2d972f","#eeae11","#5688c7","#6f42c1","#5688c7","#525053"]
brights = ["#999999","#fc618d","#2d972f","#ffaa33","#5688c7","#a86efd","#5688c7","#0a0e14"]
