# Keys Ocean Sunset HC
[colors]
foreground = "#f0f4fa"
background = "#060910"
cursor_bg = "#ff8531"
cursor_border = "#ff8531"
cursor_fg = "#060910"
selection_bg = "#2c4875"
selection_fg = "#ffffff"

ansi = ["#7a92a8","#ff6361","#4ad68a","#ffa600","#6aa8f0","#de72b0","#5edee8","#c8d8ec"]
brights = ["#8aa0b8","#ff8578","#72f0a8","#ffd380","#88c4ff","#f0a8d8","#88f0f8","#fff5be"]
