# Maple Jute
[colors]
foreground = "#fbe9d3"
background = "#56351f"
cursor_bg = "#ffdf9c"
cursor_border = "#ffdf9c"
cursor_fg = "#56351f"
selection_bg = "#8e684a"
selection_fg = "#fff8e8"

ansi = ["#cfb7a1","#f5a18d","#b9d8a1","#f2c87c","#a8c9ec","#dbb0dd","#9ed9d2","#fbe9d3"]
brights = ["#e2cbb7","#ffbd9e","#cfe6b2","#ffdf9c","#c2dafa","#ecc9ec","#b9e9e0","#fff7e8"]
