# Monsoon Mesa
[colors]
foreground = "#f8f1df"
background = "#164b58"
cursor_bg = "#f4c96a"
cursor_border = "#f4c96a"
cursor_fg = "#164b58"
selection_bg = "#356873"
selection_fg = "#fffbed"

ansi = ["#d0d8d6","#f7a18d","#98d9ac","#f0d278","#a7d1ef","#dfb1dc","#9ae1de","#f8f1df"]
brights = ["#dee4e2","#fbb7a6","#afe3bc","#f7e097","#c0def4","#e9c8e7","#b7ebe7","#fffdf4"]
