# Porcelain
[colors]
foreground = "#2a2e37"
background = "#fbfbfd"
cursor_bg = "#0054d1"
cursor_border = "#0054d1"
cursor_fg = "#fbfbfd"
selection_bg = "#dce6f7"
selection_fg = "#aeaeb0"

ansi = ["#2a2e37","#c60018","#157424","#855700","#004cc8","#761bc3","#006873","#5a6170"]
brights = ["#828896","#d60027","#1b842d","#af2700","#005bdb","#862ad2","#007f8f","#1b1e25"]
