# Saguaro
[colors]
foreground = "#fff0d5"
background = "#001c13"
cursor_bg = "#ffb52e"
cursor_border = "#ffb52e"
cursor_fg = "#001c13"
selection_bg = "#7b3d25"
selection_fg = "#fff4dc"

ansi = ["#aebdb5","#f08a68","#82d49d","#f2c85f","#72d2ce","#e887b0","#7bd9d5","#fff0d5"]
brights = ["#c5d0ca","#ffa078","#a2dfb5","#f8d982","#9be1dc","#f0a6c5","#a3e7e2","#fff9ea"]
