# X Tokio
[colors]
foreground = "#f7f1ff"
background = "#1c1c1d"
cursor_bg = "#f7f1ff"
cursor_border = "#f7f1ff"
cursor_fg = "#1c1c1d"
selection_bg = "#f7f1ff"
selection_fg = "#1c1c1d"

ansi = ["#1c1c1d","#fc618d","#7bd88f","#fce566","#fd9353","#948ae3","#5ad4e6","#f7f1ff"]
brights = ["#4f4f50","#fc618d","#7bd88f","#fce566","#fd9353","#948ae3","#5ad4e6","#f7f1ff"]
