color0 #afa3bd
color1 #ff6d98
color2 #8ed69e
color3 #e5c85f
color4 #62b9f2
color5 #d16cf0
color6 #4bd9e1
color7 #f4edff
color8 #b9aec5
color9 #ff7fa4
color10 #9cdbaa
color11 #e8cf72
color12 #75c1f4
color13 #d77ef2
color14 #61dee5
color15 #f5efff
background #1c082c
selection_foreground #1c082c
cursor #ff7fa4
cursor_text_color #1c082c
foreground #f4edff
selection_background #f4edff
