color0 #bfc4ce
color1 #f1958c
color2 #83cba2
color3 #e9c96c
color4 #83b9e6
color5 #c89edb
color6 #78ced3
color7 #fff0df
color8 #d0d4dc
color9 #f8aca5
color10 #9dd8b5
color11 #f2d98a
color12 #9fcaf0
color13 #d9b6e5
color14 #97dce0
color15 #fffaf2
background #172b54
selection_foreground #172b54
cursor #f3b85b
cursor_text_color #172b54
foreground #fff0df
selection_background #fff0df
