color0 #c7c0ba
color1 #ee9676
color2 #82c794
color3 #e5c05c
color4 #80bdd2
color5 #cc9fc1
color6 #75ccc7
color7 #fff0dc
color8 #d6d0ca
color9 #f4aa8d
color10 #9bd4a7
color11 #efd17d
color12 #9dcddd
color13 #dab6cf
color14 #94dad5
color15 #fff9ed
background #403637
selection_foreground #403637
cursor #f0b65c
cursor_text_color #403637
foreground #fff0dc
selection_background #fff0dc
