tags = ["dark"]

[theme.colors]
background = "#2b1050"
foreground = "#f2edff"
bright-foreground = "#e3cf7d"

[theme.colors.palette]
0 = "#b7acc9"
1 = "#ef8ca4"
2 = "#9ed08c"
3 = "#dfc86b"
4 = "#82c8ef"
5 = "#c18df0"
6 = "#77d7de"
7 = "#f2edff"
8 = "#c0b6cf"
9 = "#f19aaf"
10 = "#aad69a"
11 = "#e3cf7d"
12 = "#91cff1"
13 = "#c89bf2"
14 = "#87dce2"
15 = "#f4efff"
