tags = ["dark"]

[theme.colors]
background = "#54213e"
foreground = "#fff0df"
bright-foreground = "#f2a34f"

[theme.colors.palette]
0 = "#c9bbc3"
1 = "#f3958d"
2 = "#86ce91"
3 = "#edc95f"
4 = "#92c2e8"
5 = "#d99dcc"
6 = "#7ed5cf"
7 = "#fff0df"
8 = "#d9ccd2"
9 = "#f9aca5"
10 = "#9fdaaa"
11 = "#f6da80"
12 = "#afd2ef"
13 = "#e6b6d9"
14 = "#9ee2dd"
15 = "#fffaf2"
