tags = ["dark"]

[theme.colors]
background = "#2a2622"
foreground = "#e6ddd0"
bright-foreground = "#e6ddd0"

[theme.colors.palette]
0 = "#211d19"
1 = "#e77467"
2 = "#aab971"
3 = "#e1b869"
4 = "#78b3b5"
5 = "#c9a0bd"
6 = "#a5c4b1"
7 = "#c2b7a6"
8 = "#9a8e7c"
9 = "#f38f7e"
10 = "#becc8a"
11 = "#e39962"
12 = "#92c6c7"
13 = "#dab6d1"
14 = "#bbd6c3"
15 = "#f2eadb"
