tags = ["dark"]

[theme.colors]
background = "#172b54"
foreground = "#fff0df"
bright-foreground = "#ff9879"

[theme.colors.palette]
0 = "#bfc4ce"
1 = "#f1958c"
2 = "#83cba2"
3 = "#e9c96c"
4 = "#83b9e6"
5 = "#c89edb"
6 = "#78ced3"
7 = "#fff0df"
8 = "#d0d4dc"
9 = "#f8aca5"
10 = "#9dd8b5"
11 = "#f2d98a"
12 = "#9fcaf0"
13 = "#d9b6e5"
14 = "#97dce0"
15 = "#fffaf2"
