tags = ["dark"]

[theme.colors]
background = "#0b1220"
foreground = "#f8fafc"
bright-foreground = "#f8fafc"

[theme.colors.palette]
0 = "#3f4550"
1 = "#fb7185"
2 = "#22c55e"
3 = "#fbbf24"
4 = "#60a5fa"
5 = "#e879f9"
6 = "#22d3ee"
7 = "#b6c2d5"
8 = "#3d4452"
9 = "#fc8d9d"
10 = "#4ed17e"
11 = "#fccb4b"
12 = "#80b7fb"
13 = "#ed94fa"
14 = "#4edcf1"
15 = "#f8fafc"
