tags = ["dark"]

[theme.colors]
background = "#0d0b12"
foreground = "#f0edf6"
bright-foreground = "#d9a7ff"

[theme.colors.palette]
0 = "#b8b4c1"
1 = "#f08188"
2 = "#79d0a1"
3 = "#e9cb69"
4 = "#88b3e9"
5 = "#d5a2e6"
6 = "#7bd3da"
7 = "#f0edf6"
8 = "#cbc7d2"
9 = "#f29ca2"
10 = "#98deb7"
11 = "#efdc8a"
12 = "#a7c8f0"
13 = "#e3baed"
14 = "#9ce2e5"
15 = "#ffffff"
