tags = ["dark"]

[theme.colors]
background = "#392414"
foreground = "#f9e6c7"
bright-foreground = "#ffdb91"

[theme.colors.palette]
0 = "#cbb49b"
1 = "#f4a17c"
2 = "#a8c98b"
3 = "#f3c873"
4 = "#9dc5ed"
5 = "#d6a5d8"
6 = "#92d4d4"
7 = "#f9e6c7"
8 = "#e0cdb5"
9 = "#ffc29d"
10 = "#c3dca3"
11 = "#ffdb91"
12 = "#b9d9fa"
13 = "#e7bde9"
14 = "#afe6e2"
15 = "#fff5df"
