" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: 13th Floor
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "13th-Floor"

" Normal colors
hi Normal guifg=#f2e2c8 guibg=#4a0710

" Syntax highlighting groups
hi Comment guifg=#c5b4b7
hi Constant guifg=#d0af63
hi Identifier guifg=#849caf
hi Statement guifg=#e48e81
hi PreProc guifg=#c09cb1
hi Type guifg=#aab88f
hi Special guifg=#8bbbb4
hi Underlined guifg=#93a8b9 gui=underline
hi Error guifg=#e07f70 guibg=#4a0710
hi Todo guifg=#d6b976 guibg=#4a0710

" Additional groups for better compatibility
hi String guifg=#9eae80
hi Character guifg=#9eae80
hi Number guifg=#d0af63
hi Boolean guifg=#d0af63
hi Float guifg=#d0af63

hi Function guifg=#849caf

hi Conditional guifg=#e48e81
hi Repeat guifg=#e48e81
hi Label guifg=#e48e81
hi Operator guifg=#f2e2c8
hi Keyword guifg=#e48e81
hi Exception guifg=#e07f70

hi Include guifg=#c09cb1
hi Define guifg=#c09cb1
hi Macro guifg=#c09cb1
hi PreCondit guifg=#c09cb1

hi StorageClass guifg=#aab88f
hi Structure guifg=#aab88f
hi Typedef guifg=#aab88f

hi SpecialChar guifg=#8bbbb4
hi Tag guifg=#8bbbb4
hi Delimiter guifg=#f2e2c8
hi SpecialComment guifg=#c5b4b7
hi Debug guifg=#d6b976

hi Ignore guifg=#4a0710

" Cursor and line highlighting
hi Cursor guifg=#4a0710 guibg=#e48e81
hi CursorLine guibg=#c5b4b7
hi CursorColumn guibg=#c5b4b7

" Visual selection
hi Visual guibg=#c5b4b7

" Search highlighting
hi Search guibg=#d6b976 guifg=#4a0710
hi IncSearch guibg=#d6b976 guifg=#4a0710

" Line numbers
hi LineNr guifg=#c5b4b7
hi CursorLineNr guifg=#f2e2c8

" Status line
hi StatusLine guifg=#f2e2c8 guibg=#c5b4b7
hi StatusLineNC guifg=#c5b4b7 guibg=#4a0710

" Tab line
hi TabLine guifg=#c5b4b7 guibg=#4a0710
hi TabLineSel guifg=#f2e2c8 guibg=#c5b4b7
hi TabLineFill guibg=#4a0710

" Popup menu
hi Pmenu guifg=#f2e2c8 guibg=#c5b4b7
hi PmenuSel guifg=#4a0710 guibg=#c5b4b7
hi PmenuSbar guibg=#c5b4b7
hi PmenuThumb guibg=#f2e2c8

" Diff highlighting
hi DiffAdd guibg=#9eae80
hi DiffChange guibg=#d0af63
hi DiffDelete guibg=#e07f70
hi DiffText guibg=#849caf

" Fold highlighting
hi Folded guifg=#c5b4b7 guibg=#4a0710
hi FoldColumn guifg=#c5b4b7 guibg=#4a0710

" Spell checking
hi SpellBad gui=undercurl guisp=#e07f70
hi SpellCap gui=undercurl guisp=#849caf
hi SpellRare gui=undercurl guisp=#b78ea6
hi SpellLocal gui=undercurl guisp=#7bb2aa

" Error and warning messages
hi ErrorMsg guifg=#e07f70
hi WarningMsg guifg=#d0af63
hi MoreMsg guifg=#849caf
hi Question guifg=#9eae80

" Mode message
hi ModeMsg guifg=#9eae80

" Directory
hi Directory guifg=#849caf

" Title
hi Title guifg=#b78ea6

" Match parenthesis
hi MatchParen guibg=#c5b4b7

" Sign column
hi SignColumn guifg=#c5b4b7 guibg=#4a0710
