" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Aztec Sunset
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Aztec-Sunset"

" Normal colors
hi Normal guifg=#ffe6c7 guibg=#1b0c18

" Syntax highlighting groups
hi Comment guifg=#c0b4b0
hi Constant guifg=#e9bd59
hi Identifier guifg=#72c6c2
hi Statement guifg=#ff986d
hi PreProc guifg=#f194bd
hi Type guifg=#86d7a8
hi Special guifg=#89e2dc
hi Underlined guifg=#8bd8d2 gui=underline
hi Error guifg=#f47c62 guibg=#1b0c18
hi Todo guifg=#ffd071 guibg=#1b0c18

" Additional groups for better compatibility
hi String guifg=#67c894
hi Character guifg=#67c894
hi Number guifg=#e9bd59
hi Boolean guifg=#e9bd59
hi Float guifg=#e9bd59

hi Function guifg=#72c6c2

hi Conditional guifg=#ff986d
hi Repeat guifg=#ff986d
hi Label guifg=#ff986d
hi Operator guifg=#ffe6c7
hi Keyword guifg=#ff986d
hi Exception guifg=#f47c62

hi Include guifg=#f194bd
hi Define guifg=#f194bd
hi Macro guifg=#f194bd
hi PreCondit guifg=#f194bd

hi StorageClass guifg=#86d7a8
hi Structure guifg=#86d7a8
hi Typedef guifg=#86d7a8

hi SpecialChar guifg=#89e2dc
hi Tag guifg=#89e2dc
hi Delimiter guifg=#ffe6c7
hi SpecialComment guifg=#c0b4b0
hi Debug guifg=#ffd071

hi Ignore guifg=#1b0c18

" Cursor and line highlighting
hi Cursor guifg=#1b0c18 guibg=#ff9f2e
hi CursorLine guibg=#743829
hi CursorColumn guibg=#743829

" Visual selection
hi Visual guibg=#743829

" Search highlighting
hi Search guibg=#ffd071 guifg=#1b0c18
hi IncSearch guibg=#ffd071 guifg=#1b0c18

" Line numbers
hi LineNr guifg=#c0b4b0
hi CursorLineNr guifg=#ffe6c7

" Status line
hi StatusLine guifg=#ffe6c7 guibg=#c0b4b0
hi StatusLineNC guifg=#c0b4b0 guibg=#1b0c18

" Tab line
hi TabLine guifg=#c0b4b0 guibg=#1b0c18
hi TabLineSel guifg=#ffe6c7 guibg=#743829
hi TabLineFill guibg=#1b0c18

" Popup menu
hi Pmenu guifg=#ffe6c7 guibg=#c0b4b0
hi PmenuSel guifg=#1b0c18 guibg=#743829
hi PmenuSbar guibg=#c0b4b0
hi PmenuThumb guibg=#ffe6c7

" Diff highlighting
hi DiffAdd guibg=#67c894
hi DiffChange guibg=#e9bd59
hi DiffDelete guibg=#f47c62
hi DiffText guibg=#72c6c2

" Fold highlighting
hi Folded guifg=#c0b4b0 guibg=#1b0c18
hi FoldColumn guifg=#c0b4b0 guibg=#1b0c18

" Spell checking
hi SpellBad gui=undercurl guisp=#f47c62
hi SpellCap gui=undercurl guisp=#72c6c2
hi SpellRare gui=undercurl guisp=#e778a8
hi SpellLocal gui=undercurl guisp=#65d5d0

" Error and warning messages
hi ErrorMsg guifg=#f47c62
hi WarningMsg guifg=#e9bd59
hi MoreMsg guifg=#72c6c2
hi Question guifg=#67c894

" Mode message
hi ModeMsg guifg=#67c894

" Directory
hi Directory guifg=#72c6c2

" Title
hi Title guifg=#e778a8

" Match parenthesis
hi MatchParen guibg=#c0b4b0

" Sign column
hi SignColumn guifg=#c0b4b0 guibg=#1b0c18
