" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Barrel Cactus
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Barrel-Cactus"

" Normal colors
hi Normal guifg=#fff0d3 guibg=#145039

" Syntax highlighting groups
hi Comment guifg=#cedbd1
hi Constant guifg=#eac95f
hi Identifier guifg=#83bfd8
hi Statement guifg=#f8ab89
hi PreProc guifg=#e4b7cf
hi Type guifg=#a3dcaf
hi Special guifg=#96dfd7
hi Underlined guifg=#9fcfe2 gui=underline
hi Error guifg=#f5a181 guibg=#145039
hi Todo guifg=#f3d97f guibg=#145039

" Additional groups for better compatibility
hi String guifg=#8bd19b
hi Character guifg=#8bd19b
hi Number guifg=#eac95f
hi Boolean guifg=#eac95f
hi Float guifg=#eac95f

hi Function guifg=#83bfd8

hi Conditional guifg=#f8ab89
hi Repeat guifg=#f8ab89
hi Label guifg=#f8ab89
hi Operator guifg=#fff0d3
hi Keyword guifg=#f8ab89
hi Exception guifg=#f5a181

hi Include guifg=#e4b7cf
hi Define guifg=#e4b7cf
hi Macro guifg=#e4b7cf
hi PreCondit guifg=#e4b7cf

hi StorageClass guifg=#a3dcaf
hi Structure guifg=#a3dcaf
hi Typedef guifg=#a3dcaf

hi SpecialChar guifg=#96dfd7
hi Tag guifg=#96dfd7
hi Delimiter guifg=#fff0d3
hi SpecialComment guifg=#cedbd1
hi Debug guifg=#f3d97f

hi Ignore guifg=#145039

" Cursor and line highlighting
hi Cursor guifg=#145039 guibg=#f0bb4d
hi CursorLine guibg=#326b56
hi CursorColumn guibg=#326b56

" Visual selection
hi Visual guibg=#326b56

" Search highlighting
hi Search guibg=#f3d97f guifg=#145039
hi IncSearch guibg=#f3d97f guifg=#145039

" Line numbers
hi LineNr guifg=#cedbd1
hi CursorLineNr guifg=#fff0d3

" Status line
hi StatusLine guifg=#fff0d3 guibg=#cedbd1
hi StatusLineNC guifg=#cedbd1 guibg=#145039

" Tab line
hi TabLine guifg=#cedbd1 guibg=#145039
hi TabLineSel guifg=#fff0d3 guibg=#326b56
hi TabLineFill guibg=#145039

" Popup menu
hi Pmenu guifg=#fff0d3 guibg=#cedbd1
hi PmenuSel guifg=#145039 guibg=#326b56
hi PmenuSbar guibg=#cedbd1
hi PmenuThumb guibg=#fff0d3

" Diff highlighting
hi DiffAdd guibg=#8bd19b
hi DiffChange guibg=#eac95f
hi DiffDelete guibg=#f5a181
hi DiffText guibg=#83bfd8

" Fold highlighting
hi Folded guifg=#cedbd1 guibg=#145039
hi FoldColumn guifg=#cedbd1 guibg=#145039

" Spell checking
hi SpellBad gui=undercurl guisp=#f5a181
hi SpellCap gui=undercurl guisp=#83bfd8
hi SpellRare gui=undercurl guisp=#dcaac8
hi SpellLocal gui=undercurl guisp=#77d3ca

" Error and warning messages
hi ErrorMsg guifg=#f5a181
hi WarningMsg guifg=#eac95f
hi MoreMsg guifg=#83bfd8
hi Question guifg=#8bd19b

" Mode message
hi ModeMsg guifg=#8bd19b

" Directory
hi Directory guifg=#83bfd8

" Title
hi Title guifg=#dcaac8

" Match parenthesis
hi MatchParen guibg=#cedbd1

" Sign column
hi SignColumn guifg=#cedbd1 guibg=#145039
