" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Candy Corn
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Candy-Corn"

" Normal colors
hi Normal guifg=#51463b guibg=#fff0d2

" Syntax highlighting groups
hi Comment guifg=#29231e
hi Constant guifg=#785711
hi Identifier guifg=#36516b
hi Statement guifg=#7f270f
hi PreProc guifg=#56355a
hi Type guifg=#395025
hi Special guifg=#215357
hi Underlined guifg=#2c4258 gui=underline
hi Error guifg=#9b2f12 guibg=#fff0d2
hi Todo guifg=#62470e guibg=#fff0d2

" Additional groups for better compatibility
hi String guifg=#46612d
hi Character guifg=#46612d
hi Number guifg=#785711
hi Boolean guifg=#785711
hi Float guifg=#785711

hi Function guifg=#36516b

hi Conditional guifg=#7f270f
hi Repeat guifg=#7f270f
hi Label guifg=#7f270f
hi Operator guifg=#51463b
hi Keyword guifg=#7f270f
hi Exception guifg=#9b2f12

hi Include guifg=#56355a
hi Define guifg=#56355a
hi Macro guifg=#56355a
hi PreCondit guifg=#56355a

hi StorageClass guifg=#395025
hi Structure guifg=#395025
hi Typedef guifg=#395025

hi SpecialChar guifg=#215357
hi Tag guifg=#215357
hi Delimiter guifg=#51463b
hi SpecialComment guifg=#29231e
hi Debug guifg=#62470e

hi Ignore guifg=#fff0d2

" Cursor and line highlighting
hi Cursor guifg=#fff0d2 guibg=#24150e
hi CursorLine guibg=#f6c89b
hi CursorColumn guibg=#f6c89b

" Visual selection
hi Visual guibg=#f6c89b

" Search highlighting
hi Search guibg=#62470e guifg=#fff0d2
hi IncSearch guibg=#62470e guifg=#fff0d2

" Line numbers
hi LineNr guifg=#29231e
hi CursorLineNr guifg=#51463b

" Status line
hi StatusLine guifg=#51463b guibg=#29231e
hi StatusLineNC guifg=#29231e guibg=#fff0d2

" Tab line
hi TabLine guifg=#29231e guibg=#fff0d2
hi TabLineSel guifg=#51463b guibg=#f6c89b
hi TabLineFill guibg=#fff0d2

" Popup menu
hi Pmenu guifg=#51463b guibg=#29231e
hi PmenuSel guifg=#fff0d2 guibg=#f6c89b
hi PmenuSbar guibg=#29231e
hi PmenuThumb guibg=#51463b

" Diff highlighting
hi DiffAdd guibg=#46612d
hi DiffChange guibg=#785711
hi DiffDelete guibg=#9b2f12
hi DiffText guibg=#36516b

" Fold highlighting
hi Folded guifg=#29231e guibg=#fff0d2
hi FoldColumn guifg=#29231e guibg=#fff0d2

" Spell checking
hi SpellBad gui=undercurl guisp=#9b2f12
hi SpellCap gui=undercurl guisp=#36516b
hi SpellRare gui=undercurl guisp=#69416e
hi SpellLocal gui=undercurl guisp=#28656a

" Error and warning messages
hi ErrorMsg guifg=#9b2f12
hi WarningMsg guifg=#785711
hi MoreMsg guifg=#36516b
hi Question guifg=#46612d

" Mode message
hi ModeMsg guifg=#46612d

" Directory
hi Directory guifg=#36516b

" Title
hi Title guifg=#69416e

" Match parenthesis
hi MatchParen guibg=#29231e

" Sign column
hi SignColumn guifg=#29231e guibg=#fff0d2
