" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Candlelight
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Candlelight"

" Normal colors
hi Normal guifg=#f8e7c4 guibg=#432708

" Syntax highlighting groups
hi Comment guifg=#cfc1aa
hi Constant guifg=#dfbb53
hi Identifier guifg=#83aebd
hi Statement guifg=#eba374
hi PreProc guifg=#c49eaf
hi Type guifg=#a6be8c
hi Special guifg=#89c1b8
hi Underlined guifg=#92b8c5 gui=underline
hi Error guifg=#e89661 guibg=#432708
hi Todo guifg=#e3c368 guibg=#432708

" Additional groups for better compatibility
hi String guifg=#9ab57c
hi Character guifg=#9ab57c
hi Number guifg=#dfbb53
hi Boolean guifg=#dfbb53
hi Float guifg=#dfbb53

hi Function guifg=#83aebd

hi Conditional guifg=#eba374
hi Repeat guifg=#eba374
hi Label guifg=#eba374
hi Operator guifg=#f8e7c4
hi Keyword guifg=#eba374
hi Exception guifg=#e89661

hi Include guifg=#c49eaf
hi Define guifg=#c49eaf
hi Macro guifg=#c49eaf
hi PreCondit guifg=#c49eaf

hi StorageClass guifg=#a6be8c
hi Structure guifg=#a6be8c
hi Typedef guifg=#a6be8c

hi SpecialChar guifg=#89c1b8
hi Tag guifg=#89c1b8
hi Delimiter guifg=#f8e7c4
hi SpecialComment guifg=#cfc1aa
hi Debug guifg=#e3c368

hi Ignore guifg=#432708

" Cursor and line highlighting
hi Cursor guifg=#432708 guibg=#eba374
hi CursorLine guibg=#cfc1aa
hi CursorColumn guibg=#cfc1aa

" Visual selection
hi Visual guibg=#cfc1aa

" Search highlighting
hi Search guibg=#e3c368 guifg=#432708
hi IncSearch guibg=#e3c368 guifg=#432708

" Line numbers
hi LineNr guifg=#cfc1aa
hi CursorLineNr guifg=#f8e7c4

" Status line
hi StatusLine guifg=#f8e7c4 guibg=#cfc1aa
hi StatusLineNC guifg=#cfc1aa guibg=#432708

" Tab line
hi TabLine guifg=#cfc1aa guibg=#432708
hi TabLineSel guifg=#f8e7c4 guibg=#cfc1aa
hi TabLineFill guibg=#432708

" Popup menu
hi Pmenu guifg=#f8e7c4 guibg=#cfc1aa
hi PmenuSel guifg=#432708 guibg=#cfc1aa
hi PmenuSbar guibg=#cfc1aa
hi PmenuThumb guibg=#f8e7c4

" Diff highlighting
hi DiffAdd guibg=#9ab57c
hi DiffChange guibg=#dfbb53
hi DiffDelete guibg=#e89661
hi DiffText guibg=#83aebd

" Fold highlighting
hi Folded guifg=#cfc1aa guibg=#432708
hi FoldColumn guifg=#cfc1aa guibg=#432708

" Spell checking
hi SpellBad gui=undercurl guisp=#e89661
hi SpellCap gui=undercurl guisp=#83aebd
hi SpellRare gui=undercurl guisp=#bc91a4
hi SpellLocal gui=undercurl guisp=#79b8ae

" Error and warning messages
hi ErrorMsg guifg=#e89661
hi WarningMsg guifg=#dfbb53
hi MoreMsg guifg=#83aebd
hi Question guifg=#9ab57c

" Mode message
hi ModeMsg guifg=#9ab57c

" Directory
hi Directory guifg=#83aebd

" Title
hi Title guifg=#bc91a4

" Match parenthesis
hi MatchParen guibg=#cfc1aa

" Sign column
hi SignColumn guifg=#cfc1aa guibg=#432708
