" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Carbon Paper
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Carbon-Paper"

" Normal colors
hi Normal guifg=#1d2028 guibg=#f8f6ed

" Syntax highlighting groups
hi Comment guifg=#474b53
hi Constant guifg=#654d00
hi Identifier guifg=#17458b
hi Statement guifg=#902a2a
hi PreProc guifg=#67398f
hi Type guifg=#185f3d
hi Special guifg=#004b57
hi Underlined guifg=#123a78 gui=underline
hi Error guifg=#842424 guibg=#f8f6ed
hi Todo guifg=#6d5300 guibg=#f8f6ed

" Additional groups for better compatibility
hi String guifg=#145a37
hi Character guifg=#145a37
hi Number guifg=#654d00
hi Boolean guifg=#654d00
hi Float guifg=#654d00

hi Function guifg=#17458b

hi Conditional guifg=#902a2a
hi Repeat guifg=#902a2a
hi Label guifg=#902a2a
hi Operator guifg=#3c4048
hi Keyword guifg=#902a2a
hi Exception guifg=#842424

hi Include guifg=#67398f
hi Define guifg=#67398f
hi Macro guifg=#67398f
hi PreCondit guifg=#67398f

hi StorageClass guifg=#185f3d
hi Structure guifg=#185f3d
hi Typedef guifg=#185f3d

hi SpecialChar guifg=#004b57
hi Tag guifg=#004b57
hi Delimiter guifg=#3c4048
hi SpecialComment guifg=#474b53
hi Debug guifg=#6d5300

hi Ignore guifg=#f8f6ed

" Cursor and line highlighting
hi Cursor guifg=#f8f6ed guibg=#31558e
hi CursorLine guibg=#ddd9cb
hi CursorColumn guibg=#ddd9cb

" Visual selection
hi Visual guibg=#ddd9cb

" Search highlighting
hi Search guibg=#6d5300 guifg=#f8f6ed
hi IncSearch guibg=#6d5300 guifg=#f8f6ed

" Line numbers
hi LineNr guifg=#474b53
hi CursorLineNr guifg=#1d2028

" Status line
hi StatusLine guifg=#1d2028 guibg=#474b53
hi StatusLineNC guifg=#474b53 guibg=#f8f6ed

" Tab line
hi TabLine guifg=#474b53 guibg=#f8f6ed
hi TabLineSel guifg=#1d2028 guibg=#ddd9cb
hi TabLineFill guibg=#f8f6ed

" Popup menu
hi Pmenu guifg=#1d2028 guibg=#474b53
hi PmenuSel guifg=#f8f6ed guibg=#ddd9cb
hi PmenuSbar guibg=#474b53
hi PmenuThumb guibg=#1d2028

" Diff highlighting
hi DiffAdd guibg=#145a37
hi DiffChange guibg=#654d00
hi DiffDelete guibg=#842424
hi DiffText guibg=#17458b

" Fold highlighting
hi Folded guifg=#474b53 guibg=#f8f6ed
hi FoldColumn guifg=#474b53 guibg=#f8f6ed

" Spell checking
hi SpellBad gui=undercurl guisp=#842424
hi SpellCap gui=undercurl guisp=#17458b
hi SpellRare gui=undercurl guisp=#603187
hi SpellLocal gui=undercurl guisp=#005866

" Error and warning messages
hi ErrorMsg guifg=#842424
hi WarningMsg guifg=#654d00
hi MoreMsg guifg=#17458b
hi Question guifg=#145a37

" Mode message
hi ModeMsg guifg=#145a37

" Directory
hi Directory guifg=#17458b

" Title
hi Title guifg=#603187

" Match parenthesis
hi MatchParen guibg=#474b53

" Sign column
hi SignColumn guifg=#474b53 guibg=#f8f6ed
