" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Cassette Tape
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Cassette-Tape"

" Normal colors
hi Normal guifg=#2b1b12 guibg=#fff7ed

" Syntax highlighting groups
hi Comment guifg=#c4b39a
hi Constant guifg=#be123c
hi Identifier guifg=#7c2d12
hi Statement guifg=#941616
hi PreProc guifg=#0c5e58
hi Type guifg=#324e0e
hi Special guifg=#904207
hi Underlined guifg=#63240e gui=underline
hi Error guifg=#b91c1c guibg=#fff7ed
hi Todo guifg=#9c0f31 guibg=#fff7ed

" Additional groups for better compatibility
hi String guifg=#3f6212
hi Character guifg=#3f6212
hi Number guifg=#be123c
hi Boolean guifg=#be123c
hi Float guifg=#be123c

hi Function guifg=#7c2d12

hi Conditional guifg=#941616
hi Repeat guifg=#941616
hi Label guifg=#941616
hi Operator guifg=#6b4f3f
hi Keyword guifg=#941616
hi Exception guifg=#b91c1c

hi Include guifg=#0c5e58
hi Define guifg=#0c5e58
hi Macro guifg=#0c5e58
hi PreCondit guifg=#0c5e58

hi StorageClass guifg=#324e0e
hi Structure guifg=#324e0e
hi Typedef guifg=#324e0e

hi SpecialChar guifg=#904207
hi Tag guifg=#904207
hi Delimiter guifg=#6b4f3f
hi SpecialComment guifg=#c4b39a
hi Debug guifg=#9c0f31

hi Ignore guifg=#fff7ed

" Cursor and line highlighting
hi Cursor guifg=#fff7ed guibg=#2b1b12
hi CursorLine guibg=#2b1b12
hi CursorColumn guibg=#2b1b12

" Visual selection
hi Visual guibg=#2b1b12

" Search highlighting
hi Search guibg=#9c0f31 guifg=#fff7ed
hi IncSearch guibg=#9c0f31 guifg=#fff7ed

" Line numbers
hi LineNr guifg=#c4b39a
hi CursorLineNr guifg=#2b1b12

" Status line
hi StatusLine guifg=#2b1b12 guibg=#c4b39a
hi StatusLineNC guifg=#c4b39a guibg=#fff7ed

" Tab line
hi TabLine guifg=#c4b39a guibg=#fff7ed
hi TabLineSel guifg=#2b1b12 guibg=#2b1b12
hi TabLineFill guibg=#fff7ed

" Popup menu
hi Pmenu guifg=#2b1b12 guibg=#c4b39a
hi PmenuSel guifg=#fff7ed guibg=#2b1b12
hi PmenuSbar guibg=#c4b39a
hi PmenuThumb guibg=#2b1b12

" Diff highlighting
hi DiffAdd guibg=#3f6212
hi DiffChange guibg=#be123c
hi DiffDelete guibg=#b91c1c
hi DiffText guibg=#7c2d12

" Fold highlighting
hi Folded guifg=#c4b39a guibg=#fff7ed
hi FoldColumn guifg=#c4b39a guibg=#fff7ed

" Spell checking
hi SpellBad gui=undercurl guisp=#b91c1c
hi SpellCap gui=undercurl guisp=#7c2d12
hi SpellRare gui=undercurl guisp=#0f766e
hi SpellLocal gui=undercurl guisp=#b45309

" Error and warning messages
hi ErrorMsg guifg=#b91c1c
hi WarningMsg guifg=#be123c
hi MoreMsg guifg=#7c2d12
hi Question guifg=#3f6212

" Mode message
hi ModeMsg guifg=#3f6212

" Directory
hi Directory guifg=#7c2d12

" Title
hi Title guifg=#0f766e

" Match parenthesis
hi MatchParen guibg=#c4b39a

" Sign column
hi SignColumn guifg=#c4b39a guibg=#fff7ed
