" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Charcoal
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Charcoal"

" Normal colors
hi Normal guifg=#c4c4c4 guibg=#0d0d0d

" Syntax highlighting groups
hi Comment guifg=#474747
hi Constant guifg=#b0b0b0
hi Identifier guifg=#9a9a9a
hi Statement guifg=#a0a0a0
hi PreProc guifg=#b8b8b8
hi Type guifg=#c4c4c4
hi Special guifg=#cccccc
hi Underlined guifg=#d0d0d0 gui=underline
hi Error guifg=#888888 guibg=#0d0d0d
hi Todo guifg=#c8c8c8 guibg=#0d0d0d

" Additional groups for better compatibility
hi String guifg=#a8a8a8
hi Character guifg=#a8a8a8
hi Number guifg=#b0b0b0
hi Boolean guifg=#b0b0b0
hi Float guifg=#b0b0b0

hi Function guifg=#9a9a9a

hi Conditional guifg=#a0a0a0
hi Repeat guifg=#a0a0a0
hi Label guifg=#a0a0a0
hi Operator guifg=#c0c0c0
hi Keyword guifg=#a0a0a0
hi Exception guifg=#888888

hi Include guifg=#b8b8b8
hi Define guifg=#b8b8b8
hi Macro guifg=#b8b8b8
hi PreCondit guifg=#b8b8b8

hi StorageClass guifg=#c4c4c4
hi Structure guifg=#c4c4c4
hi Typedef guifg=#c4c4c4

hi SpecialChar guifg=#cccccc
hi Tag guifg=#cccccc
hi Delimiter guifg=#c0c0c0
hi SpecialComment guifg=#474747
hi Debug guifg=#c8c8c8

hi Ignore guifg=#0d0d0d

" Cursor and line highlighting
hi Cursor guifg=#0d0d0d guibg=#d0d0d0
hi CursorLine guibg=#2e2e2e
hi CursorColumn guibg=#2e2e2e

" Visual selection
hi Visual guibg=#2e2e2e

" Search highlighting
hi Search guibg=#c8c8c8 guifg=#0d0d0d
hi IncSearch guibg=#c8c8c8 guifg=#0d0d0d

" Line numbers
hi LineNr guifg=#474747
hi CursorLineNr guifg=#c4c4c4

" Status line
hi StatusLine guifg=#c4c4c4 guibg=#474747
hi StatusLineNC guifg=#474747 guibg=#0d0d0d

" Tab line
hi TabLine guifg=#474747 guibg=#0d0d0d
hi TabLineSel guifg=#c4c4c4 guibg=#2e2e2e
hi TabLineFill guibg=#0d0d0d

" Popup menu
hi Pmenu guifg=#c4c4c4 guibg=#474747
hi PmenuSel guifg=#0d0d0d guibg=#2e2e2e
hi PmenuSbar guibg=#474747
hi PmenuThumb guibg=#c4c4c4

" Diff highlighting
hi DiffAdd guibg=#a8a8a8
hi DiffChange guibg=#b0b0b0
hi DiffDelete guibg=#888888
hi DiffText guibg=#9a9a9a

" Fold highlighting
hi Folded guifg=#474747 guibg=#0d0d0d
hi FoldColumn guifg=#474747 guibg=#0d0d0d

" Spell checking
hi SpellBad gui=undercurl guisp=#888888
hi SpellCap gui=undercurl guisp=#9a9a9a
hi SpellRare gui=undercurl guisp=#8a8a8a
hi SpellLocal gui=undercurl guisp=#a0a0a0

" Error and warning messages
hi ErrorMsg guifg=#888888
hi WarningMsg guifg=#b0b0b0
hi MoreMsg guifg=#9a9a9a
hi Question guifg=#a8a8a8

" Mode message
hi ModeMsg guifg=#a8a8a8

" Directory
hi Directory guifg=#9a9a9a

" Title
hi Title guifg=#8a8a8a

" Match parenthesis
hi MatchParen guibg=#474747

" Sign column
hi SignColumn guifg=#474747 guibg=#0d0d0d
