" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Cholla
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Cholla"

" Normal colors
hi Normal guifg=#fff0d4 guibg=#394122

" Syntax highlighting groups
hi Comment guifg=#d7d8c7
hi Constant guifg=#e9c65c
hi Identifier guifg=#82bdd8
hi Statement guifg=#f5ad8c
hi PreProc guifg=#e3b3ca
hi Type guifg=#9ed7a6
hi Special guifg=#94ddd5
hi Underlined guifg=#9dcee3 gui=underline
hi Error guifg=#ee9a74 guibg=#394122
hi Todo guifg=#f3d77d guibg=#394122

" Additional groups for better compatibility
hi String guifg=#83cb8f
hi Character guifg=#83cb8f
hi Number guifg=#e9c65c
hi Boolean guifg=#e9c65c
hi Float guifg=#e9c65c

hi Function guifg=#82bdd8

hi Conditional guifg=#f5ad8c
hi Repeat guifg=#f5ad8c
hi Label guifg=#f5ad8c
hi Operator guifg=#fff0d4
hi Keyword guifg=#f5ad8c
hi Exception guifg=#ee9a74

hi Include guifg=#e3b3ca
hi Define guifg=#e3b3ca
hi Macro guifg=#e3b3ca
hi PreCondit guifg=#e3b3ca

hi StorageClass guifg=#9ed7a6
hi Structure guifg=#9ed7a6
hi Typedef guifg=#9ed7a6

hi SpecialChar guifg=#94ddd5
hi Tag guifg=#94ddd5
hi Delimiter guifg=#fff0d4
hi SpecialComment guifg=#d7d8c7
hi Debug guifg=#f3d77d

hi Ignore guifg=#394122

" Cursor and line highlighting
hi Cursor guifg=#394122 guibg=#f3c85d
hi CursorLine guibg=#59603d
hi CursorColumn guibg=#59603d

" Visual selection
hi Visual guibg=#59603d

" Search highlighting
hi Search guibg=#f3d77d guifg=#394122
hi IncSearch guibg=#f3d77d guifg=#394122

" Line numbers
hi LineNr guifg=#d7d8c7
hi CursorLineNr guifg=#fff0d4

" Status line
hi StatusLine guifg=#fff0d4 guibg=#d7d8c7
hi StatusLineNC guifg=#d7d8c7 guibg=#394122

" Tab line
hi TabLine guifg=#d7d8c7 guibg=#394122
hi TabLineSel guifg=#fff0d4 guibg=#59603d
hi TabLineFill guibg=#394122

" Popup menu
hi Pmenu guifg=#fff0d4 guibg=#d7d8c7
hi PmenuSel guifg=#394122 guibg=#59603d
hi PmenuSbar guibg=#d7d8c7
hi PmenuThumb guibg=#fff0d4

" Diff highlighting
hi DiffAdd guibg=#83cb8f
hi DiffChange guibg=#e9c65c
hi DiffDelete guibg=#ee9a74
hi DiffText guibg=#82bdd8

" Fold highlighting
hi Folded guifg=#d7d8c7 guibg=#394122
hi FoldColumn guifg=#d7d8c7 guibg=#394122

" Spell checking
hi SpellBad gui=undercurl guisp=#ee9a74
hi SpellCap gui=undercurl guisp=#82bdd8
hi SpellRare gui=undercurl guisp=#d79abb
hi SpellLocal gui=undercurl guisp=#75d0c6

" Error and warning messages
hi ErrorMsg guifg=#ee9a74
hi WarningMsg guifg=#e9c65c
hi MoreMsg guifg=#82bdd8
hi Question guifg=#83cb8f

" Mode message
hi ModeMsg guifg=#83cb8f

" Directory
hi Directory guifg=#82bdd8

" Title
hi Title guifg=#d79abb

" Match parenthesis
hi MatchParen guibg=#d7d8c7

" Sign column
hi SignColumn guifg=#d7d8c7 guibg=#394122
