" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Clockwork Gold
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Clockwork-Gold"

" Normal colors
hi Normal guifg=#ebe8e0 guibg=#1d1c19

" Syntax highlighting groups
hi Comment guifg=#4c4b47
hi Constant guifg=#ffcc00
hi Identifier guifg=#4fa3f4
hi Statement guifg=#ff716b
hi PreProc guifg=#ff68c6
hi Type guifg=#88e196
hi Special guifg=#82e1e0
hi Underlined guifg=#76c0ff gui=underline
hi Error guifg=#e94b4a guibg=#1d1c19
hi Todo guifg=#c89f00 guibg=#1d1c19

" Additional groups for better compatibility
hi String guifg=#73c881
hi Character guifg=#73c881
hi Number guifg=#ffcc00
hi Boolean guifg=#ffcc00
hi Float guifg=#ffcc00

hi Function guifg=#4fa3f4

hi Conditional guifg=#ff716b
hi Repeat guifg=#ff716b
hi Label guifg=#ff716b
hi Operator guifg=#a9a69d
hi Keyword guifg=#ff716b
hi Exception guifg=#e94b4a

hi Include guifg=#ff68c6
hi Define guifg=#ff68c6
hi Macro guifg=#ff68c6
hi PreCondit guifg=#ff68c6

hi StorageClass guifg=#88e196
hi Structure guifg=#88e196
hi Typedef guifg=#88e196

hi SpecialChar guifg=#82e1e0
hi Tag guifg=#82e1e0
hi Delimiter guifg=#a9a69d
hi SpecialComment guifg=#4c4b47
hi Debug guifg=#c89f00

hi Ignore guifg=#1d1c19

" Cursor and line highlighting
hi Cursor guifg=#1d1c19 guibg=#ffcc00
hi CursorLine guibg=#4c4b47
hi CursorColumn guibg=#4c4b47

" Visual selection
hi Visual guibg=#4c4b47

" Search highlighting
hi Search guibg=#c89f00 guifg=#1d1c19
hi IncSearch guibg=#c89f00 guifg=#1d1c19

" Line numbers
hi LineNr guifg=#4c4b47
hi CursorLineNr guifg=#ebe8e0

" Status line
hi StatusLine guifg=#ebe8e0 guibg=#4c4b47
hi StatusLineNC guifg=#4c4b47 guibg=#1d1c19

" Tab line
hi TabLine guifg=#4c4b47 guibg=#1d1c19
hi TabLineSel guifg=#ebe8e0 guibg=#4c4b47
hi TabLineFill guibg=#1d1c19

" Popup menu
hi Pmenu guifg=#ebe8e0 guibg=#4c4b47
hi PmenuSel guifg=#1d1c19 guibg=#4c4b47
hi PmenuSbar guibg=#4c4b47
hi PmenuThumb guibg=#ebe8e0

" Diff highlighting
hi DiffAdd guibg=#73c881
hi DiffChange guibg=#ffcc00
hi DiffDelete guibg=#e94b4a
hi DiffText guibg=#4fa3f4

" Fold highlighting
hi Folded guifg=#4c4b47 guibg=#1d1c19
hi FoldColumn guifg=#4c4b47 guibg=#1d1c19

" Spell checking
hi SpellBad gui=undercurl guisp=#e94b4a
hi SpellCap gui=undercurl guisp=#4fa3f4
hi SpellRare gui=undercurl guisp=#ef3ead
hi SpellLocal gui=undercurl guisp=#64c3c3

" Error and warning messages
hi ErrorMsg guifg=#e94b4a
hi WarningMsg guifg=#ffcc00
hi MoreMsg guifg=#4fa3f4
hi Question guifg=#73c881

" Mode message
hi ModeMsg guifg=#73c881

" Directory
hi Directory guifg=#4fa3f4

" Title
hi Title guifg=#ef3ead

" Match parenthesis
hi MatchParen guibg=#4c4b47

" Sign column
hi SignColumn guifg=#4c4b47 guibg=#1d1c19
