" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: CRT Afterglow
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "CRT-Afterglow"

" Normal colors
hi Normal guifg=#d0d8c8 guibg=#0b0f0b

" Syntax highlighting groups
hi Comment guifg=#4a5d4a
hi Constant guifg=#f1fa8c
hi Identifier guifg=#8be9fd
hi Statement guifg=#ff8a80
hi PreProc guifg=#dda0ff
hi Type guifg=#8aff9d
hi Special guifg=#8affd8
hi Underlined guifg=#b3f1ff gui=underline
hi Error guifg=#ff5f56 guibg=#0b0f0b
hi Todo guifg=#fff59d guibg=#0b0f0b

" Additional groups for better compatibility
hi String guifg=#50fa7b
hi Character guifg=#50fa7b
hi Number guifg=#f1fa8c
hi Boolean guifg=#f1fa8c
hi Float guifg=#f1fa8c

hi Function guifg=#8be9fd

hi Conditional guifg=#ff8a80
hi Repeat guifg=#ff8a80
hi Label guifg=#ff8a80
hi Operator guifg=#95a99b
hi Keyword guifg=#ff8a80
hi Exception guifg=#ff5f56

hi Include guifg=#dda0ff
hi Define guifg=#dda0ff
hi Macro guifg=#dda0ff
hi PreCondit guifg=#dda0ff

hi StorageClass guifg=#8aff9d
hi Structure guifg=#8aff9d
hi Typedef guifg=#8aff9d

hi SpecialChar guifg=#8affd8
hi Tag guifg=#8affd8
hi Delimiter guifg=#95a99b
hi SpecialComment guifg=#4a5d4a
hi Debug guifg=#fff59d

hi Ignore guifg=#0b0f0b

" Cursor and line highlighting
hi Cursor guifg=#0b0f0b guibg=#f4d35e
hi CursorLine guibg=#2a3a2a
hi CursorColumn guibg=#2a3a2a

" Visual selection
hi Visual guibg=#2a3a2a

" Search highlighting
hi Search guibg=#fff59d guifg=#0b0f0b
hi IncSearch guibg=#fff59d guifg=#0b0f0b

" Line numbers
hi LineNr guifg=#4a5d4a
hi CursorLineNr guifg=#d0d8c8

" Status line
hi StatusLine guifg=#d0d8c8 guibg=#4a5d4a
hi StatusLineNC guifg=#4a5d4a guibg=#0b0f0b

" Tab line
hi TabLine guifg=#4a5d4a guibg=#0b0f0b
hi TabLineSel guifg=#d0d8c8 guibg=#2a3a2a
hi TabLineFill guibg=#0b0f0b

" Popup menu
hi Pmenu guifg=#d0d8c8 guibg=#4a5d4a
hi PmenuSel guifg=#0b0f0b guibg=#2a3a2a
hi PmenuSbar guibg=#4a5d4a
hi PmenuThumb guibg=#d0d8c8

" Diff highlighting
hi DiffAdd guibg=#50fa7b
hi DiffChange guibg=#f1fa8c
hi DiffDelete guibg=#ff5f56
hi DiffText guibg=#8be9fd

" Fold highlighting
hi Folded guifg=#4a5d4a guibg=#0b0f0b
hi FoldColumn guifg=#4a5d4a guibg=#0b0f0b

" Spell checking
hi SpellBad gui=undercurl guisp=#ff5f56
hi SpellCap gui=undercurl guisp=#8be9fd
hi SpellRare gui=undercurl guisp=#bd93f9
hi SpellLocal gui=undercurl guisp=#5af78e

" Error and warning messages
hi ErrorMsg guifg=#ff5f56
hi WarningMsg guifg=#f1fa8c
hi MoreMsg guifg=#8be9fd
hi Question guifg=#50fa7b

" Mode message
hi ModeMsg guifg=#50fa7b

" Directory
hi Directory guifg=#8be9fd

" Title
hi Title guifg=#bd93f9

" Match parenthesis
hi MatchParen guibg=#4a5d4a

" Sign column
hi SignColumn guifg=#4a5d4a guibg=#0b0f0b
