" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Cursor Light
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Cursor-Light"

" Normal colors
hi Normal guifg=#252525 guibg=#f3f3f3

" Syntax highlighting groups
hi Comment guifg=#5c5c5c
hi Constant guifg=#a16900
hi Identifier guifg=#3c7cab
hi Statement guifg=#e75e78
hi PreProc guifg=#d06ba6
hi Type guifg=#55a583
hi Special guifg=#6f9ba6
hi Underlined guifg=#6299c3 gui=underline
hi Error guifg=#cf2d56 guibg=#f3f3f3
hi Todo guifg=#c08532 guibg=#f3f3f3

" Additional groups for better compatibility
hi String guifg=#1f8a65
hi Character guifg=#1f8a65
hi Number guifg=#a16900
hi Boolean guifg=#a16900
hi Float guifg=#a16900

hi Function guifg=#3c7cab

hi Conditional guifg=#e75e78
hi Repeat guifg=#e75e78
hi Label guifg=#e75e78
hi Operator guifg=#afafaf
hi Keyword guifg=#e75e78
hi Exception guifg=#cf2d56

hi Include guifg=#d06ba6
hi Define guifg=#d06ba6
hi Macro guifg=#d06ba6
hi PreCondit guifg=#d06ba6

hi StorageClass guifg=#55a583
hi Structure guifg=#55a583
hi Typedef guifg=#55a583

hi SpecialChar guifg=#6f9ba6
hi Tag guifg=#6f9ba6
hi Delimiter guifg=#afafaf
hi SpecialComment guifg=#5c5c5c
hi Debug guifg=#c08532

hi Ignore guifg=#f3f3f3

" Cursor and line highlighting
hi Cursor guifg=#f3f3f3 guibg=#252525
hi CursorLine guibg=#d9d9d9
hi CursorColumn guibg=#d9d9d9

" Visual selection
hi Visual guibg=#d9d9d9

" Search highlighting
hi Search guibg=#c08532 guifg=#f3f3f3
hi IncSearch guibg=#c08532 guifg=#f3f3f3

" Line numbers
hi LineNr guifg=#5c5c5c
hi CursorLineNr guifg=#252525

" Status line
hi StatusLine guifg=#252525 guibg=#5c5c5c
hi StatusLineNC guifg=#5c5c5c guibg=#f3f3f3

" Tab line
hi TabLine guifg=#5c5c5c guibg=#f3f3f3
hi TabLineSel guifg=#252525 guibg=#d9d9d9
hi TabLineFill guibg=#f3f3f3

" Popup menu
hi Pmenu guifg=#252525 guibg=#5c5c5c
hi PmenuSel guifg=#f3f3f3 guibg=#d9d9d9
hi PmenuSbar guibg=#5c5c5c
hi PmenuThumb guibg=#252525

" Diff highlighting
hi DiffAdd guibg=#1f8a65
hi DiffChange guibg=#a16900
hi DiffDelete guibg=#cf2d56
hi DiffText guibg=#3c7cab

" Fold highlighting
hi Folded guifg=#5c5c5c guibg=#f3f3f3
hi FoldColumn guifg=#5c5c5c guibg=#f3f3f3

" Spell checking
hi SpellBad gui=undercurl guisp=#cf2d56
hi SpellCap gui=undercurl guisp=#3c7cab
hi SpellRare gui=undercurl guisp=#b8448b
hi SpellLocal gui=undercurl guisp=#4c7f8c

" Error and warning messages
hi ErrorMsg guifg=#cf2d56
hi WarningMsg guifg=#a16900
hi MoreMsg guifg=#3c7cab
hi Question guifg=#1f8a65

" Mode message
hi ModeMsg guifg=#1f8a65

" Directory
hi Directory guifg=#3c7cab

" Title
hi Title guifg=#b8448b

" Match parenthesis
hi MatchParen guibg=#5c5c5c

" Sign column
hi SignColumn guifg=#5c5c5c guibg=#f3f3f3
