" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Cursor Dark
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Cursor-Dark"

" Normal colors
hi Normal guifg=#ffffff guibg=#141414

" Syntax highlighting groups
hi Comment guifg=#505050
hi Constant guifg=#ebcb8b
hi Identifier guifg=#81a1c1
hi Statement guifg=#bf616a
hi PreProc guifg=#b48ead
hi Type guifg=#a3be8c
hi Special guifg=#88c0d0
hi Underlined guifg=#81a1c1 gui=underline
hi Error guifg=#bf616a guibg=#141414
hi Todo guifg=#ebcb8b guibg=#141414

" Additional groups for better compatibility
hi String guifg=#a3be8c
hi Character guifg=#a3be8c
hi Number guifg=#ebcb8b
hi Boolean guifg=#ebcb8b
hi Float guifg=#ebcb8b

hi Function guifg=#81a1c1

hi Conditional guifg=#bf616a
hi Repeat guifg=#bf616a
hi Label guifg=#bf616a
hi Operator guifg=#d8dee9
hi Keyword guifg=#bf616a
hi Exception guifg=#bf616a

hi Include guifg=#b48ead
hi Define guifg=#b48ead
hi Macro guifg=#b48ead
hi PreCondit guifg=#b48ead

hi StorageClass guifg=#a3be8c
hi Structure guifg=#a3be8c
hi Typedef guifg=#a3be8c

hi SpecialChar guifg=#88c0d0
hi Tag guifg=#88c0d0
hi Delimiter guifg=#d8dee9
hi SpecialComment guifg=#505050
hi Debug guifg=#ebcb8b

hi Ignore guifg=#141414

" Cursor and line highlighting
hi Cursor guifg=#141414 guibg=#ffffff
hi CursorLine guibg=#303030
hi CursorColumn guibg=#303030

" Visual selection
hi Visual guibg=#303030

" Search highlighting
hi Search guibg=#ebcb8b guifg=#141414
hi IncSearch guibg=#ebcb8b guifg=#141414

" Line numbers
hi LineNr guifg=#505050
hi CursorLineNr guifg=#ffffff

" Status line
hi StatusLine guifg=#ffffff guibg=#505050
hi StatusLineNC guifg=#505050 guibg=#141414

" Tab line
hi TabLine guifg=#505050 guibg=#141414
hi TabLineSel guifg=#ffffff guibg=#303030
hi TabLineFill guibg=#141414

" Popup menu
hi Pmenu guifg=#ffffff guibg=#505050
hi PmenuSel guifg=#141414 guibg=#303030
hi PmenuSbar guibg=#505050
hi PmenuThumb guibg=#ffffff

" Diff highlighting
hi DiffAdd guibg=#a3be8c
hi DiffChange guibg=#ebcb8b
hi DiffDelete guibg=#bf616a
hi DiffText guibg=#81a1c1

" Fold highlighting
hi Folded guifg=#505050 guibg=#141414
hi FoldColumn guifg=#505050 guibg=#141414

" Spell checking
hi SpellBad gui=undercurl guisp=#bf616a
hi SpellCap gui=undercurl guisp=#81a1c1
hi SpellRare gui=undercurl guisp=#b48ead
hi SpellLocal gui=undercurl guisp=#88c0d0

" Error and warning messages
hi ErrorMsg guifg=#bf616a
hi WarningMsg guifg=#ebcb8b
hi MoreMsg guifg=#81a1c1
hi Question guifg=#a3be8c

" Mode message
hi ModeMsg guifg=#a3be8c

" Directory
hi Directory guifg=#81a1c1

" Title
hi Title guifg=#b48ead

" Match parenthesis
hi MatchParen guibg=#505050

" Sign column
hi SignColumn guifg=#505050 guibg=#141414
