" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Deep Current
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Deep-Current"

" Normal colors
hi Normal guifg=#e2e8f0 guibg=#08121f

" Syntax highlighting groups
hi Comment guifg=#475569
hi Constant guifg=#f59e0b
hi Identifier guifg=#3b82f6
hi Statement guifg=#ff7b9c
hi PreProc guifg=#e879f9
hi Type guifg=#86efac
hi Special guifg=#2dd4bf
hi Underlined guifg=#60a5fa gui=underline
hi Error guifg=#ff4d6d guibg=#08121f
hi Todo guifg=#fcd34d guibg=#08121f

" Additional groups for better compatibility
hi String guifg=#22c55e
hi Character guifg=#22c55e
hi Number guifg=#f59e0b
hi Boolean guifg=#f59e0b
hi Float guifg=#f59e0b

hi Function guifg=#3b82f6

hi Conditional guifg=#ff7b9c
hi Repeat guifg=#ff7b9c
hi Label guifg=#ff7b9c
hi Operator guifg=#94a3b8
hi Keyword guifg=#ff7b9c
hi Exception guifg=#ff4d6d

hi Include guifg=#e879f9
hi Define guifg=#e879f9
hi Macro guifg=#e879f9
hi PreCondit guifg=#e879f9

hi StorageClass guifg=#86efac
hi Structure guifg=#86efac
hi Typedef guifg=#86efac

hi SpecialChar guifg=#2dd4bf
hi Tag guifg=#2dd4bf
hi Delimiter guifg=#94a3b8
hi SpecialComment guifg=#475569
hi Debug guifg=#fcd34d

hi Ignore guifg=#08121f

" Cursor and line highlighting
hi Cursor guifg=#08121f guibg=#00c5ff
hi CursorLine guibg=#334155
hi CursorColumn guibg=#334155

" Visual selection
hi Visual guibg=#334155

" Search highlighting
hi Search guibg=#fcd34d guifg=#08121f
hi IncSearch guibg=#fcd34d guifg=#08121f

" Line numbers
hi LineNr guifg=#475569
hi CursorLineNr guifg=#e2e8f0

" Status line
hi StatusLine guifg=#e2e8f0 guibg=#475569
hi StatusLineNC guifg=#475569 guibg=#08121f

" Tab line
hi TabLine guifg=#475569 guibg=#08121f
hi TabLineSel guifg=#e2e8f0 guibg=#334155
hi TabLineFill guibg=#08121f

" Popup menu
hi Pmenu guifg=#e2e8f0 guibg=#475569
hi PmenuSel guifg=#08121f guibg=#334155
hi PmenuSbar guibg=#475569
hi PmenuThumb guibg=#e2e8f0

" Diff highlighting
hi DiffAdd guibg=#22c55e
hi DiffChange guibg=#f59e0b
hi DiffDelete guibg=#ff4d6d
hi DiffText guibg=#3b82f6

" Fold highlighting
hi Folded guifg=#475569 guibg=#08121f
hi FoldColumn guifg=#475569 guibg=#08121f

" Spell checking
hi SpellBad gui=undercurl guisp=#ff4d6d
hi SpellCap gui=undercurl guisp=#3b82f6
hi SpellRare gui=undercurl guisp=#d946ef
hi SpellLocal gui=undercurl guisp=#06d6a0

" Error and warning messages
hi ErrorMsg guifg=#ff4d6d
hi WarningMsg guifg=#f59e0b
hi MoreMsg guifg=#3b82f6
hi Question guifg=#22c55e

" Mode message
hi ModeMsg guifg=#22c55e

" Directory
hi Directory guifg=#3b82f6

" Title
hi Title guifg=#d946ef

" Match parenthesis
hi MatchParen guibg=#475569

" Sign column
hi SignColumn guifg=#475569 guibg=#08121f
