" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Dracula+ High Contrast
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Dracula+-High-Contrast"

" Normal colors
hi Normal guifg=#f8f8f2 guibg=#14141a

" Syntax highlighting groups
hi Comment guifg=#9ba1b5
hi Constant guifg=#ffcb6b
hi Identifier guifg=#82aaff
hi Statement guifg=#ff8a8a
hi PreProc guifg=#ff92df
hi Type guifg=#69ff94
hi Special guifg=#a4ffff
hi Underlined guifg=#d6acff gui=underline
hi Error guifg=#ff7676 guibg=#14141a
hi Todo guifg=#ffd98a guibg=#14141a

" Additional groups for better compatibility
hi String guifg=#50fa7b
hi Character guifg=#50fa7b
hi Number guifg=#ffcb6b
hi Boolean guifg=#ffcb6b
hi Float guifg=#ffcb6b

hi Function guifg=#82aaff

hi Conditional guifg=#ff8a8a
hi Repeat guifg=#ff8a8a
hi Label guifg=#ff8a8a
hi Operator guifg=#f8f8f2
hi Keyword guifg=#ff8a8a
hi Exception guifg=#ff7676

hi Include guifg=#ff92df
hi Define guifg=#ff92df
hi Macro guifg=#ff92df
hi PreCondit guifg=#ff92df

hi StorageClass guifg=#69ff94
hi Structure guifg=#69ff94
hi Typedef guifg=#69ff94

hi SpecialChar guifg=#a4ffff
hi Tag guifg=#a4ffff
hi Delimiter guifg=#f8f8f2
hi SpecialComment guifg=#9ba1b5
hi Debug guifg=#ffd98a

hi Ignore guifg=#14141a

" Cursor and line highlighting
hi Cursor guifg=#14141a guibg=#eceff4
hi CursorLine guibg=#44475a
hi CursorColumn guibg=#44475a

" Visual selection
hi Visual guibg=#44475a

" Search highlighting
hi Search guibg=#ffd98a guifg=#14141a
hi IncSearch guibg=#ffd98a guifg=#14141a

" Line numbers
hi LineNr guifg=#9ba1b5
hi CursorLineNr guifg=#f8f8f2

" Status line
hi StatusLine guifg=#f8f8f2 guibg=#9ba1b5
hi StatusLineNC guifg=#9ba1b5 guibg=#14141a

" Tab line
hi TabLine guifg=#9ba1b5 guibg=#14141a
hi TabLineSel guifg=#f8f8f2 guibg=#44475a
hi TabLineFill guibg=#14141a

" Popup menu
hi Pmenu guifg=#f8f8f2 guibg=#9ba1b5
hi PmenuSel guifg=#14141a guibg=#44475a
hi PmenuSbar guibg=#9ba1b5
hi PmenuThumb guibg=#f8f8f2

" Diff highlighting
hi DiffAdd guibg=#50fa7b
hi DiffChange guibg=#ffcb6b
hi DiffDelete guibg=#ff7676
hi DiffText guibg=#82aaff

" Fold highlighting
hi Folded guifg=#9ba1b5 guibg=#14141a
hi FoldColumn guifg=#9ba1b5 guibg=#14141a

" Spell checking
hi SpellBad gui=undercurl guisp=#ff7676
hi SpellCap gui=undercurl guisp=#82aaff
hi SpellRare gui=undercurl guisp=#c792ea
hi SpellLocal gui=undercurl guisp=#8be9fd

" Error and warning messages
hi ErrorMsg guifg=#ff7676
hi WarningMsg guifg=#ffcb6b
hi MoreMsg guifg=#82aaff
hi Question guifg=#50fa7b

" Mode message
hi ModeMsg guifg=#50fa7b

" Directory
hi Directory guifg=#82aaff

" Title
hi Title guifg=#c792ea

" Match parenthesis
hi MatchParen guibg=#9ba1b5

" Sign column
hi SignColumn guifg=#9ba1b5 guibg=#14141a
