" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Earl Grey
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Earl-Grey"

" Normal colors
hi Normal guifg=#605a52 guibg=#fcfbf9

" Syntax highlighting groups
hi Comment guifg=#a8a094
hi Constant guifg=#897d43
hi Identifier guifg=#556995
hi Statement guifg=#82403c
hi PreProc guifg=#77406f
hi Type guifg=#656d37
hi Special guifg=#326b6c
hi Underlined guifg=#3e5588 gui=underline
hi Error guifg=#8f5652 guibg=#fcfbf9
hi Todo guifg=#796d2f guibg=#fcfbf9

" Additional groups for better compatibility
hi String guifg=#747b4d
hi Character guifg=#747b4d
hi Number guifg=#897d43
hi Boolean guifg=#897d43
hi Float guifg=#897d43

hi Function guifg=#556995

hi Conditional guifg=#82403c
hi Repeat guifg=#82403c
hi Label guifg=#82403c
hi Operator guifg=#c2beb8
hi Keyword guifg=#82403c
hi Exception guifg=#8f5652

hi Include guifg=#77406f
hi Define guifg=#77406f
hi Macro guifg=#77406f
hi PreCondit guifg=#77406f

hi StorageClass guifg=#656d37
hi Structure guifg=#656d37
hi Typedef guifg=#656d37

hi SpecialChar guifg=#326b6c
hi Tag guifg=#326b6c
hi Delimiter guifg=#c2beb8
hi SpecialComment guifg=#a8a094
hi Debug guifg=#796d2f

hi Ignore guifg=#fcfbf9

" Cursor and line highlighting
hi Cursor guifg=#fcfbf9 guibg=#605a52
hi CursorLine guibg=#e1ddd6
hi CursorColumn guibg=#e1ddd6

" Visual selection
hi Visual guibg=#e1ddd6

" Search highlighting
hi Search guibg=#796d2f guifg=#fcfbf9
hi IncSearch guibg=#796d2f guifg=#fcfbf9

" Line numbers
hi LineNr guifg=#a8a094
hi CursorLineNr guifg=#605a52

" Status line
hi StatusLine guifg=#605a52 guibg=#a8a094
hi StatusLineNC guifg=#a8a094 guibg=#fcfbf9

" Tab line
hi TabLine guifg=#a8a094 guibg=#fcfbf9
hi TabLineSel guifg=#605a52 guibg=#e1ddd6
hi TabLineFill guibg=#fcfbf9

" Popup menu
hi Pmenu guifg=#605a52 guibg=#a8a094
hi PmenuSel guifg=#fcfbf9 guibg=#e1ddd6
hi PmenuSbar guibg=#a8a094
hi PmenuThumb guibg=#605a52

" Diff highlighting
hi DiffAdd guibg=#747b4d
hi DiffChange guibg=#897d43
hi DiffDelete guibg=#8f5652
hi DiffText guibg=#556995

" Fold highlighting
hi Folded guifg=#a8a094 guibg=#fcfbf9
hi FoldColumn guifg=#a8a094 guibg=#fcfbf9

" Spell checking
hi SpellBad gui=undercurl guisp=#8f5652
hi SpellCap gui=undercurl guisp=#556995
hi SpellRare gui=undercurl guisp=#83577d
hi SpellLocal gui=undercurl guisp=#477a7b

" Error and warning messages
hi ErrorMsg guifg=#8f5652
hi WarningMsg guifg=#897d43
hi MoreMsg guifg=#556995
hi Question guifg=#747b4d

" Mode message
hi ModeMsg guifg=#747b4d

" Directory
hi Directory guifg=#556995

" Title
hi Title guifg=#83577d

" Match parenthesis
hi MatchParen guibg=#a8a094

" Sign column
hi SignColumn guifg=#a8a094 guibg=#fcfbf9
