" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Ember Peak
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Ember-Peak"

" Normal colors
hi Normal guifg=#f8fafc guibg=#0a0a0f

" Syntax highlighting groups
hi Comment guifg=#cbc8c3
hi Constant guifg=#ffd166
hi Identifier guifg=#86b5ff
hi Statement guifg=#ff9b8f
hi PreProc guifg=#ecb2ff
hi Type guifg=#84e0a8
hi Special guifg=#c5eef4
hi Underlined guifg=#a8c9ff gui=underline
hi Error guifg=#ff806f guibg=#0a0a0f
hi Todo guifg=#ffe18a guibg=#0a0a0f

" Additional groups for better compatibility
hi String guifg=#65d493
hi Character guifg=#65d493
hi Number guifg=#ffd166
hi Boolean guifg=#ffd166
hi Float guifg=#ffd166

hi Function guifg=#86b5ff

hi Conditional guifg=#ff9b8f
hi Repeat guifg=#ff9b8f
hi Label guifg=#ff9b8f
hi Operator guifg=#f8fafc
hi Keyword guifg=#ff9b8f
hi Exception guifg=#ff806f

hi Include guifg=#ecb2ff
hi Define guifg=#ecb2ff
hi Macro guifg=#ecb2ff
hi PreCondit guifg=#ecb2ff

hi StorageClass guifg=#84e0a8
hi Structure guifg=#84e0a8
hi Typedef guifg=#84e0a8

hi SpecialChar guifg=#c5eef4
hi Tag guifg=#c5eef4
hi Delimiter guifg=#f8fafc
hi SpecialComment guifg=#cbc8c3
hi Debug guifg=#ffe18a

hi Ignore guifg=#0a0a0f

" Cursor and line highlighting
hi Cursor guifg=#1a0f08 guibg=#ffb86b
hi CursorLine guibg=#2b1f16
hi CursorColumn guibg=#2b1f16

" Visual selection
hi Visual guibg=#2b1f16

" Search highlighting
hi Search guibg=#ffe18a guifg=#0a0a0f
hi IncSearch guibg=#ffe18a guifg=#0a0a0f

" Line numbers
hi LineNr guifg=#cbc8c3
hi CursorLineNr guifg=#f8fafc

" Status line
hi StatusLine guifg=#f8fafc guibg=#cbc8c3
hi StatusLineNC guifg=#cbc8c3 guibg=#0a0a0f

" Tab line
hi TabLine guifg=#cbc8c3 guibg=#0a0a0f
hi TabLineSel guifg=#f8fafc guibg=#2b1f16
hi TabLineFill guibg=#0a0a0f

" Popup menu
hi Pmenu guifg=#f8fafc guibg=#cbc8c3
hi PmenuSel guifg=#0a0a0f guibg=#2b1f16
hi PmenuSbar guibg=#cbc8c3
hi PmenuThumb guibg=#f8fafc

" Diff highlighting
hi DiffAdd guibg=#65d493
hi DiffChange guibg=#ffd166
hi DiffDelete guibg=#ff806f
hi DiffText guibg=#86b5ff

" Fold highlighting
hi Folded guifg=#cbc8c3 guibg=#0a0a0f
hi FoldColumn guifg=#cbc8c3 guibg=#0a0a0f

" Spell checking
hi SpellBad gui=undercurl guisp=#ff806f
hi SpellCap gui=undercurl guisp=#86b5ff
hi SpellRare gui=undercurl guisp=#e29aff
hi SpellLocal gui=undercurl guisp=#b8e7ef

" Error and warning messages
hi ErrorMsg guifg=#ff806f
hi WarningMsg guifg=#ffd166
hi MoreMsg guifg=#86b5ff
hi Question guifg=#65d493

" Mode message
hi ModeMsg guifg=#65d493

" Directory
hi Directory guifg=#86b5ff

" Title
hi Title guifg=#e29aff

" Match parenthesis
hi MatchParen guibg=#cbc8c3

" Sign column
hi SignColumn guifg=#cbc8c3 guibg=#0a0a0f
