" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Emberglass
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Emberglass"

" Normal colors
hi Normal guifg=#e6e7eb guibg=#0b0e11

" Syntax highlighting groups
hi Comment guifg=#64748b
hi Constant guifg=#eab308
hi Identifier guifg=#38bdf8
hi Statement guifg=#fb923c
hi PreProc guifg=#c084fc
hi Type guifg=#86efac
hi Special guifg=#67e8f9
hi Underlined guifg=#7dd3fc gui=underline
hi Error guifg=#f97316 guibg=#0b0e11
hi Todo guifg=#facc15 guibg=#0b0e11

" Additional groups for better compatibility
hi String guifg=#22c55e
hi Character guifg=#22c55e
hi Number guifg=#eab308
hi Boolean guifg=#eab308
hi Float guifg=#eab308

hi Function guifg=#38bdf8

hi Conditional guifg=#fb923c
hi Repeat guifg=#fb923c
hi Label guifg=#fb923c
hi Operator guifg=#cbd5e1
hi Keyword guifg=#fb923c
hi Exception guifg=#f97316

hi Include guifg=#c084fc
hi Define guifg=#c084fc
hi Macro guifg=#c084fc
hi PreCondit guifg=#c084fc

hi StorageClass guifg=#86efac
hi Structure guifg=#86efac
hi Typedef guifg=#86efac

hi SpecialChar guifg=#67e8f9
hi Tag guifg=#67e8f9
hi Delimiter guifg=#cbd5e1
hi SpecialComment guifg=#64748b
hi Debug guifg=#facc15

hi Ignore guifg=#0b0e11

" Cursor and line highlighting
hi Cursor guifg=#0b0e11 guibg=#f59e0b
hi CursorLine guibg=#4b5563
hi CursorColumn guibg=#4b5563

" Visual selection
hi Visual guibg=#4b5563

" Search highlighting
hi Search guibg=#facc15 guifg=#0b0e11
hi IncSearch guibg=#facc15 guifg=#0b0e11

" Line numbers
hi LineNr guifg=#64748b
hi CursorLineNr guifg=#e6e7eb

" Status line
hi StatusLine guifg=#e6e7eb guibg=#64748b
hi StatusLineNC guifg=#64748b guibg=#0b0e11

" Tab line
hi TabLine guifg=#64748b guibg=#0b0e11
hi TabLineSel guifg=#e6e7eb guibg=#4b5563
hi TabLineFill guibg=#0b0e11

" Popup menu
hi Pmenu guifg=#e6e7eb guibg=#64748b
hi PmenuSel guifg=#0b0e11 guibg=#4b5563
hi PmenuSbar guibg=#64748b
hi PmenuThumb guibg=#e6e7eb

" Diff highlighting
hi DiffAdd guibg=#22c55e
hi DiffChange guibg=#eab308
hi DiffDelete guibg=#f97316
hi DiffText guibg=#38bdf8

" Fold highlighting
hi Folded guifg=#64748b guibg=#0b0e11
hi FoldColumn guifg=#64748b guibg=#0b0e11

" Spell checking
hi SpellBad gui=undercurl guisp=#f97316
hi SpellCap gui=undercurl guisp=#38bdf8
hi SpellRare gui=undercurl guisp=#a855f7
hi SpellLocal gui=undercurl guisp=#14b8a6

" Error and warning messages
hi ErrorMsg guifg=#f97316
hi WarningMsg guifg=#eab308
hi MoreMsg guifg=#38bdf8
hi Question guifg=#22c55e

" Mode message
hi ModeMsg guifg=#22c55e

" Directory
hi Directory guifg=#38bdf8

" Title
hi Title guifg=#a855f7

" Match parenthesis
hi MatchParen guibg=#64748b

" Sign column
hi SignColumn guifg=#64748b guibg=#0b0e11
