" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Green Screen
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Green-Screen"

" Normal colors
hi Normal guifg=#dff7e8 guibg=#031009

" Syntax highlighting groups
hi Comment guifg=#c0cec5
hi Constant guifg=#e5cc69
hi Identifier guifg=#82b3e7
hi Statement guifg=#f09ba1
hi PreProc guifg=#d9bae8
hi Type guifg=#90dfb4
hi Special guifg=#92e1dc
hi Underlined guifg=#a1c8ef gui=underline
hi Error guifg=#ed8087 guibg=#031009
hi Todo guifg=#ecdc8b guibg=#031009

" Additional groups for better compatibility
hi String guifg=#70d19c
hi Character guifg=#70d19c
hi Number guifg=#e5cc69
hi Boolean guifg=#e5cc69
hi Float guifg=#e5cc69

hi Function guifg=#82b3e7

hi Conditional guifg=#f09ba1
hi Repeat guifg=#f09ba1
hi Label guifg=#f09ba1
hi Operator guifg=#dff7e8
hi Keyword guifg=#f09ba1
hi Exception guifg=#ed8087

hi Include guifg=#d9bae8
hi Define guifg=#d9bae8
hi Macro guifg=#d9bae8
hi PreCondit guifg=#d9bae8

hi StorageClass guifg=#90dfb4
hi Structure guifg=#90dfb4
hi Typedef guifg=#90dfb4

hi SpecialChar guifg=#92e1dc
hi Tag guifg=#92e1dc
hi Delimiter guifg=#dff7e8
hi SpecialComment guifg=#c0cec5
hi Debug guifg=#ecdc8b

hi Ignore guifg=#031009

" Cursor and line highlighting
hi Cursor guifg=#031009 guibg=#8af0b4
hi CursorLine guibg=#12351f
hi CursorColumn guibg=#12351f

" Visual selection
hi Visual guibg=#12351f

" Search highlighting
hi Search guibg=#ecdc8b guifg=#031009
hi IncSearch guibg=#ecdc8b guifg=#031009

" Line numbers
hi LineNr guifg=#c0cec5
hi CursorLineNr guifg=#dff7e8

" Status line
hi StatusLine guifg=#dff7e8 guibg=#c0cec5
hi StatusLineNC guifg=#c0cec5 guibg=#031009

" Tab line
hi TabLine guifg=#c0cec5 guibg=#031009
hi TabLineSel guifg=#dff7e8 guibg=#12351f
hi TabLineFill guibg=#031009

" Popup menu
hi Pmenu guifg=#dff7e8 guibg=#c0cec5
hi PmenuSel guifg=#031009 guibg=#12351f
hi PmenuSbar guibg=#c0cec5
hi PmenuThumb guibg=#dff7e8

" Diff highlighting
hi DiffAdd guibg=#70d19c
hi DiffChange guibg=#e5cc69
hi DiffDelete guibg=#ed8087
hi DiffText guibg=#82b3e7

" Fold highlighting
hi Folded guifg=#c0cec5 guibg=#031009
hi FoldColumn guifg=#c0cec5 guibg=#031009

" Spell checking
hi SpellBad gui=undercurl guisp=#ed8087
hi SpellCap gui=undercurl guisp=#82b3e7
hi SpellRare gui=undercurl guisp=#c99fdf
hi SpellLocal gui=undercurl guisp=#70d2ce

" Error and warning messages
hi ErrorMsg guifg=#ed8087
hi WarningMsg guifg=#e5cc69
hi MoreMsg guifg=#82b3e7
hi Question guifg=#70d19c

" Mode message
hi ModeMsg guifg=#70d19c

" Directory
hi Directory guifg=#82b3e7

" Title
hi Title guifg=#c99fdf

" Match parenthesis
hi MatchParen guibg=#c0cec5

" Sign column
hi SignColumn guifg=#c0cec5 guibg=#031009
