" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Harvest Moon
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Harvest-Moon"

" Normal colors
hi Normal guifg=#fff1d2 guibg=#0d3557

" Syntax highlighting groups
hi Comment guifg=#cbd3d6
hi Constant guifg=#edc667
hi Identifier guifg=#8fc1dd
hi Statement guifg=#f2ae92
hi PreProc guifg=#d4b8d5
hi Type guifg=#b0d6a4
hi Special guifg=#9edbdc
hi Underlined guifg=#aad1e7 gui=underline
hi Error guifg=#ee997d guibg=#0d3557
hi Todo guifg=#f4d585 guibg=#0d3557

" Additional groups for better compatibility
hi String guifg=#9bca8e
hi Character guifg=#9bca8e
hi Number guifg=#edc667
hi Boolean guifg=#edc667
hi Float guifg=#edc667

hi Function guifg=#8fc1dd

hi Conditional guifg=#f2ae92
hi Repeat guifg=#f2ae92
hi Label guifg=#f2ae92
hi Operator guifg=#fff1d2
hi Keyword guifg=#f2ae92
hi Exception guifg=#ee997d

hi Include guifg=#d4b8d5
hi Define guifg=#d4b8d5
hi Macro guifg=#d4b8d5
hi PreCondit guifg=#d4b8d5

hi StorageClass guifg=#b0d6a4
hi Structure guifg=#b0d6a4
hi Typedef guifg=#b0d6a4

hi SpecialChar guifg=#9edbdc
hi Tag guifg=#9edbdc
hi Delimiter guifg=#fff1d2
hi SpecialComment guifg=#cbd3d6
hi Debug guifg=#f4d585

hi Ignore guifg=#0d3557

" Cursor and line highlighting
hi Cursor guifg=#0d3557 guibg=#f3b64a
hi CursorLine guibg=#2a5371
hi CursorColumn guibg=#2a5371

" Visual selection
hi Visual guibg=#2a5371

" Search highlighting
hi Search guibg=#f4d585 guifg=#0d3557
hi IncSearch guibg=#f4d585 guifg=#0d3557

" Line numbers
hi LineNr guifg=#cbd3d6
hi CursorLineNr guifg=#fff1d2

" Status line
hi StatusLine guifg=#fff1d2 guibg=#cbd3d6
hi StatusLineNC guifg=#cbd3d6 guibg=#0d3557

" Tab line
hi TabLine guifg=#cbd3d6 guibg=#0d3557
hi TabLineSel guifg=#fff1d2 guibg=#2a5371
hi TabLineFill guibg=#0d3557

" Popup menu
hi Pmenu guifg=#fff1d2 guibg=#cbd3d6
hi PmenuSel guifg=#0d3557 guibg=#2a5371
hi PmenuSbar guibg=#cbd3d6
hi PmenuThumb guibg=#fff1d2

" Diff highlighting
hi DiffAdd guibg=#9bca8e
hi DiffChange guibg=#edc667
hi DiffDelete guibg=#ee997d
hi DiffText guibg=#8fc1dd

" Fold highlighting
hi Folded guifg=#cbd3d6 guibg=#0d3557
hi FoldColumn guifg=#cbd3d6 guibg=#0d3557

" Spell checking
hi SpellBad gui=undercurl guisp=#ee997d
hi SpellCap gui=undercurl guisp=#8fc1dd
hi SpellRare gui=undercurl guisp=#c7a1c8
hi SpellLocal gui=undercurl guisp=#80ced0

" Error and warning messages
hi ErrorMsg guifg=#ee997d
hi WarningMsg guifg=#edc667
hi MoreMsg guifg=#8fc1dd
hi Question guifg=#9bca8e

" Mode message
hi ModeMsg guifg=#9bca8e

" Directory
hi Directory guifg=#8fc1dd

" Title
hi Title guifg=#c7a1c8

" Match parenthesis
hi MatchParen guibg=#cbd3d6

" Sign column
hi SignColumn guifg=#cbd3d6 guibg=#0d3557
