" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Haunted House
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Haunted-House"

" Normal colors
hi Normal guifg=#f1f4ed guibg=#23394e

" Syntax highlighting groups
hi Comment guifg=#ccd3d8
hi Constant guifg=#e5cb7c
hi Identifier guifg=#9fc7e5
hi Statement guifg=#f1afa3
hi PreProc guifg=#d0c2e0
hi Type guifg=#b3d8ba
hi Special guifg=#addddd
hi Underlined guifg=#b8d6ec gui=underline
hi Error guifg=#ed9b8c guibg=#23394e
hi Todo guifg=#edda99 guibg=#23394e

" Additional groups for better compatibility
hi String guifg=#9fcba7
hi Character guifg=#9fcba7
hi Number guifg=#e5cb7c
hi Boolean guifg=#e5cb7c
hi Float guifg=#e5cb7c

hi Function guifg=#9fc7e5

hi Conditional guifg=#f1afa3
hi Repeat guifg=#f1afa3
hi Label guifg=#f1afa3
hi Operator guifg=#f1f4ed
hi Keyword guifg=#f1afa3
hi Exception guifg=#ed9b8c

hi Include guifg=#d0c2e0
hi Define guifg=#d0c2e0
hi Macro guifg=#d0c2e0
hi PreCondit guifg=#d0c2e0

hi StorageClass guifg=#b3d8ba
hi Structure guifg=#b3d8ba
hi Typedef guifg=#b3d8ba

hi SpecialChar guifg=#addddd
hi Tag guifg=#addddd
hi Delimiter guifg=#f1f4ed
hi SpecialComment guifg=#ccd3d8
hi Debug guifg=#edda99

hi Ignore guifg=#23394e

" Cursor and line highlighting
hi Cursor guifg=#23394e guibg=#d5e2ee
hi CursorLine guibg=#40566a
hi CursorColumn guibg=#40566a

" Visual selection
hi Visual guibg=#40566a

" Search highlighting
hi Search guibg=#edda99 guifg=#23394e
hi IncSearch guibg=#edda99 guifg=#23394e

" Line numbers
hi LineNr guifg=#ccd3d8
hi CursorLineNr guifg=#f1f4ed

" Status line
hi StatusLine guifg=#f1f4ed guibg=#ccd3d8
hi StatusLineNC guifg=#ccd3d8 guibg=#23394e

" Tab line
hi TabLine guifg=#ccd3d8 guibg=#23394e
hi TabLineSel guifg=#f1f4ed guibg=#40566a
hi TabLineFill guibg=#23394e

" Popup menu
hi Pmenu guifg=#f1f4ed guibg=#ccd3d8
hi PmenuSel guifg=#23394e guibg=#40566a
hi PmenuSbar guibg=#ccd3d8
hi PmenuThumb guibg=#f1f4ed

" Diff highlighting
hi DiffAdd guibg=#9fcba7
hi DiffChange guibg=#e5cb7c
hi DiffDelete guibg=#ed9b8c
hi DiffText guibg=#9fc7e5

" Fold highlighting
hi Folded guifg=#ccd3d8 guibg=#23394e
hi FoldColumn guifg=#ccd3d8 guibg=#23394e

" Spell checking
hi SpellBad gui=undercurl guisp=#ed9b8c
hi SpellCap gui=undercurl guisp=#9fc7e5
hi SpellRare gui=undercurl guisp=#c2add8
hi SpellLocal gui=undercurl guisp=#93d0d0

" Error and warning messages
hi ErrorMsg guifg=#ed9b8c
hi WarningMsg guifg=#e5cb7c
hi MoreMsg guifg=#9fc7e5
hi Question guifg=#9fcba7

" Mode message
hi ModeMsg guifg=#9fcba7

" Directory
hi Directory guifg=#9fc7e5

" Title
hi Title guifg=#c2add8

" Match parenthesis
hi MatchParen guibg=#ccd3d8

" Sign column
hi SignColumn guifg=#ccd3d8 guibg=#23394e
