" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Kwyjibo
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Kwyjibo"

" Normal colors
hi Normal guifg=#f5f1e8 guibg=#07173b

" Syntax highlighting groups
hi Comment guifg=#b9c3d9
hi Constant guifg=#ffd529
hi Identifier guifg=#70afff
hi Statement guifg=#ff8a91
hi PreProc guifg=#efb3ec
hi Type guifg=#8ae0aa
hi Special guifg=#8ce7ef
hi Underlined guifg=#98c6ff gui=underline
hi Error guifg=#ff6973 guibg=#07173b
hi Todo guifg=#ffe269 guibg=#07173b

" Additional groups for better compatibility
hi String guifg=#67d391
hi Character guifg=#67d391
hi Number guifg=#ffd529
hi Boolean guifg=#ffd529
hi Float guifg=#ffd529

hi Function guifg=#70afff

hi Conditional guifg=#ff8a91
hi Repeat guifg=#ff8a91
hi Label guifg=#ff8a91
hi Operator guifg=#f5f1e8
hi Keyword guifg=#ff8a91
hi Exception guifg=#ff6973

hi Include guifg=#efb3ec
hi Define guifg=#efb3ec
hi Macro guifg=#efb3ec
hi PreCondit guifg=#efb3ec

hi StorageClass guifg=#8ae0aa
hi Structure guifg=#8ae0aa
hi Typedef guifg=#8ae0aa

hi SpecialChar guifg=#8ce7ef
hi Tag guifg=#8ce7ef
hi Delimiter guifg=#f5f1e8
hi SpecialComment guifg=#b9c3d9
hi Debug guifg=#ffe269

hi Ignore guifg=#07173b

" Cursor and line highlighting
hi Cursor guifg=#07173b guibg=#ffd529
hi CursorLine guibg=#236aa1
hi CursorColumn guibg=#236aa1

" Visual selection
hi Visual guibg=#236aa1

" Search highlighting
hi Search guibg=#ffe269 guifg=#07173b
hi IncSearch guibg=#ffe269 guifg=#07173b

" Line numbers
hi LineNr guifg=#b9c3d9
hi CursorLineNr guifg=#f5f1e8

" Status line
hi StatusLine guifg=#f5f1e8 guibg=#b9c3d9
hi StatusLineNC guifg=#b9c3d9 guibg=#07173b

" Tab line
hi TabLine guifg=#b9c3d9 guibg=#07173b
hi TabLineSel guifg=#f5f1e8 guibg=#236aa1
hi TabLineFill guibg=#07173b

" Popup menu
hi Pmenu guifg=#f5f1e8 guibg=#b9c3d9
hi PmenuSel guifg=#07173b guibg=#236aa1
hi PmenuSbar guibg=#b9c3d9
hi PmenuThumb guibg=#f5f1e8

" Diff highlighting
hi DiffAdd guibg=#67d391
hi DiffChange guibg=#ffd529
hi DiffDelete guibg=#ff6973
hi DiffText guibg=#70afff

" Fold highlighting
hi Folded guifg=#b9c3d9 guibg=#07173b
hi FoldColumn guifg=#b9c3d9 guibg=#07173b

" Spell checking
hi SpellBad gui=undercurl guisp=#ff6973
hi SpellCap gui=undercurl guisp=#70afff
hi SpellRare gui=undercurl guisp=#e893e4
hi SpellLocal gui=undercurl guisp=#66dce8

" Error and warning messages
hi ErrorMsg guifg=#ff6973
hi WarningMsg guifg=#ffd529
hi MoreMsg guifg=#70afff
hi Question guifg=#67d391

" Mode message
hi ModeMsg guifg=#67d391

" Directory
hi Directory guifg=#70afff

" Title
hi Title guifg=#e893e4

" Match parenthesis
hi MatchParen guibg=#b9c3d9

" Sign column
hi SignColumn guifg=#b9c3d9 guibg=#07173b
