" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Maple Jute
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Maple-Jute"

" Normal colors
hi Normal guifg=#fbe9d3 guibg=#56351f

" Syntax highlighting groups
hi Comment guifg=#e2cbb7
hi Constant guifg=#f2c87c
hi Identifier guifg=#a8c9ec
hi Statement guifg=#ffbd9e
hi PreProc guifg=#ecc9ec
hi Type guifg=#cfe6b2
hi Special guifg=#b9e9e0
hi Underlined guifg=#c2dafa gui=underline
hi Error guifg=#f5a18d guibg=#56351f
hi Todo guifg=#ffdf9c guibg=#56351f

" Additional groups for better compatibility
hi String guifg=#b9d8a1
hi Character guifg=#b9d8a1
hi Number guifg=#f2c87c
hi Boolean guifg=#f2c87c
hi Float guifg=#f2c87c

hi Function guifg=#a8c9ec

hi Conditional guifg=#ffbd9e
hi Repeat guifg=#ffbd9e
hi Label guifg=#ffbd9e
hi Operator guifg=#fbe9d3
hi Keyword guifg=#ffbd9e
hi Exception guifg=#f5a18d

hi Include guifg=#ecc9ec
hi Define guifg=#ecc9ec
hi Macro guifg=#ecc9ec
hi PreCondit guifg=#ecc9ec

hi StorageClass guifg=#cfe6b2
hi Structure guifg=#cfe6b2
hi Typedef guifg=#cfe6b2

hi SpecialChar guifg=#b9e9e0
hi Tag guifg=#b9e9e0
hi Delimiter guifg=#fbe9d3
hi SpecialComment guifg=#e2cbb7
hi Debug guifg=#ffdf9c

hi Ignore guifg=#56351f

" Cursor and line highlighting
hi Cursor guifg=#56351f guibg=#ffdf9c
hi CursorLine guibg=#8e684a
hi CursorColumn guibg=#8e684a

" Visual selection
hi Visual guibg=#8e684a

" Search highlighting
hi Search guibg=#ffdf9c guifg=#56351f
hi IncSearch guibg=#ffdf9c guifg=#56351f

" Line numbers
hi LineNr guifg=#e2cbb7
hi CursorLineNr guifg=#fbe9d3

" Status line
hi StatusLine guifg=#fbe9d3 guibg=#e2cbb7
hi StatusLineNC guifg=#e2cbb7 guibg=#56351f

" Tab line
hi TabLine guifg=#e2cbb7 guibg=#56351f
hi TabLineSel guifg=#fbe9d3 guibg=#8e684a
hi TabLineFill guibg=#56351f

" Popup menu
hi Pmenu guifg=#fbe9d3 guibg=#e2cbb7
hi PmenuSel guifg=#56351f guibg=#8e684a
hi PmenuSbar guibg=#e2cbb7
hi PmenuThumb guibg=#fbe9d3

" Diff highlighting
hi DiffAdd guibg=#b9d8a1
hi DiffChange guibg=#f2c87c
hi DiffDelete guibg=#f5a18d
hi DiffText guibg=#a8c9ec

" Fold highlighting
hi Folded guifg=#e2cbb7 guibg=#56351f
hi FoldColumn guifg=#e2cbb7 guibg=#56351f

" Spell checking
hi SpellBad gui=undercurl guisp=#f5a18d
hi SpellCap gui=undercurl guisp=#a8c9ec
hi SpellRare gui=undercurl guisp=#dbb0dd
hi SpellLocal gui=undercurl guisp=#9ed9d2

" Error and warning messages
hi ErrorMsg guifg=#f5a18d
hi WarningMsg guifg=#f2c87c
hi MoreMsg guifg=#a8c9ec
hi Question guifg=#b9d8a1

" Mode message
hi ModeMsg guifg=#b9d8a1

" Directory
hi Directory guifg=#a8c9ec

" Title
hi Title guifg=#dbb0dd

" Match parenthesis
hi MatchParen guibg=#e2cbb7

" Sign column
hi SignColumn guifg=#e2cbb7 guibg=#56351f
