" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Mesa Blue
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Mesa-Blue"

" Normal colors
hi Normal guifg=#fff0d7 guibg=#164c72

" Syntax highlighting groups
hi Comment guifg=#e1e5e2
hi Constant guifg=#f6d67a
hi Identifier guifg=#b7d9f4
hi Statement guifg=#ffc0a8
hi PreProc guifg=#f3c7e0
hi Type guifg=#b9e9c2
hi Special guifg=#c2efea
hi Underlined guifg=#cee6f8 gui=underline
hi Error guifg=#ffad91 guibg=#164c72
hi Todo guifg=#ffe596 guibg=#164c72

" Additional groups for better compatibility
hi String guifg=#9fdfad
hi Character guifg=#9fdfad
hi Number guifg=#f6d67a
hi Boolean guifg=#f6d67a
hi Float guifg=#f6d67a

hi Function guifg=#b7d9f4

hi Conditional guifg=#ffc0a8
hi Repeat guifg=#ffc0a8
hi Label guifg=#ffc0a8
hi Operator guifg=#fff0d7
hi Keyword guifg=#ffc0a8
hi Exception guifg=#ffad91

hi Include guifg=#f3c7e0
hi Define guifg=#f3c7e0
hi Macro guifg=#f3c7e0
hi PreCondit guifg=#f3c7e0

hi StorageClass guifg=#b9e9c2
hi Structure guifg=#b9e9c2
hi Typedef guifg=#b9e9c2

hi SpecialChar guifg=#c2efea
hi Tag guifg=#c2efea
hi Delimiter guifg=#fff0d7
hi SpecialComment guifg=#e1e5e2
hi Debug guifg=#ffe596

hi Ignore guifg=#164c72

" Cursor and line highlighting
hi Cursor guifg=#164c72 guibg=#ffc05d
hi CursorLine guibg=#35698b
hi CursorColumn guibg=#35698b

" Visual selection
hi Visual guibg=#35698b

" Search highlighting
hi Search guibg=#ffe596 guifg=#164c72
hi IncSearch guibg=#ffe596 guifg=#164c72

" Line numbers
hi LineNr guifg=#e1e5e2
hi CursorLineNr guifg=#fff0d7

" Status line
hi StatusLine guifg=#fff0d7 guibg=#e1e5e2
hi StatusLineNC guifg=#e1e5e2 guibg=#164c72

" Tab line
hi TabLine guifg=#e1e5e2 guibg=#164c72
hi TabLineSel guifg=#fff0d7 guibg=#35698b
hi TabLineFill guibg=#164c72

" Popup menu
hi Pmenu guifg=#fff0d7 guibg=#e1e5e2
hi PmenuSel guifg=#164c72 guibg=#35698b
hi PmenuSbar guibg=#e1e5e2
hi PmenuThumb guibg=#fff0d7

" Diff highlighting
hi DiffAdd guibg=#9fdfad
hi DiffChange guibg=#f6d67a
hi DiffDelete guibg=#ffad91
hi DiffText guibg=#b7d9f4

" Fold highlighting
hi Folded guifg=#e1e5e2 guibg=#164c72
hi FoldColumn guifg=#e1e5e2 guibg=#164c72

" Spell checking
hi SpellBad gui=undercurl guisp=#ffad91
hi SpellCap gui=undercurl guisp=#b7d9f4
hi SpellRare gui=undercurl guisp=#ecafd4
hi SpellLocal gui=undercurl guisp=#a6e5df

" Error and warning messages
hi ErrorMsg guifg=#ffad91
hi WarningMsg guifg=#f6d67a
hi MoreMsg guifg=#b7d9f4
hi Question guifg=#9fdfad

" Mode message
hi ModeMsg guifg=#9fdfad

" Directory
hi Directory guifg=#b7d9f4

" Title
hi Title guifg=#ecafd4

" Match parenthesis
hi MatchParen guibg=#e1e5e2

" Sign column
hi SignColumn guifg=#e1e5e2 guibg=#164c72
