" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Monsoon Mesa
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Monsoon-Mesa"

" Normal colors
hi Normal guifg=#f8f1df guibg=#164b58

" Syntax highlighting groups
hi Comment guifg=#dee4e2
hi Constant guifg=#f0d278
hi Identifier guifg=#a7d1ef
hi Statement guifg=#fbb7a6
hi PreProc guifg=#e9c8e7
hi Type guifg=#afe3bc
hi Special guifg=#b7ebe7
hi Underlined guifg=#c0def4 gui=underline
hi Error guifg=#f7a18d guibg=#164b58
hi Todo guifg=#f7e097 guibg=#164b58

" Additional groups for better compatibility
hi String guifg=#98d9ac
hi Character guifg=#98d9ac
hi Number guifg=#f0d278
hi Boolean guifg=#f0d278
hi Float guifg=#f0d278

hi Function guifg=#a7d1ef

hi Conditional guifg=#fbb7a6
hi Repeat guifg=#fbb7a6
hi Label guifg=#fbb7a6
hi Operator guifg=#f8f1df
hi Keyword guifg=#fbb7a6
hi Exception guifg=#f7a18d

hi Include guifg=#e9c8e7
hi Define guifg=#e9c8e7
hi Macro guifg=#e9c8e7
hi PreCondit guifg=#e9c8e7

hi StorageClass guifg=#afe3bc
hi Structure guifg=#afe3bc
hi Typedef guifg=#afe3bc

hi SpecialChar guifg=#b7ebe7
hi Tag guifg=#b7ebe7
hi Delimiter guifg=#f8f1df
hi SpecialComment guifg=#dee4e2
hi Debug guifg=#f7e097

hi Ignore guifg=#164b58

" Cursor and line highlighting
hi Cursor guifg=#164b58 guibg=#f4c96a
hi CursorLine guibg=#356873
hi CursorColumn guibg=#356873

" Visual selection
hi Visual guibg=#356873

" Search highlighting
hi Search guibg=#f7e097 guifg=#164b58
hi IncSearch guibg=#f7e097 guifg=#164b58

" Line numbers
hi LineNr guifg=#dee4e2
hi CursorLineNr guifg=#f8f1df

" Status line
hi StatusLine guifg=#f8f1df guibg=#dee4e2
hi StatusLineNC guifg=#dee4e2 guibg=#164b58

" Tab line
hi TabLine guifg=#dee4e2 guibg=#164b58
hi TabLineSel guifg=#f8f1df guibg=#356873
hi TabLineFill guibg=#164b58

" Popup menu
hi Pmenu guifg=#f8f1df guibg=#dee4e2
hi PmenuSel guifg=#164b58 guibg=#356873
hi PmenuSbar guibg=#dee4e2
hi PmenuThumb guibg=#f8f1df

" Diff highlighting
hi DiffAdd guibg=#98d9ac
hi DiffChange guibg=#f0d278
hi DiffDelete guibg=#f7a18d
hi DiffText guibg=#a7d1ef

" Fold highlighting
hi Folded guifg=#dee4e2 guibg=#164b58
hi FoldColumn guifg=#dee4e2 guibg=#164b58

" Spell checking
hi SpellBad gui=undercurl guisp=#f7a18d
hi SpellCap gui=undercurl guisp=#a7d1ef
hi SpellRare gui=undercurl guisp=#dfb1dc
hi SpellLocal gui=undercurl guisp=#9ae1de

" Error and warning messages
hi ErrorMsg guifg=#f7a18d
hi WarningMsg guifg=#f0d278
hi MoreMsg guifg=#a7d1ef
hi Question guifg=#98d9ac

" Mode message
hi ModeMsg guifg=#98d9ac

" Directory
hi Directory guifg=#a7d1ef

" Title
hi Title guifg=#dfb1dc

" Match parenthesis
hi MatchParen guibg=#dee4e2

" Sign column
hi SignColumn guifg=#dee4e2 guibg=#164b58
