" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Outrun Electric
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Outrun-Electric"

" Normal colors
hi Normal guifg=#f2f3f7 guibg=#0c0a20

" Syntax highlighting groups
hi Comment guifg=#546a90
hi Constant guifg=#ffd400
hi Identifier guifg=#1ea8fc
hi Statement guifg=#ef6d85
hi PreProc guifg=#df85ff
hi Type guifg=#c6e76d
hi Special guifg=#84daff
hi Underlined guifg=#6dc6fd gui=underline
hi Error guifg=#e61f44 guibg=#0c0a20
hi Todo guifg=#ffe359 guibg=#0c0a20

" Additional groups for better compatibility
hi String guifg=#a7da1e
hi Character guifg=#a7da1e
hi Number guifg=#ffd400
hi Boolean guifg=#ffd400
hi Float guifg=#ffd400

hi Function guifg=#1ea8fc

hi Conditional guifg=#ef6d85
hi Repeat guifg=#ef6d85
hi Label guifg=#ef6d85
hi Operator guifg=#f2f3f7
hi Keyword guifg=#ef6d85
hi Exception guifg=#e61f44

hi Include guifg=#df85ff
hi Define guifg=#df85ff
hi Macro guifg=#df85ff
hi PreCondit guifg=#df85ff

hi StorageClass guifg=#c6e76d
hi Structure guifg=#c6e76d
hi Typedef guifg=#c6e76d

hi SpecialChar guifg=#84daff
hi Tag guifg=#84daff
hi Delimiter guifg=#f2f3f7
hi SpecialComment guifg=#546a90
hi Debug guifg=#ffe359

hi Ignore guifg=#0c0a20

" Cursor and line highlighting
hi Cursor guifg=#0c0a20 guibg=#ff2afc
hi CursorLine guibg=#ba45a3
hi CursorColumn guibg=#ba45a3

" Visual selection
hi Visual guibg=#ba45a3

" Search highlighting
hi Search guibg=#ffe359 guifg=#0c0a20
hi IncSearch guibg=#ffe359 guifg=#0c0a20

" Line numbers
hi LineNr guifg=#546a90
hi CursorLineNr guifg=#f2f3f7

" Status line
hi StatusLine guifg=#f2f3f7 guibg=#546a90
hi StatusLineNC guifg=#546a90 guibg=#0c0a20

" Tab line
hi TabLine guifg=#546a90 guibg=#0c0a20
hi TabLineSel guifg=#f2f3f7 guibg=#ba45a3
hi TabLineFill guibg=#0c0a20

" Popup menu
hi Pmenu guifg=#f2f3f7 guibg=#546a90
hi PmenuSel guifg=#0c0a20 guibg=#ba45a3
hi PmenuSbar guibg=#546a90
hi PmenuThumb guibg=#f2f3f7

" Diff highlighting
hi DiffAdd guibg=#a7da1e
hi DiffChange guibg=#ffd400
hi DiffDelete guibg=#e61f44
hi DiffText guibg=#1ea8fc

" Fold highlighting
hi Folded guifg=#546a90 guibg=#0c0a20
hi FoldColumn guifg=#546a90 guibg=#0c0a20

" Spell checking
hi SpellBad gui=undercurl guisp=#e61f44
hi SpellCap gui=undercurl guisp=#1ea8fc
hi SpellRare gui=undercurl guisp=#ff2afc
hi SpellLocal gui=undercurl guisp=#42c6ff

" Error and warning messages
hi ErrorMsg guifg=#e61f44
hi WarningMsg guifg=#ffd400
hi MoreMsg guifg=#1ea8fc
hi Question guifg=#a7da1e

" Mode message
hi ModeMsg guifg=#a7da1e

" Directory
hi Directory guifg=#1ea8fc

" Title
hi Title guifg=#ff2afc

" Match parenthesis
hi MatchParen guibg=#546a90

" Sign column
hi SignColumn guifg=#546a90 guibg=#0c0a20
