" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Poltergeist
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Poltergeist"

" Normal colors
hi Normal guifg=#f0ffff guibg=#06444b

" Syntax highlighting groups
hi Comment guifg=#c8d7d7
hi Constant guifg=#e9d06c
hi Identifier guifg=#8ed4ed
hi Statement guifg=#ffa89e
hi PreProc guifg=#ccb2eb
hi Type guifg=#9ae4b9
hi Special guifg=#87e5e3
hi Underlined guifg=#9cd9ef gui=underline
hi Error guifg=#ff9c91 guibg=#06444b
hi Todo guifg=#ecd67e guibg=#06444b

" Additional groups for better compatibility
hi String guifg=#8ce0b0
hi Character guifg=#8ce0b0
hi Number guifg=#e9d06c
hi Boolean guifg=#e9d06c
hi Float guifg=#e9d06c

hi Function guifg=#8ed4ed

hi Conditional guifg=#ffa89e
hi Repeat guifg=#ffa89e
hi Label guifg=#ffa89e
hi Operator guifg=#f0ffff
hi Keyword guifg=#ffa89e
hi Exception guifg=#ff9c91

hi Include guifg=#ccb2eb
hi Define guifg=#ccb2eb
hi Macro guifg=#ccb2eb
hi PreCondit guifg=#ccb2eb

hi StorageClass guifg=#9ae4b9
hi Structure guifg=#9ae4b9
hi Typedef guifg=#9ae4b9

hi SpecialChar guifg=#87e5e3
hi Tag guifg=#87e5e3
hi Delimiter guifg=#f0ffff
hi SpecialComment guifg=#c8d7d7
hi Debug guifg=#ecd67e

hi Ignore guifg=#06444b

" Cursor and line highlighting
hi Cursor guifg=#06444b guibg=#ffa89e
hi CursorLine guibg=#c8d7d7
hi CursorColumn guibg=#c8d7d7

" Visual selection
hi Visual guibg=#c8d7d7

" Search highlighting
hi Search guibg=#ecd67e guifg=#06444b
hi IncSearch guibg=#ecd67e guifg=#06444b

" Line numbers
hi LineNr guifg=#c8d7d7
hi CursorLineNr guifg=#f0ffff

" Status line
hi StatusLine guifg=#f0ffff guibg=#c8d7d7
hi StatusLineNC guifg=#c8d7d7 guibg=#06444b

" Tab line
hi TabLine guifg=#c8d7d7 guibg=#06444b
hi TabLineSel guifg=#f0ffff guibg=#c8d7d7
hi TabLineFill guibg=#06444b

" Popup menu
hi Pmenu guifg=#f0ffff guibg=#c8d7d7
hi PmenuSel guifg=#06444b guibg=#c8d7d7
hi PmenuSbar guibg=#c8d7d7
hi PmenuThumb guibg=#f0ffff

" Diff highlighting
hi DiffAdd guibg=#8ce0b0
hi DiffChange guibg=#e9d06c
hi DiffDelete guibg=#ff9c91
hi DiffText guibg=#8ed4ed

" Fold highlighting
hi Folded guifg=#c8d7d7 guibg=#06444b
hi FoldColumn guifg=#c8d7d7 guibg=#06444b

" Spell checking
hi SpellBad gui=undercurl guisp=#ff9c91
hi SpellCap gui=undercurl guisp=#8ed4ed
hi SpellRare gui=undercurl guisp=#c5a7e8
hi SpellLocal gui=undercurl guisp=#77e1df

" Error and warning messages
hi ErrorMsg guifg=#ff9c91
hi WarningMsg guifg=#e9d06c
hi MoreMsg guifg=#8ed4ed
hi Question guifg=#8ce0b0

" Mode message
hi ModeMsg guifg=#8ce0b0

" Directory
hi Directory guifg=#8ed4ed

" Title
hi Title guifg=#c5a7e8

" Match parenthesis
hi MatchParen guibg=#c8d7d7

" Sign column
hi SignColumn guifg=#c8d7d7 guibg=#06444b
