" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Purple Portal
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Purple-Portal"

" Normal colors
hi Normal guifg=#faf5ff guibg=#160528

" Syntax highlighting groups
hi Comment guifg=#503872
hi Constant guifg=#f472b6
hi Identifier guifg=#facc15
hi Statement guifg=#fc8d9d
hi PreProc guifg=#60caf9
hi Type guifg=#5ddcad
hi Special guifg=#793ff3
hi Underlined guifg=#fbd644 gui=underline
hi Error guifg=#fb7185 guibg=#160528
hi Todo guifg=#f68bc3 guibg=#160528

" Additional groups for better compatibility
hi String guifg=#34d399
hi Character guifg=#34d399
hi Number guifg=#f472b6
hi Boolean guifg=#f472b6
hi Float guifg=#f472b6

hi Function guifg=#facc15

hi Conditional guifg=#fc8d9d
hi Repeat guifg=#fc8d9d
hi Label guifg=#fc8d9d
hi Operator guifg=#d8b4fe
hi Keyword guifg=#fc8d9d
hi Exception guifg=#fb7185

hi Include guifg=#60caf9
hi Define guifg=#60caf9
hi Macro guifg=#60caf9
hi PreCondit guifg=#60caf9

hi StorageClass guifg=#5ddcad
hi Structure guifg=#5ddcad
hi Typedef guifg=#5ddcad

hi SpecialChar guifg=#793ff3
hi Tag guifg=#793ff3
hi Delimiter guifg=#d8b4fe
hi SpecialComment guifg=#503872
hi Debug guifg=#f68bc3

hi Ignore guifg=#160528

" Cursor and line highlighting
hi Cursor guifg=#160528 guibg=#faf5ff
hi CursorLine guibg=#faf5ff
hi CursorColumn guibg=#faf5ff

" Visual selection
hi Visual guibg=#faf5ff

" Search highlighting
hi Search guibg=#f68bc3 guifg=#160528
hi IncSearch guibg=#f68bc3 guifg=#160528

" Line numbers
hi LineNr guifg=#503872
hi CursorLineNr guifg=#faf5ff

" Status line
hi StatusLine guifg=#faf5ff guibg=#503872
hi StatusLineNC guifg=#503872 guibg=#160528

" Tab line
hi TabLine guifg=#503872 guibg=#160528
hi TabLineSel guifg=#faf5ff guibg=#faf5ff
hi TabLineFill guibg=#160528

" Popup menu
hi Pmenu guifg=#faf5ff guibg=#503872
hi PmenuSel guifg=#160528 guibg=#faf5ff
hi PmenuSbar guibg=#503872
hi PmenuThumb guibg=#faf5ff

" Diff highlighting
hi DiffAdd guibg=#34d399
hi DiffChange guibg=#f472b6
hi DiffDelete guibg=#fb7185
hi DiffText guibg=#facc15

" Fold highlighting
hi Folded guifg=#503872 guibg=#160528
hi FoldColumn guifg=#503872 guibg=#160528

" Spell checking
hi SpellBad gui=undercurl guisp=#fb7185
hi SpellCap gui=undercurl guisp=#facc15
hi SpellRare gui=undercurl guisp=#38bdf8
hi SpellLocal gui=undercurl guisp=#580ff0

" Error and warning messages
hi ErrorMsg guifg=#fb7185
hi WarningMsg guifg=#f472b6
hi MoreMsg guifg=#facc15
hi Question guifg=#34d399

" Mode message
hi ModeMsg guifg=#34d399

" Directory
hi Directory guifg=#facc15

" Title
hi Title guifg=#38bdf8

" Match parenthesis
hi MatchParen guibg=#503872

" Sign column
hi SignColumn guifg=#503872 guibg=#160528
