" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Rhoads Insipired
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Rhoads-Insipired"

" Normal colors
hi Normal guifg=#f5f5f0 guibg=#0a0a0a

" Syntax highlighting groups
hi Comment guifg=#555555
hi Constant guifg=#f5a623
hi Identifier guifg=#5aa9e6
hi Statement guifg=#ff7474
hi PreProc guifg=#d69bf4
hi Type guifg=#d4ef91
hi Special guifg=#7be0dc
hi Underlined guifg=#85c7f2 gui=underline
hi Error guifg=#e85d5d guibg=#0a0a0a
hi Todo guifg=#ffd166 guibg=#0a0a0a

" Additional groups for better compatibility
hi String guifg=#b7d96c
hi Character guifg=#b7d96c
hi Number guifg=#f5a623
hi Boolean guifg=#f5a623
hi Float guifg=#f5a623

hi Function guifg=#5aa9e6

hi Conditional guifg=#ff7474
hi Repeat guifg=#ff7474
hi Label guifg=#ff7474
hi Operator guifg=#e8e8e3
hi Keyword guifg=#ff7474
hi Exception guifg=#e85d5d

hi Include guifg=#d69bf4
hi Define guifg=#d69bf4
hi Macro guifg=#d69bf4
hi PreCondit guifg=#d69bf4

hi StorageClass guifg=#d4ef91
hi Structure guifg=#d4ef91
hi Typedef guifg=#d4ef91

hi SpecialChar guifg=#7be0dc
hi Tag guifg=#7be0dc
hi Delimiter guifg=#e8e8e3
hi SpecialComment guifg=#555555
hi Debug guifg=#ffd166

hi Ignore guifg=#0a0a0a

" Cursor and line highlighting
hi Cursor guifg=#f5f5f0 guibg=#a855f7
hi CursorLine guibg=#f4b942
hi CursorColumn guibg=#f4b942

" Visual selection
hi Visual guibg=#f4b942

" Search highlighting
hi Search guibg=#ffd166 guifg=#0a0a0a
hi IncSearch guibg=#ffd166 guifg=#0a0a0a

" Line numbers
hi LineNr guifg=#555555
hi CursorLineNr guifg=#f5f5f0

" Status line
hi StatusLine guifg=#f5f5f0 guibg=#555555
hi StatusLineNC guifg=#555555 guibg=#0a0a0a

" Tab line
hi TabLine guifg=#555555 guibg=#0a0a0a
hi TabLineSel guifg=#f5f5f0 guibg=#f4b942
hi TabLineFill guibg=#0a0a0a

" Popup menu
hi Pmenu guifg=#f5f5f0 guibg=#555555
hi PmenuSel guifg=#0a0a0a guibg=#f4b942
hi PmenuSbar guibg=#555555
hi PmenuThumb guibg=#f5f5f0

" Diff highlighting
hi DiffAdd guibg=#b7d96c
hi DiffChange guibg=#f5a623
hi DiffDelete guibg=#e85d5d
hi DiffText guibg=#5aa9e6

" Fold highlighting
hi Folded guifg=#555555 guibg=#0a0a0a
hi FoldColumn guifg=#555555 guibg=#0a0a0a

" Spell checking
hi SpellBad gui=undercurl guisp=#e85d5d
hi SpellCap gui=undercurl guisp=#5aa9e6
hi SpellRare gui=undercurl guisp=#b66de8
hi SpellLocal gui=undercurl guisp=#50c8c6

" Error and warning messages
hi ErrorMsg guifg=#e85d5d
hi WarningMsg guifg=#f5a623
hi MoreMsg guifg=#5aa9e6
hi Question guifg=#b7d96c

" Mode message
hi ModeMsg guifg=#b7d96c

" Directory
hi Directory guifg=#5aa9e6

" Title
hi Title guifg=#b66de8

" Match parenthesis
hi MatchParen guibg=#555555

" Sign column
hi SignColumn guifg=#555555 guibg=#0a0a0a
