" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Rhoads LP
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Rhoads-LP"

" Normal colors
hi Normal guifg=#2b2618 guibg=#fdf7e8

" Syntax highlighting groups
hi Comment guifg=#8a8474
hi Constant guifg=#d6b852
hi Identifier guifg=#5b7fd6
hi Statement guifg=#e66f67
hi PreProc guifg=#c39be8
hi Type guifg=#91bd79
hi Special guifg=#68bfbb
hi Underlined guifg=#86a5e8 gui=underline
hi Error guifg=#c5423a guibg=#fdf7e8
hi Todo guifg=#ceb352 guibg=#fdf7e8

" Additional groups for better compatibility
hi String guifg=#5f8f4f
hi Character guifg=#5f8f4f
hi Number guifg=#d6b852
hi Boolean guifg=#d6b852
hi Float guifg=#d6b852

hi Function guifg=#5b7fd6

hi Conditional guifg=#e66f67
hi Repeat guifg=#e66f67
hi Label guifg=#e66f67
hi Operator guifg=#c2bcb0
hi Keyword guifg=#e66f67
hi Exception guifg=#c5423a

hi Include guifg=#c39be8
hi Define guifg=#c39be8
hi Macro guifg=#c39be8
hi PreCondit guifg=#c39be8

hi StorageClass guifg=#91bd79
hi Structure guifg=#91bd79
hi Typedef guifg=#91bd79

hi SpecialChar guifg=#68bfbb
hi Tag guifg=#68bfbb
hi Delimiter guifg=#c2bcb0
hi SpecialComment guifg=#8a8474
hi Debug guifg=#ceb352

hi Ignore guifg=#fdf7e8

" Cursor and line highlighting
hi Cursor guifg=#fffaf0 guibg=#d4b34f
hi CursorLine guibg=#e0c878
hi CursorColumn guibg=#e0c878

" Visual selection
hi Visual guibg=#e0c878

" Search highlighting
hi Search guibg=#ceb352 guifg=#fdf7e8
hi IncSearch guibg=#ceb352 guifg=#fdf7e8

" Line numbers
hi LineNr guifg=#8a8474
hi CursorLineNr guifg=#2b2618

" Status line
hi StatusLine guifg=#2b2618 guibg=#8a8474
hi StatusLineNC guifg=#8a8474 guibg=#fdf7e8

" Tab line
hi TabLine guifg=#8a8474 guibg=#fdf7e8
hi TabLineSel guifg=#2b2618 guibg=#e0c878
hi TabLineFill guibg=#fdf7e8

" Popup menu
hi Pmenu guifg=#2b2618 guibg=#8a8474
hi PmenuSel guifg=#fdf7e8 guibg=#e0c878
hi PmenuSbar guibg=#8a8474
hi PmenuThumb guibg=#2b2618

" Diff highlighting
hi DiffAdd guibg=#5f8f4f
hi DiffChange guibg=#d6b852
hi DiffDelete guibg=#c5423a
hi DiffText guibg=#5b7fd6

" Fold highlighting
hi Folded guifg=#8a8474 guibg=#fdf7e8
hi FoldColumn guifg=#8a8474 guibg=#fdf7e8

" Spell checking
hi SpellBad gui=undercurl guisp=#c5423a
hi SpellCap gui=undercurl guisp=#5b7fd6
hi SpellRare gui=undercurl guisp=#a678d6
hi SpellLocal gui=undercurl guisp=#46c5c3

" Error and warning messages
hi ErrorMsg guifg=#c5423a
hi WarningMsg guifg=#d6b852
hi MoreMsg guifg=#5b7fd6
hi Question guifg=#5f8f4f

" Mode message
hi ModeMsg guifg=#5f8f4f

" Directory
hi Directory guifg=#5b7fd6

" Title
hi Title guifg=#a678d6

" Match parenthesis
hi MatchParen guibg=#8a8474

" Sign column
hi SignColumn guifg=#8a8474 guibg=#fdf7e8
