" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Rhoads Legacy
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Rhoads-Legacy"

" Normal colors
hi Normal guifg=#c4b5fd guibg=#0a0614

" Syntax highlighting groups
hi Comment guifg=#4b3f72
hi Constant guifg=#f4d03f
hi Identifier guifg=#6366f1
hi Statement guifg=#d946ef
hi PreProc guifg=#e9d5ff
hi Type guifg=#f472b6
hi Special guifg=#cbd5e1
hi Underlined guifg=#7c9cff gui=underline
hi Error guifg=#7c3aed guibg=#0a0614
hi Todo guifg=#fde68a guibg=#0a0614

" Additional groups for better compatibility
hi String guifg=#d946ef
hi Character guifg=#d946ef
hi Number guifg=#f4d03f
hi Boolean guifg=#f4d03f
hi Float guifg=#f4d03f

hi Function guifg=#6366f1

hi Conditional guifg=#d946ef
hi Repeat guifg=#d946ef
hi Label guifg=#d946ef
hi Operator guifg=#f8f6ed
hi Keyword guifg=#d946ef
hi Exception guifg=#7c3aed

hi Include guifg=#e9d5ff
hi Define guifg=#e9d5ff
hi Macro guifg=#e9d5ff
hi PreCondit guifg=#e9d5ff

hi StorageClass guifg=#f472b6
hi Structure guifg=#f472b6
hi Typedef guifg=#f472b6

hi SpecialChar guifg=#cbd5e1
hi Tag guifg=#cbd5e1
hi Delimiter guifg=#f8f6ed
hi SpecialComment guifg=#4b3f72
hi Debug guifg=#fde68a

hi Ignore guifg=#0a0614

" Cursor and line highlighting
hi Cursor guifg=#0a0614 guibg=#f4d03f
hi CursorLine guibg=#4c1d95
hi CursorColumn guibg=#4c1d95

" Visual selection
hi Visual guibg=#4c1d95

" Search highlighting
hi Search guibg=#fde68a guifg=#0a0614
hi IncSearch guibg=#fde68a guifg=#0a0614

" Line numbers
hi LineNr guifg=#4b3f72
hi CursorLineNr guifg=#c4b5fd

" Status line
hi StatusLine guifg=#c4b5fd guibg=#4b3f72
hi StatusLineNC guifg=#4b3f72 guibg=#0a0614

" Tab line
hi TabLine guifg=#4b3f72 guibg=#0a0614
hi TabLineSel guifg=#c4b5fd guibg=#4c1d95
hi TabLineFill guibg=#0a0614

" Popup menu
hi Pmenu guifg=#c4b5fd guibg=#4b3f72
hi PmenuSel guifg=#0a0614 guibg=#4c1d95
hi PmenuSbar guibg=#4b3f72
hi PmenuThumb guibg=#c4b5fd

" Diff highlighting
hi DiffAdd guibg=#d946ef
hi DiffChange guibg=#f4d03f
hi DiffDelete guibg=#7c3aed
hi DiffText guibg=#6366f1

" Fold highlighting
hi Folded guifg=#4b3f72 guibg=#0a0614
hi FoldColumn guifg=#4b3f72 guibg=#0a0614

" Spell checking
hi SpellBad gui=undercurl guisp=#7c3aed
hi SpellCap gui=undercurl guisp=#6366f1
hi SpellRare gui=undercurl guisp=#a78bfa
hi SpellLocal gui=undercurl guisp=#c4b5fd

" Error and warning messages
hi ErrorMsg guifg=#7c3aed
hi WarningMsg guifg=#f4d03f
hi MoreMsg guifg=#6366f1
hi Question guifg=#d946ef

" Mode message
hi ModeMsg guifg=#d946ef

" Directory
hi Directory guifg=#6366f1

" Title
hi Title guifg=#a78bfa

" Match parenthesis
hi MatchParen guibg=#4b3f72

" Sign column
hi SignColumn guifg=#4b3f72 guibg=#0a0614
