" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Rover
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Rover"

" Normal colors
hi Normal guifg=#f5f8fd guibg=#0a0d14

" Syntax highlighting groups
hi Comment guifg=#9dabbd
hi Constant guifg=#d9b56b
hi Identifier guifg=#6a9fd0
hi Statement guifg=#ef8b93
hi PreProc guifg=#cbb4e6
hi Type guifg=#aedcba
hi Special guifg=#8fe4f0
hi Underlined guifg=#8fbce8 gui=underline
hi Error guifg=#e2707a guibg=#0a0d14
hi Todo guifg=#e8c98a guibg=#0a0d14

" Additional groups for better compatibility
hi String guifg=#93c9a2
hi Character guifg=#93c9a2
hi Number guifg=#d9b56b
hi Boolean guifg=#d9b56b
hi Float guifg=#d9b56b

hi Function guifg=#6a9fd0

hi Conditional guifg=#ef8b93
hi Repeat guifg=#ef8b93
hi Label guifg=#ef8b93
hi Operator guifg=#dee5ef
hi Keyword guifg=#ef8b93
hi Exception guifg=#e2707a

hi Include guifg=#cbb4e6
hi Define guifg=#cbb4e6
hi Macro guifg=#cbb4e6
hi PreCondit guifg=#cbb4e6

hi StorageClass guifg=#aedcba
hi Structure guifg=#aedcba
hi Typedef guifg=#aedcba

hi SpecialChar guifg=#8fe4f0
hi Tag guifg=#8fe4f0
hi Delimiter guifg=#dee5ef
hi SpecialComment guifg=#9dabbd
hi Debug guifg=#e8c98a

hi Ignore guifg=#0a0d14

" Cursor and line highlighting
hi Cursor guifg=#0a0d14 guibg=#7fdcea
hi CursorLine guibg=#223047
hi CursorColumn guibg=#223047

" Visual selection
hi Visual guibg=#223047

" Search highlighting
hi Search guibg=#e8c98a guifg=#0a0d14
hi IncSearch guibg=#e8c98a guifg=#0a0d14

" Line numbers
hi LineNr guifg=#9dabbd
hi CursorLineNr guifg=#f5f8fd

" Status line
hi StatusLine guifg=#f5f8fd guibg=#9dabbd
hi StatusLineNC guifg=#9dabbd guibg=#0a0d14

" Tab line
hi TabLine guifg=#9dabbd guibg=#0a0d14
hi TabLineSel guifg=#f5f8fd guibg=#223047
hi TabLineFill guibg=#0a0d14

" Popup menu
hi Pmenu guifg=#f5f8fd guibg=#9dabbd
hi PmenuSel guifg=#0a0d14 guibg=#223047
hi PmenuSbar guibg=#9dabbd
hi PmenuThumb guibg=#f5f8fd

" Diff highlighting
hi DiffAdd guibg=#93c9a2
hi DiffChange guibg=#d9b56b
hi DiffDelete guibg=#e2707a
hi DiffText guibg=#6a9fd0

" Fold highlighting
hi Folded guifg=#9dabbd guibg=#0a0d14
hi FoldColumn guifg=#9dabbd guibg=#0a0d14

" Spell checking
hi SpellBad gui=undercurl guisp=#e2707a
hi SpellCap gui=undercurl guisp=#6a9fd0
hi SpellRare gui=undercurl guisp=#b49ad8
hi SpellLocal gui=undercurl guisp=#5fd0e0

" Error and warning messages
hi ErrorMsg guifg=#e2707a
hi WarningMsg guifg=#d9b56b
hi MoreMsg guifg=#6a9fd0
hi Question guifg=#93c9a2

" Mode message
hi ModeMsg guifg=#93c9a2

" Directory
hi Directory guifg=#6a9fd0

" Title
hi Title guifg=#b49ad8

" Match parenthesis
hi MatchParen guibg=#9dabbd

" Sign column
hi SignColumn guifg=#9dabbd guibg=#0a0d14
