" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Seance
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Seance"

" Normal colors
hi Normal guifg=#f9eddf guibg=#3b2035

" Syntax highlighting groups
hi Comment guifg=#d0c5ca
hi Constant guifg=#e5c779
hi Identifier guifg=#9fc2dc
hi Statement guifg=#efb0a5
hi PreProc guifg=#e0bfd5
hi Type guifg=#bbdba5
hi Special guifg=#addbd5
hi Underlined guifg=#b8d1e5 gui=underline
hi Error guifg=#e99b8e guibg=#3b2035
hi Todo guifg=#edd796 guibg=#3b2035

" Additional groups for better compatibility
hi String guifg=#a8cf8f
hi Character guifg=#a8cf8f
hi Number guifg=#e5c779
hi Boolean guifg=#e5c779
hi Float guifg=#e5c779

hi Function guifg=#9fc2dc

hi Conditional guifg=#efb0a5
hi Repeat guifg=#efb0a5
hi Label guifg=#efb0a5
hi Operator guifg=#f9eddf
hi Keyword guifg=#efb0a5
hi Exception guifg=#e99b8e

hi Include guifg=#e0bfd5
hi Define guifg=#e0bfd5
hi Macro guifg=#e0bfd5
hi PreCondit guifg=#e0bfd5

hi StorageClass guifg=#bbdba5
hi Structure guifg=#bbdba5
hi Typedef guifg=#bbdba5

hi SpecialChar guifg=#addbd5
hi Tag guifg=#addbd5
hi Delimiter guifg=#f9eddf
hi SpecialComment guifg=#d0c5ca
hi Debug guifg=#edd796

hi Ignore guifg=#3b2035

" Cursor and line highlighting
hi Cursor guifg=#3b2035 guibg=#f1c76d
hi CursorLine guibg=#5b3b52
hi CursorColumn guibg=#5b3b52

" Visual selection
hi Visual guibg=#5b3b52

" Search highlighting
hi Search guibg=#edd796 guifg=#3b2035
hi IncSearch guibg=#edd796 guifg=#3b2035

" Line numbers
hi LineNr guifg=#d0c5ca
hi CursorLineNr guifg=#f9eddf

" Status line
hi StatusLine guifg=#f9eddf guibg=#d0c5ca
hi StatusLineNC guifg=#d0c5ca guibg=#3b2035

" Tab line
hi TabLine guifg=#d0c5ca guibg=#3b2035
hi TabLineSel guifg=#f9eddf guibg=#5b3b52
hi TabLineFill guibg=#3b2035

" Popup menu
hi Pmenu guifg=#f9eddf guibg=#d0c5ca
hi PmenuSel guifg=#3b2035 guibg=#5b3b52
hi PmenuSbar guibg=#d0c5ca
hi PmenuThumb guibg=#f9eddf

" Diff highlighting
hi DiffAdd guibg=#a8cf8f
hi DiffChange guibg=#e5c779
hi DiffDelete guibg=#e99b8e
hi DiffText guibg=#9fc2dc

" Fold highlighting
hi Folded guifg=#d0c5ca guibg=#3b2035
hi FoldColumn guifg=#d0c5ca guibg=#3b2035

" Spell checking
hi SpellBad gui=undercurl guisp=#e99b8e
hi SpellCap gui=undercurl guisp=#9fc2dc
hi SpellRare gui=undercurl guisp=#d5a6c8
hi SpellLocal gui=undercurl guisp=#8fcfc8

" Error and warning messages
hi ErrorMsg guifg=#e99b8e
hi WarningMsg guifg=#e5c779
hi MoreMsg guifg=#9fc2dc
hi Question guifg=#a8cf8f

" Mode message
hi ModeMsg guifg=#a8cf8f

" Directory
hi Directory guifg=#9fc2dc

" Title
hi Title guifg=#d5a6c8

" Match parenthesis
hi MatchParen guibg=#d0c5ca

" Sign column
hi SignColumn guifg=#d0c5ca guibg=#3b2035
