" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: SilkCircuit Glow
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "SilkCircuit-Glow"

" Normal colors
hi Normal guifg=#ffffff guibg=#0a0816

" Syntax highlighting groups
hi Comment guifg=#818181
hi Constant guifg=#ffff00
hi Identifier guifg=#0099ff
hi Statement guifg=#ff6666
hi PreProc guifg=#ff66ff
hi Type guifg=#66ff66
hi Special guifg=#66ffff
hi Underlined guifg=#66ccff gui=underline
hi Error guifg=#ff2244 guibg=#0a0816
hi Todo guifg=#ffff66 guibg=#0a0816

" Additional groups for better compatibility
hi String guifg=#00ff00
hi Character guifg=#00ff00
hi Number guifg=#ffff00
hi Boolean guifg=#ffff00
hi Float guifg=#ffff00

hi Function guifg=#0099ff

hi Conditional guifg=#ff6666
hi Repeat guifg=#ff6666
hi Label guifg=#ff6666
hi Operator guifg=#ffffff
hi Keyword guifg=#ff6666
hi Exception guifg=#ff2244

hi Include guifg=#ff66ff
hi Define guifg=#ff66ff
hi Macro guifg=#ff66ff
hi PreCondit guifg=#ff66ff

hi StorageClass guifg=#66ff66
hi Structure guifg=#66ff66
hi Typedef guifg=#66ff66

hi SpecialChar guifg=#66ffff
hi Tag guifg=#66ffff
hi Delimiter guifg=#ffffff
hi SpecialComment guifg=#818181
hi Debug guifg=#ffff66

hi Ignore guifg=#0a0816

" Cursor and line highlighting
hi Cursor guifg=#0a0816 guibg=#00ffff
hi CursorLine guibg=#4b0654
hi CursorColumn guibg=#4b0654

" Visual selection
hi Visual guibg=#4b0654

" Search highlighting
hi Search guibg=#ffff66 guifg=#0a0816
hi IncSearch guibg=#ffff66 guifg=#0a0816

" Line numbers
hi LineNr guifg=#818181
hi CursorLineNr guifg=#ffffff

" Status line
hi StatusLine guifg=#ffffff guibg=#818181
hi StatusLineNC guifg=#818181 guibg=#0a0816

" Tab line
hi TabLine guifg=#818181 guibg=#0a0816
hi TabLineSel guifg=#ffffff guibg=#4b0654
hi TabLineFill guibg=#0a0816

" Popup menu
hi Pmenu guifg=#ffffff guibg=#818181
hi PmenuSel guifg=#0a0816 guibg=#4b0654
hi PmenuSbar guibg=#818181
hi PmenuThumb guibg=#ffffff

" Diff highlighting
hi DiffAdd guibg=#00ff00
hi DiffChange guibg=#ffff00
hi DiffDelete guibg=#ff2244
hi DiffText guibg=#0099ff

" Fold highlighting
hi Folded guifg=#818181 guibg=#0a0816
hi FoldColumn guifg=#818181 guibg=#0a0816

" Spell checking
hi SpellBad gui=undercurl guisp=#ff2244
hi SpellCap gui=undercurl guisp=#0099ff
hi SpellRare gui=undercurl guisp=#ff00ff
hi SpellLocal gui=undercurl guisp=#00ffff

" Error and warning messages
hi ErrorMsg guifg=#ff2244
hi WarningMsg guifg=#ffff00
hi MoreMsg guifg=#0099ff
hi Question guifg=#00ff00

" Mode message
hi ModeMsg guifg=#00ff00

" Directory
hi Directory guifg=#0099ff

" Title
hi Title guifg=#ff00ff

" Match parenthesis
hi MatchParen guibg=#818181

" Sign column
hi SignColumn guifg=#818181 guibg=#0a0816
