" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Springfield Resident Hight Contrast
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Springfield-Resident-Hight-Contrast"

" Normal colors
hi Normal guifg=#062f63 guibg=#ffdd32

" Syntax highlighting groups
hi Comment guifg=#343b46
hi Constant guifg=#5d3e00
hi Identifier guifg=#063d82
hi Statement guifg=#85162c
hi PreProc guifg=#701966
hi Type guifg=#164e27
hi Special guifg=#004a5c
hi Underlined guifg=#084287 gui=underline
hi Error guifg=#7a1026 guibg=#ffdd32
hi Todo guifg=#5c3e00 guibg=#ffdd32

" Additional groups for better compatibility
hi String guifg=#134e24
hi Character guifg=#134e24
hi Number guifg=#5d3e00
hi Boolean guifg=#5d3e00
hi Float guifg=#5d3e00

hi Function guifg=#063d82

hi Conditional guifg=#85162c
hi Repeat guifg=#85162c
hi Label guifg=#85162c
hi Operator guifg=#29303b
hi Keyword guifg=#85162c
hi Exception guifg=#7a1026

hi Include guifg=#701966
hi Define guifg=#701966
hi Macro guifg=#701966
hi PreCondit guifg=#701966

hi StorageClass guifg=#164e27
hi Structure guifg=#164e27
hi Typedef guifg=#164e27

hi SpecialChar guifg=#004a5c
hi Tag guifg=#004a5c
hi Delimiter guifg=#29303b
hi SpecialComment guifg=#343b46
hi Debug guifg=#5c3e00

hi Ignore guifg=#ffdd32

" Cursor and line highlighting
hi Cursor guifg=#fff3a3 guibg=#0b4b94
hi CursorLine guibg=#0b4b94
hi CursorColumn guibg=#0b4b94

" Visual selection
hi Visual guibg=#0b4b94

" Search highlighting
hi Search guibg=#5c3e00 guifg=#ffdd32
hi IncSearch guibg=#5c3e00 guifg=#ffdd32

" Line numbers
hi LineNr guifg=#343b46
hi CursorLineNr guifg=#062f63

" Status line
hi StatusLine guifg=#062f63 guibg=#343b46
hi StatusLineNC guifg=#343b46 guibg=#ffdd32

" Tab line
hi TabLine guifg=#343b46 guibg=#ffdd32
hi TabLineSel guifg=#062f63 guibg=#0b4b94
hi TabLineFill guibg=#ffdd32

" Popup menu
hi Pmenu guifg=#062f63 guibg=#343b46
hi PmenuSel guifg=#ffdd32 guibg=#0b4b94
hi PmenuSbar guibg=#343b46
hi PmenuThumb guibg=#062f63

" Diff highlighting
hi DiffAdd guibg=#134e24
hi DiffChange guibg=#5d3e00
hi DiffDelete guibg=#7a1026
hi DiffText guibg=#063d82

" Fold highlighting
hi Folded guifg=#343b46 guibg=#ffdd32
hi FoldColumn guifg=#343b46 guibg=#ffdd32

" Spell checking
hi SpellBad gui=undercurl guisp=#7a1026
hi SpellCap gui=undercurl guisp=#063d82
hi SpellRare gui=undercurl guisp=#67145d
hi SpellLocal gui=undercurl guisp=#004a5d

" Error and warning messages
hi ErrorMsg guifg=#7a1026
hi WarningMsg guifg=#5d3e00
hi MoreMsg guifg=#063d82
hi Question guifg=#134e24

" Mode message
hi ModeMsg guifg=#134e24

" Directory
hi Directory guifg=#063d82

" Title
hi Title guifg=#67145d

" Match parenthesis
hi MatchParen guibg=#343b46

" Sign column
hi SignColumn guifg=#343b46 guibg=#ffdd32
