" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Terminal Green 1999
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Terminal-Green-1999"

" Normal colors
hi Normal guifg=#d8ffe6 guibg=#03120a

" Syntax highlighting groups
hi Comment guifg=#274335
hi Constant guifg=#00d26a
hi Identifier guifg=#7dd3fc
hi Statement guifg=#ff7d95
hi PreProc guifg=#b1ff79
hi Type guifg=#4ed17e
hi Special guifg=#61ffa0
hi Underlined guifg=#97dcfd gui=underline
hi Error guifg=#ff5c7a guibg=#03120a
hi Todo guifg=#2eda85 guibg=#03120a

" Additional groups for better compatibility
hi String guifg=#22c55e
hi Character guifg=#22c55e
hi Number guifg=#00d26a
hi Boolean guifg=#00d26a
hi Float guifg=#00d26a

hi Function guifg=#7dd3fc

hi Conditional guifg=#ff7d95
hi Repeat guifg=#ff7d95
hi Label guifg=#ff7d95
hi Operator guifg=#8fd6a9
hi Keyword guifg=#ff7d95
hi Exception guifg=#ff5c7a

hi Include guifg=#b1ff79
hi Define guifg=#b1ff79
hi Macro guifg=#b1ff79
hi PreCondit guifg=#b1ff79

hi StorageClass guifg=#4ed17e
hi Structure guifg=#4ed17e
hi Typedef guifg=#4ed17e

hi SpecialChar guifg=#61ffa0
hi Tag guifg=#61ffa0
hi Delimiter guifg=#8fd6a9
hi SpecialComment guifg=#274335
hi Debug guifg=#2eda85

hi Ignore guifg=#03120a

" Cursor and line highlighting
hi Cursor guifg=#03120a guibg=#d8ffe6
hi CursorLine guibg=#d8ffe6
hi CursorColumn guibg=#d8ffe6

" Visual selection
hi Visual guibg=#d8ffe6

" Search highlighting
hi Search guibg=#2eda85 guifg=#03120a
hi IncSearch guibg=#2eda85 guifg=#03120a

" Line numbers
hi LineNr guifg=#274335
hi CursorLineNr guifg=#d8ffe6

" Status line
hi StatusLine guifg=#d8ffe6 guibg=#274335
hi StatusLineNC guifg=#274335 guibg=#03120a

" Tab line
hi TabLine guifg=#274335 guibg=#03120a
hi TabLineSel guifg=#d8ffe6 guibg=#d8ffe6
hi TabLineFill guibg=#03120a

" Popup menu
hi Pmenu guifg=#d8ffe6 guibg=#274335
hi PmenuSel guifg=#03120a guibg=#d8ffe6
hi PmenuSbar guibg=#274335
hi PmenuThumb guibg=#d8ffe6

" Diff highlighting
hi DiffAdd guibg=#22c55e
hi DiffChange guibg=#00d26a
hi DiffDelete guibg=#ff5c7a
hi DiffText guibg=#7dd3fc

" Fold highlighting
hi Folded guifg=#274335 guibg=#03120a
hi FoldColumn guifg=#274335 guibg=#03120a

" Spell checking
hi SpellBad gui=undercurl guisp=#ff5c7a
hi SpellCap gui=undercurl guisp=#7dd3fc
hi SpellRare gui=undercurl guisp=#9dff57
hi SpellLocal gui=undercurl guisp=#39ff88

" Error and warning messages
hi ErrorMsg guifg=#ff5c7a
hi WarningMsg guifg=#00d26a
hi MoreMsg guifg=#7dd3fc
hi Question guifg=#22c55e

" Mode message
hi ModeMsg guifg=#22c55e

" Directory
hi Directory guifg=#7dd3fc

" Title
hi Title guifg=#9dff57

" Match parenthesis
hi MatchParen guibg=#274335

" Sign column
hi SignColumn guifg=#274335 guibg=#03120a
