" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Trick or Treat
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Trick-or-Treat"

" Normal colors
hi Normal guifg=#fff0e3 guibg=#40145f

" Syntax highlighting groups
hi Comment guifg=#cec1da
hi Constant guifg=#f8c94e
hi Identifier guifg=#8fc9f2
hi Statement guifg=#ffa5a0
hi PreProc guifg=#efaae3
hi Type guifg=#bde88d
hi Special guifg=#99e7ea
hi Underlined guifg=#acd9f7 gui=underline
hi Error guifg=#ff8b82 guibg=#40145f
hi Todo guifg=#fbdc72 guibg=#40145f

" Additional groups for better compatibility
hi String guifg=#a8dc72
hi Character guifg=#a8dc72
hi Number guifg=#f8c94e
hi Boolean guifg=#f8c94e
hi Float guifg=#f8c94e

hi Function guifg=#8fc9f2

hi Conditional guifg=#ffa5a0
hi Repeat guifg=#ffa5a0
hi Label guifg=#ffa5a0
hi Operator guifg=#fff0e3
hi Keyword guifg=#ffa5a0
hi Exception guifg=#ff8b82

hi Include guifg=#efaae3
hi Define guifg=#efaae3
hi Macro guifg=#efaae3
hi PreCondit guifg=#efaae3

hi StorageClass guifg=#bde88d
hi Structure guifg=#bde88d
hi Typedef guifg=#bde88d

hi SpecialChar guifg=#99e7ea
hi Tag guifg=#99e7ea
hi Delimiter guifg=#fff0e3
hi SpecialComment guifg=#cec1da
hi Debug guifg=#fbdc72

hi Ignore guifg=#40145f

" Cursor and line highlighting
hi Cursor guifg=#40145f guibg=#ff65bd
hi CursorLine guibg=#642b82
hi CursorColumn guibg=#642b82

" Visual selection
hi Visual guibg=#642b82

" Search highlighting
hi Search guibg=#fbdc72 guifg=#40145f
hi IncSearch guibg=#fbdc72 guifg=#40145f

" Line numbers
hi LineNr guifg=#cec1da
hi CursorLineNr guifg=#fff0e3

" Status line
hi StatusLine guifg=#fff0e3 guibg=#cec1da
hi StatusLineNC guifg=#cec1da guibg=#40145f

" Tab line
hi TabLine guifg=#cec1da guibg=#40145f
hi TabLineSel guifg=#fff0e3 guibg=#642b82
hi TabLineFill guibg=#40145f

" Popup menu
hi Pmenu guifg=#fff0e3 guibg=#cec1da
hi PmenuSel guifg=#40145f guibg=#642b82
hi PmenuSbar guibg=#cec1da
hi PmenuThumb guibg=#fff0e3

" Diff highlighting
hi DiffAdd guibg=#a8dc72
hi DiffChange guibg=#f8c94e
hi DiffDelete guibg=#ff8b82
hi DiffText guibg=#8fc9f2

" Fold highlighting
hi Folded guifg=#cec1da guibg=#40145f
hi FoldColumn guifg=#cec1da guibg=#40145f

" Spell checking
hi SpellBad gui=undercurl guisp=#ff8b82
hi SpellCap gui=undercurl guisp=#8fc9f2
hi SpellRare gui=undercurl guisp=#e78bd8
hi SpellLocal gui=undercurl guisp=#78dce1

" Error and warning messages
hi ErrorMsg guifg=#ff8b82
hi WarningMsg guifg=#f8c94e
hi MoreMsg guifg=#8fc9f2
hi Question guifg=#a8dc72

" Mode message
hi ModeMsg guifg=#a8dc72

" Directory
hi Directory guifg=#8fc9f2

" Title
hi Title guifg=#e78bd8

" Match parenthesis
hi MatchParen guibg=#cec1da

" Sign column
hi SignColumn guifg=#cec1da guibg=#40145f
