" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Vaporwave Sunset
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Vaporwave-Sunset"

" Normal colors
hi Normal guifg=#fff7ed guibg=#180827

" Syntax highlighting groups
hi Comment guifg=#563f6e
hi Constant guifg=#fb923c
hi Identifier guifg=#a78bfa
hi Statement guifg=#fc8d9d
hi PreProc guifg=#4edcf1
hi Type guifg=#57ddcc
hi Special guifg=#ff72e0
hi Underlined guifg=#b9a2fb gui=underline
hi Error guifg=#fb7185 guibg=#180827
hi Todo guifg=#fca65f guibg=#180827

" Additional groups for better compatibility
hi String guifg=#2dd4bf
hi Character guifg=#2dd4bf
hi Number guifg=#fb923c
hi Boolean guifg=#fb923c
hi Float guifg=#fb923c

hi Function guifg=#a78bfa

hi Conditional guifg=#fc8d9d
hi Repeat guifg=#fc8d9d
hi Label guifg=#fc8d9d
hi Operator guifg=#f0abfc
hi Keyword guifg=#fc8d9d
hi Exception guifg=#fb7185

hi Include guifg=#4edcf1
hi Define guifg=#4edcf1
hi Macro guifg=#4edcf1
hi PreCondit guifg=#4edcf1

hi StorageClass guifg=#57ddcc
hi Structure guifg=#57ddcc
hi Typedef guifg=#57ddcc

hi SpecialChar guifg=#ff72e0
hi Tag guifg=#ff72e0
hi Delimiter guifg=#f0abfc
hi SpecialComment guifg=#563f6e
hi Debug guifg=#fca65f

hi Ignore guifg=#180827

" Cursor and line highlighting
hi Cursor guifg=#180827 guibg=#fff7ed
hi CursorLine guibg=#fff7ed
hi CursorColumn guibg=#fff7ed

" Visual selection
hi Visual guibg=#fff7ed

" Search highlighting
hi Search guibg=#fca65f guifg=#180827
hi IncSearch guibg=#fca65f guifg=#180827

" Line numbers
hi LineNr guifg=#563f6e
hi CursorLineNr guifg=#fff7ed

" Status line
hi StatusLine guifg=#fff7ed guibg=#563f6e
hi StatusLineNC guifg=#563f6e guibg=#180827

" Tab line
hi TabLine guifg=#563f6e guibg=#180827
hi TabLineSel guifg=#fff7ed guibg=#fff7ed
hi TabLineFill guibg=#180827

" Popup menu
hi Pmenu guifg=#fff7ed guibg=#563f6e
hi PmenuSel guifg=#180827 guibg=#fff7ed
hi PmenuSbar guibg=#563f6e
hi PmenuThumb guibg=#fff7ed

" Diff highlighting
hi DiffAdd guibg=#2dd4bf
hi DiffChange guibg=#fb923c
hi DiffDelete guibg=#fb7185
hi DiffText guibg=#a78bfa

" Fold highlighting
hi Folded guifg=#563f6e guibg=#180827
hi FoldColumn guifg=#563f6e guibg=#180827

" Spell checking
hi SpellBad gui=undercurl guisp=#fb7185
hi SpellCap gui=undercurl guisp=#a78bfa
hi SpellRare gui=undercurl guisp=#22d3ee
hi SpellLocal gui=undercurl guisp=#ff4fd8

" Error and warning messages
hi ErrorMsg guifg=#fb7185
hi WarningMsg guifg=#fb923c
hi MoreMsg guifg=#a78bfa
hi Question guifg=#2dd4bf

" Mode message
hi ModeMsg guifg=#2dd4bf

" Directory
hi Directory guifg=#a78bfa

" Title
hi Title guifg=#22d3ee

" Match parenthesis
hi MatchParen guibg=#563f6e

" Sign column
hi SignColumn guifg=#563f6e guibg=#180827
