" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Warm Burnout Dark
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Warm-Burnout-Dark"

" Normal colors
hi Normal guifg=#bfbdb6 guibg=#1a1510

" Syntax highlighting groups
hi Comment guifg=#686868
hi Constant guifg=#fdb04c
hi Identifier guifg=#4fbfff
hi Statement guifg=#f07178
hi PreProc guifg=#d2a6ff
hi Type guifg=#aad94c
hi Special guifg=#95e6cb
hi Underlined guifg=#59c2ff gui=underline
hi Error guifg=#f06b73 guibg=#1a1510
hi Todo guifg=#ffb454 guibg=#1a1510

" Additional groups for better compatibility
hi String guifg=#70bf56
hi Character guifg=#70bf56
hi Number guifg=#fdb04c
hi Boolean guifg=#fdb04c
hi Float guifg=#fdb04c

hi Function guifg=#4fbfff

hi Conditional guifg=#f07178
hi Repeat guifg=#f07178
hi Label guifg=#f07178
hi Operator guifg=#c7c7c7
hi Keyword guifg=#f07178
hi Exception guifg=#f06b73

hi Include guifg=#d2a6ff
hi Define guifg=#d2a6ff
hi Macro guifg=#d2a6ff
hi PreCondit guifg=#d2a6ff

hi StorageClass guifg=#aad94c
hi Structure guifg=#aad94c
hi Typedef guifg=#aad94c

hi SpecialChar guifg=#95e6cb
hi Tag guifg=#95e6cb
hi Delimiter guifg=#c7c7c7
hi SpecialComment guifg=#686868
hi Debug guifg=#ffb454

hi Ignore guifg=#1a1510

" Cursor and line highlighting
hi Cursor guifg=#1a1510 guibg=#f5c56e
hi CursorLine guibg=#33393a
hi CursorColumn guibg=#33393a

" Visual selection
hi Visual guibg=#33393a

" Search highlighting
hi Search guibg=#ffb454 guifg=#1a1510
hi IncSearch guibg=#ffb454 guifg=#1a1510

" Line numbers
hi LineNr guifg=#686868
hi CursorLineNr guifg=#bfbdb6

" Status line
hi StatusLine guifg=#bfbdb6 guibg=#686868
hi StatusLineNC guifg=#686868 guibg=#1a1510

" Tab line
hi TabLine guifg=#686868 guibg=#1a1510
hi TabLineSel guifg=#bfbdb6 guibg=#33393a
hi TabLineFill guibg=#1a1510

" Popup menu
hi Pmenu guifg=#bfbdb6 guibg=#686868
hi PmenuSel guifg=#1a1510 guibg=#33393a
hi PmenuSbar guibg=#686868
hi PmenuThumb guibg=#bfbdb6

" Diff highlighting
hi DiffAdd guibg=#70bf56
hi DiffChange guibg=#fdb04c
hi DiffDelete guibg=#f06b73
hi DiffText guibg=#4fbfff

" Fold highlighting
hi Folded guifg=#686868 guibg=#1a1510
hi FoldColumn guifg=#686868 guibg=#1a1510

" Spell checking
hi SpellBad gui=undercurl guisp=#f06b73
hi SpellCap gui=undercurl guisp=#4fbfff
hi SpellRare gui=undercurl guisp=#d0a1ff
hi SpellLocal gui=undercurl guisp=#93e2c8

" Error and warning messages
hi ErrorMsg guifg=#f06b73
hi WarningMsg guifg=#fdb04c
hi MoreMsg guifg=#4fbfff
hi Question guifg=#70bf56

" Mode message
hi ModeMsg guifg=#70bf56

" Directory
hi Directory guifg=#4fbfff

" Title
hi Title guifg=#d0a1ff

" Match parenthesis
hi MatchParen guibg=#686868

" Sign column
hi SignColumn guifg=#686868 guibg=#1a1510
