" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: Witching Hour
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Witching-Hour"

" Normal colors
hi Normal guifg=#f5edff guibg=#261044

" Syntax highlighting groups
hi Comment guifg=#cec3dc
hi Constant guifg=#e9c86b
hi Identifier guifg=#91c4ed
hi Statement guifg=#f5a6b4
hi PreProc guifg=#d9b1f5
hi Type guifg=#bae187
hi Special guifg=#a0e1df
hi Underlined guifg=#add5f3 gui=underline
hi Error guifg=#f18a9d guibg=#261044
hi Todo guifg=#f1d98a guibg=#261044

" Additional groups for better compatibility
hi String guifg=#a4d66e
hi Character guifg=#a4d66e
hi Number guifg=#e9c86b
hi Boolean guifg=#e9c86b
hi Float guifg=#e9c86b

hi Function guifg=#91c4ed

hi Conditional guifg=#f5a6b4
hi Repeat guifg=#f5a6b4
hi Label guifg=#f5a6b4
hi Operator guifg=#f5edff
hi Keyword guifg=#f5a6b4
hi Exception guifg=#f18a9d

hi Include guifg=#d9b1f5
hi Define guifg=#d9b1f5
hi Macro guifg=#d9b1f5
hi PreCondit guifg=#d9b1f5

hi StorageClass guifg=#bae187
hi Structure guifg=#bae187
hi Typedef guifg=#bae187

hi SpecialChar guifg=#a0e1df
hi Tag guifg=#a0e1df
hi Delimiter guifg=#f5edff
hi SpecialComment guifg=#cec3dc
hi Debug guifg=#f1d98a

hi Ignore guifg=#261044

" Cursor and line highlighting
hi Cursor guifg=#261044 guibg=#b56cff
hi CursorLine guibg=#45236b
hi CursorColumn guibg=#45236b

" Visual selection
hi Visual guibg=#45236b

" Search highlighting
hi Search guibg=#f1d98a guifg=#261044
hi IncSearch guibg=#f1d98a guifg=#261044

" Line numbers
hi LineNr guifg=#cec3dc
hi CursorLineNr guifg=#f5edff

" Status line
hi StatusLine guifg=#f5edff guibg=#cec3dc
hi StatusLineNC guifg=#cec3dc guibg=#261044

" Tab line
hi TabLine guifg=#cec3dc guibg=#261044
hi TabLineSel guifg=#f5edff guibg=#45236b
hi TabLineFill guibg=#261044

" Popup menu
hi Pmenu guifg=#f5edff guibg=#cec3dc
hi PmenuSel guifg=#261044 guibg=#45236b
hi PmenuSbar guibg=#cec3dc
hi PmenuThumb guibg=#f5edff

" Diff highlighting
hi DiffAdd guibg=#a4d66e
hi DiffChange guibg=#e9c86b
hi DiffDelete guibg=#f18a9d
hi DiffText guibg=#91c4ed

" Fold highlighting
hi Folded guifg=#cec3dc guibg=#261044
hi FoldColumn guifg=#cec3dc guibg=#261044

" Spell checking
hi SpellBad gui=undercurl guisp=#f18a9d
hi SpellCap gui=undercurl guisp=#91c4ed
hi SpellRare gui=undercurl guisp=#c995f0
hi SpellLocal gui=undercurl guisp=#80d4d2

" Error and warning messages
hi ErrorMsg guifg=#f18a9d
hi WarningMsg guifg=#e9c86b
hi MoreMsg guifg=#91c4ed
hi Question guifg=#a4d66e

" Mode message
hi ModeMsg guifg=#a4d66e

" Directory
hi Directory guifg=#91c4ed

" Title
hi Title guifg=#c995f0

" Match parenthesis
hi MatchParen guibg=#cec3dc

" Sign column
hi SignColumn guifg=#cec3dc guibg=#261044
