" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: X Bogota
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "X-Bogota"

" Normal colors
hi Normal guifg=#f7f1ff guibg=#200b0a

" Syntax highlighting groups
hi Comment guifg=#525053
hi Constant guifg=#ffed89
hi Identifier guifg=#47e6ff
hi Statement guifg=#fc618d
hi PreProc guifg=#ff9999
hi Type guifg=#7bd88f
hi Special guifg=#47e6ff
hi Underlined guifg=#47e6ff gui=underline
hi Error guifg=#fc618d guibg=#200b0a
hi Todo guifg=#ffed89 guibg=#200b0a

" Additional groups for better compatibility
hi String guifg=#7bd88f
hi Character guifg=#7bd88f
hi Number guifg=#ffed89
hi Boolean guifg=#ffed89
hi Float guifg=#ffed89

hi Function guifg=#47e6ff

hi Conditional guifg=#fc618d
hi Repeat guifg=#fc618d
hi Label guifg=#fc618d
hi Operator guifg=#f7f1ff
hi Keyword guifg=#fc618d
hi Exception guifg=#fc618d

hi Include guifg=#ff9999
hi Define guifg=#ff9999
hi Macro guifg=#ff9999
hi PreCondit guifg=#ff9999

hi StorageClass guifg=#7bd88f
hi Structure guifg=#7bd88f
hi Typedef guifg=#7bd88f

hi SpecialChar guifg=#47e6ff
hi Tag guifg=#47e6ff
hi Delimiter guifg=#f7f1ff
hi SpecialComment guifg=#525053
hi Debug guifg=#ffed89

hi Ignore guifg=#200b0a

" Cursor and line highlighting
hi Cursor guifg=#200b0a guibg=#f7f1ff
hi CursorLine guibg=#f7f1ff
hi CursorColumn guibg=#f7f1ff

" Visual selection
hi Visual guibg=#f7f1ff

" Search highlighting
hi Search guibg=#ffed89 guifg=#200b0a
hi IncSearch guibg=#ffed89 guifg=#200b0a

" Line numbers
hi LineNr guifg=#525053
hi CursorLineNr guifg=#f7f1ff

" Status line
hi StatusLine guifg=#f7f1ff guibg=#525053
hi StatusLineNC guifg=#525053 guibg=#200b0a

" Tab line
hi TabLine guifg=#525053 guibg=#200b0a
hi TabLineSel guifg=#f7f1ff guibg=#f7f1ff
hi TabLineFill guibg=#200b0a

" Popup menu
hi Pmenu guifg=#f7f1ff guibg=#525053
hi PmenuSel guifg=#200b0a guibg=#f7f1ff
hi PmenuSbar guibg=#525053
hi PmenuThumb guibg=#f7f1ff

" Diff highlighting
hi DiffAdd guibg=#7bd88f
hi DiffChange guibg=#ffed89
hi DiffDelete guibg=#fc618d
hi DiffText guibg=#47e6ff

" Fold highlighting
hi Folded guifg=#525053 guibg=#200b0a
hi FoldColumn guifg=#525053 guibg=#200b0a

" Spell checking
hi SpellBad gui=undercurl guisp=#fc618d
hi SpellCap gui=undercurl guisp=#47e6ff
hi SpellRare gui=undercurl guisp=#ff9999
hi SpellLocal gui=undercurl guisp=#47e6ff

" Error and warning messages
hi ErrorMsg guifg=#fc618d
hi WarningMsg guifg=#ffed89
hi MoreMsg guifg=#47e6ff
hi Question guifg=#7bd88f

" Mode message
hi ModeMsg guifg=#7bd88f

" Directory
hi Directory guifg=#47e6ff

" Title
hi Title guifg=#ff9999

" Match parenthesis
hi MatchParen guibg=#525053

" Sign column
hi SignColumn guifg=#525053 guibg=#200b0a
