" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: X Lahabana
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "X-Lahabana"

" Normal colors
hi Normal guifg=#f7f1ff guibg=#19191a

" Syntax highlighting groups
hi Comment guifg=#4c4c4d
hi Constant guifg=#e5ff9d
hi Identifier guifg=#fd9353
hi Statement guifg=#fc618d
hi PreProc guifg=#948ae3
hi Type guifg=#7bd88f
hi Special guifg=#5ad4e6
hi Underlined guifg=#fd9353 gui=underline
hi Error guifg=#fc618d guibg=#19191a
hi Todo guifg=#e5ff9d guibg=#19191a

" Additional groups for better compatibility
hi String guifg=#7bd88f
hi Character guifg=#7bd88f
hi Number guifg=#e5ff9d
hi Boolean guifg=#e5ff9d
hi Float guifg=#e5ff9d

hi Function guifg=#fd9353

hi Conditional guifg=#fc618d
hi Repeat guifg=#fc618d
hi Label guifg=#fc618d
hi Operator guifg=#f7f1ff
hi Keyword guifg=#fc618d
hi Exception guifg=#fc618d

hi Include guifg=#948ae3
hi Define guifg=#948ae3
hi Macro guifg=#948ae3
hi PreCondit guifg=#948ae3

hi StorageClass guifg=#7bd88f
hi Structure guifg=#7bd88f
hi Typedef guifg=#7bd88f

hi SpecialChar guifg=#5ad4e6
hi Tag guifg=#5ad4e6
hi Delimiter guifg=#f7f1ff
hi SpecialComment guifg=#4c4c4d
hi Debug guifg=#e5ff9d

hi Ignore guifg=#19191a

" Cursor and line highlighting
hi Cursor guifg=#19191a guibg=#f7f1ff
hi CursorLine guibg=#f7f1ff
hi CursorColumn guibg=#f7f1ff

" Visual selection
hi Visual guibg=#f7f1ff

" Search highlighting
hi Search guibg=#e5ff9d guifg=#19191a
hi IncSearch guibg=#e5ff9d guifg=#19191a

" Line numbers
hi LineNr guifg=#4c4c4d
hi CursorLineNr guifg=#f7f1ff

" Status line
hi StatusLine guifg=#f7f1ff guibg=#4c4c4d
hi StatusLineNC guifg=#4c4c4d guibg=#19191a

" Tab line
hi TabLine guifg=#4c4c4d guibg=#19191a
hi TabLineSel guifg=#f7f1ff guibg=#f7f1ff
hi TabLineFill guibg=#19191a

" Popup menu
hi Pmenu guifg=#f7f1ff guibg=#4c4c4d
hi PmenuSel guifg=#19191a guibg=#f7f1ff
hi PmenuSbar guibg=#4c4c4d
hi PmenuThumb guibg=#f7f1ff

" Diff highlighting
hi DiffAdd guibg=#7bd88f
hi DiffChange guibg=#e5ff9d
hi DiffDelete guibg=#fc618d
hi DiffText guibg=#fd9353

" Fold highlighting
hi Folded guifg=#4c4c4d guibg=#19191a
hi FoldColumn guifg=#4c4c4d guibg=#19191a

" Spell checking
hi SpellBad gui=undercurl guisp=#fc618d
hi SpellCap gui=undercurl guisp=#fd9353
hi SpellRare gui=undercurl guisp=#948ae3
hi SpellLocal gui=undercurl guisp=#5ad4e6

" Error and warning messages
hi ErrorMsg guifg=#fc618d
hi WarningMsg guifg=#e5ff9d
hi MoreMsg guifg=#fd9353
hi Question guifg=#7bd88f

" Mode message
hi ModeMsg guifg=#7bd88f

" Directory
hi Directory guifg=#fd9353

" Title
hi Title guifg=#948ae3

" Match parenthesis
hi MatchParen guibg=#4c4c4d

" Sign column
hi SignColumn guifg=#4c4c4d guibg=#19191a
