" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: X Miami
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "X-Miami"

" Normal colors
hi Normal guifg=#f7f1ff guibg=#000000

" Syntax highlighting groups
hi Comment guifg=#69676c
hi Constant guifg=#ffd84c
hi Identifier guifg=#00ffa8
hi Statement guifg=#ff4c8b
hi PreProc guifg=#d36cff
hi Type guifg=#7fffd4
hi Special guifg=#47cfff
hi Underlined guifg=#00ffa8 gui=underline
hi Error guifg=#ff4c8b guibg=#000000
hi Todo guifg=#ffd84c guibg=#000000

" Additional groups for better compatibility
hi String guifg=#7fffd4
hi Character guifg=#7fffd4
hi Number guifg=#ffd84c
hi Boolean guifg=#ffd84c
hi Float guifg=#ffd84c

hi Function guifg=#00ffa8

hi Conditional guifg=#ff4c8b
hi Repeat guifg=#ff4c8b
hi Label guifg=#ff4c8b
hi Operator guifg=#f7f1ff
hi Keyword guifg=#ff4c8b
hi Exception guifg=#ff4c8b

hi Include guifg=#d36cff
hi Define guifg=#d36cff
hi Macro guifg=#d36cff
hi PreCondit guifg=#d36cff

hi StorageClass guifg=#7fffd4
hi Structure guifg=#7fffd4
hi Typedef guifg=#7fffd4

hi SpecialChar guifg=#47cfff
hi Tag guifg=#47cfff
hi Delimiter guifg=#f7f1ff
hi SpecialComment guifg=#69676c
hi Debug guifg=#ffd84c

hi Ignore guifg=#000000

" Cursor and line highlighting
hi Cursor guifg=#000000 guibg=#f7f1ff
hi CursorLine guibg=#f7f1ff
hi CursorColumn guibg=#f7f1ff

" Visual selection
hi Visual guibg=#f7f1ff

" Search highlighting
hi Search guibg=#ffd84c guifg=#000000
hi IncSearch guibg=#ffd84c guifg=#000000

" Line numbers
hi LineNr guifg=#69676c
hi CursorLineNr guifg=#f7f1ff

" Status line
hi StatusLine guifg=#f7f1ff guibg=#69676c
hi StatusLineNC guifg=#69676c guibg=#000000

" Tab line
hi TabLine guifg=#69676c guibg=#000000
hi TabLineSel guifg=#f7f1ff guibg=#f7f1ff
hi TabLineFill guibg=#000000

" Popup menu
hi Pmenu guifg=#f7f1ff guibg=#69676c
hi PmenuSel guifg=#000000 guibg=#f7f1ff
hi PmenuSbar guibg=#69676c
hi PmenuThumb guibg=#f7f1ff

" Diff highlighting
hi DiffAdd guibg=#7fffd4
hi DiffChange guibg=#ffd84c
hi DiffDelete guibg=#ff4c8b
hi DiffText guibg=#00ffa8

" Fold highlighting
hi Folded guifg=#69676c guibg=#000000
hi FoldColumn guifg=#69676c guibg=#000000

" Spell checking
hi SpellBad gui=undercurl guisp=#ff4c8b
hi SpellCap gui=undercurl guisp=#00ffa8
hi SpellRare gui=undercurl guisp=#d36cff
hi SpellLocal gui=undercurl guisp=#47cfff

" Error and warning messages
hi ErrorMsg guifg=#ff4c8b
hi WarningMsg guifg=#ffd84c
hi MoreMsg guifg=#00ffa8
hi Question guifg=#7fffd4

" Mode message
hi ModeMsg guifg=#7fffd4

" Directory
hi Directory guifg=#00ffa8

" Title
hi Title guifg=#d36cff

" Match parenthesis
hi MatchParen guibg=#69676c

" Sign column
hi SignColumn guifg=#69676c guibg=#000000
