" Vim Color File
" Generated by iTerm2-Color-Schemes
" Name: X Paris
" URL: https://github.com/mbadolato/iTerm2-Color-Schemes

hi clear
if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "X-Paris"

" Normal colors
hi Normal guifg=#f7f1ff guibg=#1a0a30

" Syntax highlighting groups
hi Comment guifg=#c4bdff
hi Constant guifg=#fce566
hi Identifier guifg=#a3f3ff
hi Statement guifg=#fc618d
hi PreProc guifg=#c4bdff
hi Type guifg=#7bd88f
hi Special guifg=#a3f3ff
hi Underlined guifg=#a3f3ff gui=underline
hi Error guifg=#fc618d guibg=#1a0a30
hi Todo guifg=#fce566 guibg=#1a0a30

" Additional groups for better compatibility
hi String guifg=#7bd88f
hi Character guifg=#7bd88f
hi Number guifg=#fce566
hi Boolean guifg=#fce566
hi Float guifg=#fce566

hi Function guifg=#a3f3ff

hi Conditional guifg=#fc618d
hi Repeat guifg=#fc618d
hi Label guifg=#fc618d
hi Operator guifg=#4d3d63
hi Keyword guifg=#fc618d
hi Exception guifg=#fc618d

hi Include guifg=#c4bdff
hi Define guifg=#c4bdff
hi Macro guifg=#c4bdff
hi PreCondit guifg=#c4bdff

hi StorageClass guifg=#7bd88f
hi Structure guifg=#7bd88f
hi Typedef guifg=#7bd88f

hi SpecialChar guifg=#a3f3ff
hi Tag guifg=#a3f3ff
hi Delimiter guifg=#4d3d63
hi SpecialComment guifg=#c4bdff
hi Debug guifg=#fce566

hi Ignore guifg=#1a0a30

" Cursor and line highlighting
hi Cursor guifg=#1a0a30 guibg=#f7f1ff
hi CursorLine guibg=#f7f1ff
hi CursorColumn guibg=#f7f1ff

" Visual selection
hi Visual guibg=#f7f1ff

" Search highlighting
hi Search guibg=#fce566 guifg=#1a0a30
hi IncSearch guibg=#fce566 guifg=#1a0a30

" Line numbers
hi LineNr guifg=#c4bdff
hi CursorLineNr guifg=#f7f1ff

" Status line
hi StatusLine guifg=#f7f1ff guibg=#c4bdff
hi StatusLineNC guifg=#c4bdff guibg=#1a0a30

" Tab line
hi TabLine guifg=#c4bdff guibg=#1a0a30
hi TabLineSel guifg=#f7f1ff guibg=#f7f1ff
hi TabLineFill guibg=#1a0a30

" Popup menu
hi Pmenu guifg=#f7f1ff guibg=#c4bdff
hi PmenuSel guifg=#1a0a30 guibg=#f7f1ff
hi PmenuSbar guibg=#c4bdff
hi PmenuThumb guibg=#f7f1ff

" Diff highlighting
hi DiffAdd guibg=#7bd88f
hi DiffChange guibg=#fce566
hi DiffDelete guibg=#fc618d
hi DiffText guibg=#a3f3ff

" Fold highlighting
hi Folded guifg=#c4bdff guibg=#1a0a30
hi FoldColumn guifg=#c4bdff guibg=#1a0a30

" Spell checking
hi SpellBad gui=undercurl guisp=#fc618d
hi SpellCap gui=undercurl guisp=#a3f3ff
hi SpellRare gui=undercurl guisp=#c4bdff
hi SpellLocal gui=undercurl guisp=#a3f3ff

" Error and warning messages
hi ErrorMsg guifg=#fc618d
hi WarningMsg guifg=#fce566
hi MoreMsg guifg=#a3f3ff
hi Question guifg=#7bd88f

" Mode message
hi ModeMsg guifg=#7bd88f

" Directory
hi Directory guifg=#a3f3ff

" Title
hi Title guifg=#c4bdff

" Match parenthesis
hi MatchParen guibg=#c4bdff

" Sign column
hi SignColumn guifg=#c4bdff guibg=#1a0a30
