# Aztec Sunset
kern.vt.color.0.rgb="#a9a19f"
kern.vt.color.1.rgb="#f47c62"
kern.vt.color.2.rgb="#67c894"
kern.vt.color.3.rgb="#e9bd59"
kern.vt.color.4.rgb="#72c6c2"
kern.vt.color.5.rgb="#e778a8"
kern.vt.color.6.rgb="#65d5d0"
kern.vt.color.7.rgb="#ffe6c7"
kern.vt.color.8.rgb="#c0b4b0"
kern.vt.color.9.rgb="#ff986d"
kern.vt.color.10.rgb="#86d7a8"
kern.vt.color.11.rgb="#ffd071"
kern.vt.color.12.rgb="#8bd8d2"
kern.vt.color.13.rgb="#f194bd"
kern.vt.color.14.rgb="#89e2dc"
kern.vt.color.15.rgb="#fff4df"
