# Belfry
kern.vt.color.0.rgb="#bcaeb0"
kern.vt.color.1.rgb="#f1817b"
kern.vt.color.2.rgb="#9dcc91"
kern.vt.color.3.rgb="#e7c56d"
kern.vt.color.4.rgb="#91bfe0"
kern.vt.color.5.rgb="#d29ac0"
kern.vt.color.6.rgb="#82cbc7"
kern.vt.color.7.rgb="#fff0dc"
kern.vt.color.8.rgb="#d0c3c5"
kern.vt.color.9.rgb="#f59c96"
kern.vt.color.10.rgb="#b2d8a7"
kern.vt.color.11.rgb="#efd58b"
kern.vt.color.12.rgb="#accfe8"
kern.vt.color.13.rgb="#dfb3cf"
kern.vt.color.14.rgb="#a1d9d5"
kern.vt.color.15.rgb="#fffaf0"
