# Cursor Light
kern.vt.color.0.rgb="#252525"
kern.vt.color.1.rgb="#cf2d56"
kern.vt.color.2.rgb="#1f8a65"
kern.vt.color.3.rgb="#a16900"
kern.vt.color.4.rgb="#3c7cab"
kern.vt.color.5.rgb="#b8448b"
kern.vt.color.6.rgb="#4c7f8c"
kern.vt.color.7.rgb="#252525"
kern.vt.color.8.rgb="#5c5c5c"
kern.vt.color.9.rgb="#e75e78"
kern.vt.color.10.rgb="#55a583"
kern.vt.color.11.rgb="#c08532"
kern.vt.color.12.rgb="#6299c3"
kern.vt.color.13.rgb="#d06ba6"
kern.vt.color.14.rgb="#6f9ba6"
kern.vt.color.15.rgb="#ffffff"
