# datum (dark)
kern.vt.color.0.rgb="#2b2f35"
kern.vt.color.1.rgb="#fe9864"
kern.vt.color.2.rgb="#54dcaa"
kern.vt.color.3.rgb="#e8df69"
kern.vt.color.4.rgb="#69b9f7"
kern.vt.color.5.rgb="#fa94cd"
kern.vt.color.6.rgb="#6ae5ec"
kern.vt.color.7.rgb="#dbe0e8"
kern.vt.color.8.rgb="#8f98a3"
kern.vt.color.9.rgb="#f8bd5f"
kern.vt.color.10.rgb="#54dcaa"
kern.vt.color.11.rgb="#fcdcad"
kern.vt.color.12.rgb="#b2dafb"
kern.vt.color.13.rgb="#f5b9d9"
kern.vt.color.14.rgb="#a5f5f9"
kern.vt.color.15.rgb="#eef2f7"
