# Desert Rose
kern.vt.color.0.rgb="#c9b9b8"
kern.vt.color.1.rgb="#ff978b"
kern.vt.color.2.rgb="#94d1a1"
kern.vt.color.3.rgb="#edc96d"
kern.vt.color.4.rgb="#8fc4e8"
kern.vt.color.5.rgb="#dfa2c9"
kern.vt.color.6.rgb="#82d7d2"
kern.vt.color.7.rgb="#fff0df"
kern.vt.color.8.rgb="#dacbca"
kern.vt.color.9.rgb="#ffaea3"
kern.vt.color.10.rgb="#a9dcaf"
kern.vt.color.11.rgb="#f8d98b"
kern.vt.color.12.rgb="#acd4ef"
kern.vt.color.13.rgb="#e9bad7"
kern.vt.color.14.rgb="#a2e4df"
kern.vt.color.15.rgb="#fffaf2"
