# Electron Highlighter Day
kern.vt.color.0.rgb="#c2c6d4"
kern.vt.color.1.rgb="#f52a65"
kern.vt.color.2.rgb="#10a877"
kern.vt.color.3.rgb="#df8e1d"
kern.vt.color.4.rgb="#366ff0"
kern.vt.color.5.rgb="#8b4fe0"
kern.vt.color.6.rgb="#0a9fbf"
kern.vt.color.7.rgb="#2f3b54"
kern.vt.color.8.rgb="#7b88a8"
kern.vt.color.9.rgb="#f52a65"
kern.vt.color.10.rgb="#10a877"
kern.vt.color.11.rgb="#df8e1d"
kern.vt.color.12.rgb="#366ff0"
kern.vt.color.13.rgb="#8b4fe0"
kern.vt.color.14.rgb="#0a9fbf"
kern.vt.color.15.rgb="#2f3b54"
