# EVH FrankenTone
kern.vt.color.0.rgb="#e7d8d0"
kern.vt.color.1.rgb="#ffb4a5"
kern.vt.color.2.rgb="#e6d27e"
kern.vt.color.3.rgb="#f4d45d"
kern.vt.color.4.rgb="#a9cbe7"
kern.vt.color.5.rgb="#d9c3c9"
kern.vt.color.6.rgb="#a7d7d7"
kern.vt.color.7.rgb="#f7ede5"
kern.vt.color.8.rgb="#c9b8b1"
kern.vt.color.9.rgb="#ffd0bf"
kern.vt.color.10.rgb="#f2e4a0"
kern.vt.color.11.rgb="#ffe27d"
kern.vt.color.12.rgb="#c5ddf3"
kern.vt.color.13.rgb="#f0d8de"
kern.vt.color.14.rgb="#c4e9e8"
kern.vt.color.15.rgb="#ffffff"
