# Frostline
kern.vt.color.0.rgb="#29394a"
kern.vt.color.1.rgb="#812121"
kern.vt.color.2.rgb="#0b5934"
kern.vt.color.3.rgb="#654a00"
kern.vt.color.4.rgb="#164891"
kern.vt.color.5.rgb="#5c3189"
kern.vt.color.6.rgb="#00596a"
kern.vt.color.7.rgb="#102a43"
kern.vt.color.8.rgb="#536273"
kern.vt.color.9.rgb="#8d2727"
kern.vt.color.10.rgb="#0e603a"
kern.vt.color.11.rgb="#6c5000"
kern.vt.color.12.rgb="#194f9d"
kern.vt.color.13.rgb="#653991"
kern.vt.color.14.rgb="#006173"
kern.vt.color.15.rgb="#455565"
