# Harvest Moon
kern.vt.color.0.rgb="#b8c2c6"
kern.vt.color.1.rgb="#ee997d"
kern.vt.color.2.rgb="#9bca8e"
kern.vt.color.3.rgb="#edc667"
kern.vt.color.4.rgb="#8fc1dd"
kern.vt.color.5.rgb="#c7a1c8"
kern.vt.color.6.rgb="#80ced0"
kern.vt.color.7.rgb="#fff1d2"
kern.vt.color.8.rgb="#cbd3d6"
kern.vt.color.9.rgb="#f2ae92"
kern.vt.color.10.rgb="#b0d6a4"
kern.vt.color.11.rgb="#f4d585"
kern.vt.color.12.rgb="#aad1e7"
kern.vt.color.13.rgb="#d4b8d5"
kern.vt.color.14.rgb="#9edbdc"
kern.vt.color.15.rgb="#fff9e8"
