# Hellfire
kern.vt.color.0.rgb="#c5afa7"
kern.vt.color.1.rgb="#f2815f"
kern.vt.color.2.rgb="#a9bd72"
kern.vt.color.3.rgb="#e8bd4e"
kern.vt.color.4.rgb="#83a9c2"
kern.vt.color.5.rgb="#bf879f"
kern.vt.color.6.rgb="#76b6ad"
kern.vt.color.7.rgb="#f8e2c7"
kern.vt.color.8.rgb="#ccb9b2"
kern.vt.color.9.rgb="#f49072"
kern.vt.color.10.rgb="#b3c583"
kern.vt.color.11.rgb="#ebc563"
kern.vt.color.12.rgb="#92b3c9"
kern.vt.color.13.rgb="#c795ab"
kern.vt.color.14.rgb="#86bfb7"
kern.vt.color.15.rgb="#f9e5ce"
