# Hocus Pocus
kern.vt.color.0.rgb="#c2b1ca"
kern.vt.color.1.rgb="#f18b8c"
kern.vt.color.2.rgb="#9bd674"
kern.vt.color.3.rgb="#e9c657"
kern.vt.color.4.rgb="#8fc1e8"
kern.vt.color.5.rgb="#d187e4"
kern.vt.color.6.rgb="#7bd3d1"
kern.vt.color.7.rgb="#f6edff"
kern.vt.color.8.rgb="#c9bad0"
kern.vt.color.9.rgb="#f3999a"
kern.vt.color.10.rgb="#a7db85"
kern.vt.color.11.rgb="#eccd6b"
kern.vt.color.12.rgb="#9cc8eb"
kern.vt.color.13.rgb="#d795e7"
kern.vt.color.14.rgb="#8bd8d7"
kern.vt.color.15.rgb="#f7efff"
