# Icy Glacier
kern.vt.color.0.rgb="#263548"
kern.vt.color.1.rgb="#8f2424"
kern.vt.color.2.rgb="#17613c"
kern.vt.color.3.rgb="#6e5500"
kern.vt.color.4.rgb="#174c9b"
kern.vt.color.5.rgb="#64379a"
kern.vt.color.6.rgb="#006275"
kern.vt.color.7.rgb="#0f172a"
kern.vt.color.8.rgb="#536171"
kern.vt.color.9.rgb="#741a1a"
kern.vt.color.10.rgb="#1b6945"
kern.vt.color.11.rgb="#765d00"
kern.vt.color.12.rgb="#123b78"
kern.vt.color.13.rgb="#503075"
kern.vt.color.14.rgb="#006b80"
kern.vt.color.15.rgb="#455365"
