# Jute Espresso
kern.vt.color.0.rgb="#e0c7ab"
kern.vt.color.1.rgb="#ffc0a1"
kern.vt.color.2.rgb="#c4ddad"
kern.vt.color.3.rgb="#fbd18a"
kern.vt.color.4.rgb="#a9cbea"
kern.vt.color.5.rgb="#d8b9dc"
kern.vt.color.6.rgb="#a9ded6"
kern.vt.color.7.rgb="#fff0d7"
kern.vt.color.8.rgb="#efd9c1"
kern.vt.color.9.rgb="#ffd1b3"
kern.vt.color.10.rgb="#d5e9c1"
kern.vt.color.11.rgb="#ffe0a4"
kern.vt.color.12.rgb="#c2ddf7"
kern.vt.color.13.rgb="#e9cdea"
kern.vt.color.14.rgb="#c2ece3"
kern.vt.color.15.rgb="#fff9e9"
