# Karasu Snow
kern.vt.color.0.rgb="#0a0a0a"
kern.vt.color.1.rgb="#b84755"
kern.vt.color.2.rgb="#3f7e4a"
kern.vt.color.3.rgb="#8a6a1f"
kern.vt.color.4.rgb="#2e5e9b"
kern.vt.color.5.rgb="#6c4bb8"
kern.vt.color.6.rgb="#2d7e7a"
kern.vt.color.7.rgb="#292524"
kern.vt.color.8.rgb="#404040"
kern.vt.color.9.rgb="#d93c3c"
kern.vt.color.10.rgb="#2f9150"
kern.vt.color.11.rgb="#9a7a1d"
kern.vt.color.12.rgb="#2b72c7"
kern.vt.color.13.rgb="#7b59d6"
kern.vt.color.14.rgb="#1f968f"
kern.vt.color.15.rgb="#ffffff"
