# Karma Light
kern.vt.color.0.rgb="#0a0e14"
kern.vt.color.1.rgb="#fc618d"
kern.vt.color.2.rgb="#2d972f"
kern.vt.color.3.rgb="#eeae11"
kern.vt.color.4.rgb="#5688c7"
kern.vt.color.5.rgb="#6f42c1"
kern.vt.color.6.rgb="#5688c7"
kern.vt.color.7.rgb="#0a0e14"
kern.vt.color.8.rgb="#999999"
kern.vt.color.9.rgb="#fc618d"
kern.vt.color.10.rgb="#2d972f"
kern.vt.color.11.rgb="#ffaa33"
kern.vt.color.12.rgb="#5688c7"
kern.vt.color.13.rgb="#a86efd"
kern.vt.color.14.rgb="#5688c7"
kern.vt.color.15.rgb="#0a0e14"
