# Klein Void
kern.vt.color.0.rgb="#1a1c24"
kern.vt.color.1.rgb="#f09890"
kern.vt.color.2.rgb="#a6c080"
kern.vt.color.3.rgb="#e8bc75"
kern.vt.color.4.rgb="#002fa7"
kern.vt.color.5.rgb="#d49bb5"
kern.vt.color.6.rgb="#9fc0e5"
kern.vt.color.7.rgb="#ede6d3"
kern.vt.color.8.rgb="#92907a"
kern.vt.color.9.rgb="#d97757"
kern.vt.color.10.rgb="#bcc89c"
kern.vt.color.11.rgb="#f0c880"
kern.vt.color.12.rgb="#a8bef0"
kern.vt.color.13.rgb="#c8b4d4"
kern.vt.color.14.rgb="#b0d0ed"
kern.vt.color.15.rgb="#f5efde"
