# Moonwire
kern.vt.color.0.rgb="#07101f"
kern.vt.color.1.rgb="#ff5470"
kern.vt.color.2.rgb="#62e6a7"
kern.vt.color.3.rgb="#dfff3f"
kern.vt.color.4.rgb="#4e9dff"
kern.vt.color.5.rgb="#b68cff"
kern.vt.color.6.rgb="#42d9f5"
kern.vt.color.7.rgb="#f6fbff"
kern.vt.color.8.rgb="#a3b8ce"
kern.vt.color.9.rgb="#ff7b91"
kern.vt.color.10.rgb="#8af0c1"
kern.vt.color.11.rgb="#edff7a"
kern.vt.color.12.rgb="#78b8ff"
kern.vt.color.13.rgb="#d2b1ff"
kern.vt.color.14.rgb="#79ecff"
kern.vt.color.15.rgb="#ffffff"
