# Moonwalk
kern.vt.color.0.rgb="#080808"
kern.vt.color.1.rgb="#7a0047"
kern.vt.color.2.rgb="#145b0e"
kern.vt.color.3.rgb="#733a11"
kern.vt.color.4.rgb="#002fa7"
kern.vt.color.5.rgb="#5400a8"
kern.vt.color.6.rgb="#00566b"
kern.vt.color.7.rgb="#061f4a"
kern.vt.color.8.rgb="#494440"
kern.vt.color.9.rgb="#af1608"
kern.vt.color.10.rgb="#4c6129"
kern.vt.color.11.rgb="#7a5000"
kern.vt.color.12.rgb="#0d50c5"
kern.vt.color.13.rgb="#952197"
kern.vt.color.14.rgb="#006092"
kern.vt.color.15.rgb="#ffffff"
