# Night Pharmacy
kern.vt.color.0.rgb="#afbeb5"
kern.vt.color.1.rgb="#ef8088"
kern.vt.color.2.rgb="#72d1a0"
kern.vt.color.3.rgb="#e6cb69"
kern.vt.color.4.rgb="#83b3e7"
kern.vt.color.5.rgb="#cba0df"
kern.vt.color.6.rgb="#72d3d0"
kern.vt.color.7.rgb="#ecf5ef"
kern.vt.color.8.rgb="#c4d0c9"
kern.vt.color.9.rgb="#f19ba1"
kern.vt.color.10.rgb="#91dfb7"
kern.vt.color.11.rgb="#eddb8b"
kern.vt.color.12.rgb="#a3c8ef"
kern.vt.color.13.rgb="#dabbe8"
kern.vt.color.14.rgb="#94e2df"
kern.vt.color.15.rgb="#ffffff"
