# Obsurdian
kern.vt.color.0.rgb="#b8b8b8"
kern.vt.color.1.rgb="#ff6b6b"
kern.vt.color.2.rgb="#66d98b"
kern.vt.color.3.rgb="#ffe37a"
kern.vt.color.4.rgb="#82aaff"
kern.vt.color.5.rgb="#ff8fd1"
kern.vt.color.6.rgb="#8be9f4"
kern.vt.color.7.rgb="#f5f5f5"
kern.vt.color.8.rgb="#c7c7c7"
kern.vt.color.9.rgb="#ff8585"
kern.vt.color.10.rgb="#82e6a0"
kern.vt.color.11.rgb="#ffeb96"
kern.vt.color.12.rgb="#9abaff"
kern.vt.color.13.rgb="#ffa8dc"
kern.vt.color.14.rgb="#a4f1f7"
kern.vt.color.15.rgb="#ffffff"
