# Patina Moss
kern.vt.color.0.rgb="#33362e"
kern.vt.color.1.rgb="#c07878"
kern.vt.color.2.rgb="#5ba886"
kern.vt.color.3.rgb="#d4bf6e"
kern.vt.color.4.rgb="#65a8b5"
kern.vt.color.5.rgb="#c08a7d"
kern.vt.color.6.rgb="#63a8a6"
kern.vt.color.7.rgb="#dbd7ca"
kern.vt.color.8.rgb="#585b51"
kern.vt.color.9.rgb="#c07878"
kern.vt.color.10.rgb="#5ba886"
kern.vt.color.11.rgb="#d4bf6e"
kern.vt.color.12.rgb="#65a8b5"
kern.vt.color.13.rgb="#c08a7d"
kern.vt.color.14.rgb="#63a8a6"
kern.vt.color.15.rgb="#dbd7ca"
