# Petrified
kern.vt.color.0.rgb="#c7c0ba"
kern.vt.color.1.rgb="#ee9676"
kern.vt.color.2.rgb="#82c794"
kern.vt.color.3.rgb="#e5c05c"
kern.vt.color.4.rgb="#80bdd2"
kern.vt.color.5.rgb="#cc9fc1"
kern.vt.color.6.rgb="#75ccc7"
kern.vt.color.7.rgb="#fff0dc"
kern.vt.color.8.rgb="#d6d0ca"
kern.vt.color.9.rgb="#f4aa8d"
kern.vt.color.10.rgb="#9bd4a7"
kern.vt.color.11.rgb="#efd17d"
kern.vt.color.12.rgb="#9dcddd"
kern.vt.color.13.rgb="#dab6cf"
kern.vt.color.14.rgb="#94dad5"
kern.vt.color.15.rgb="#fff9ed"
