# Poltergeist
kern.vt.color.0.rgb="#c0d1d2"
kern.vt.color.1.rgb="#ff9c91"
kern.vt.color.2.rgb="#8ce0b0"
kern.vt.color.3.rgb="#e9d06c"
kern.vt.color.4.rgb="#8ed4ed"
kern.vt.color.5.rgb="#c5a7e8"
kern.vt.color.6.rgb="#77e1df"
kern.vt.color.7.rgb="#f0ffff"
kern.vt.color.8.rgb="#c8d7d7"
kern.vt.color.9.rgb="#ffa89e"
kern.vt.color.10.rgb="#9ae4b9"
kern.vt.color.11.rgb="#ecd67e"
kern.vt.color.12.rgb="#9cd9ef"
kern.vt.color.13.rgb="#ccb2eb"
kern.vt.color.14.rgb="#87e5e3"
kern.vt.color.15.rgb="#f2ffff"
