# Prism
kern.vt.color.0.rgb="#060c18"
kern.vt.color.1.rgb="#ff7192"
kern.vt.color.2.rgb="#71e0b0"
kern.vt.color.3.rgb="#fad77c"
kern.vt.color.4.rgb="#47b3ff"
kern.vt.color.5.rgb="#9da9ff"
kern.vt.color.6.rgb="#31dcf2"
kern.vt.color.7.rgb="#d7e3f4"
kern.vt.color.8.rgb="#5e6f90"
kern.vt.color.9.rgb="#ff96ad"
kern.vt.color.10.rgb="#93ecc7"
kern.vt.color.11.rgb="#fca76d"
kern.vt.color.12.rgb="#77caff"
kern.vt.color.13.rgb="#b8c1ff"
kern.vt.color.14.rgb="#6ceafb"
kern.vt.color.15.rgb="#eaf1fb"
