# Pumpkin Patch
kern.vt.color.0.rgb="#c3c8af"
kern.vt.color.1.rgb="#f09870"
kern.vt.color.2.rgb="#95ce77"
kern.vt.color.3.rgb="#e8c95a"
kern.vt.color.4.rgb="#87bfcf"
kern.vt.color.5.rgb="#c79ab7"
kern.vt.color.6.rgb="#79c9bb"
kern.vt.color.7.rgb="#f5efd1"
kern.vt.color.8.rgb="#cacfb9"
kern.vt.color.9.rgb="#f2a481"
kern.vt.color.10.rgb="#a2d487"
kern.vt.color.11.rgb="#ebcf6e"
kern.vt.color.12.rgb="#95c7d5"
kern.vt.color.13.rgb="#cea6c0"
kern.vt.color.14.rgb="#89cfc3"
kern.vt.color.15.rgb="#f6f1d7"
