# SilkCircuit Dawn
kern.vt.color.0.rgb="#2b2540"
kern.vt.color.1.rgb="#c1272d"
kern.vt.color.2.rgb="#1d6e46"
kern.vt.color.3.rgb="#796100"
kern.vt.color.4.rgb="#1454dc"
kern.vt.color.5.rgb="#b40077"
kern.vt.color.6.rgb="#006e72"
kern.vt.color.7.rgb="#2b2540"
kern.vt.color.8.rgb="#5a4d6e"
kern.vt.color.9.rgb="#dc2626"
kern.vt.color.10.rgb="#288855"
kern.vt.color.11.rgb="#7f5f00"
kern.vt.color.12.rgb="#2572ef"
kern.vt.color.13.rgb="#d92a99"
kern.vt.color.14.rgb="#048397"
kern.vt.color.15.rgb="#ffffff"
