# Y2K Chrome
kern.vt.color.0.rgb="#383f4f"
kern.vt.color.1.rgb="#dc2626"
kern.vt.color.2.rgb="#15803d"
kern.vt.color.3.rgb="#0891b2"
kern.vt.color.4.rgb="#f97316"
kern.vt.color.5.rgb="#7c3aed"
kern.vt.color.6.rgb="#2563eb"
kern.vt.color.7.rgb="#0f172a"
kern.vt.color.8.rgb="#a3b1c4"
kern.vt.color.9.rgb="#b01e1e"
kern.vt.color.10.rgb="#116631"
kern.vt.color.11.rgb="#077792"
kern.vt.color.12.rgb="#c75c12"
kern.vt.color.13.rgb="#632ebe"
kern.vt.color.14.rgb="#1e4fbc"
kern.vt.color.15.rgb="#0f172a"
