# Abandoned
foreground=#eee9d7
background=#433d2d
cursor=#e9a689

color0=#c2c0ae
color1=#e69a79
color2=#9db692
color3=#d7c06e
color4=#8eafb8
color5=#bda6b4
color6=#82bbb4
color7=#eee9d7

color8=#c9c8b8
color9=#e9a689
color10=#a9bf9f
color11=#dcc87f
color12=#9cb9c1
color13=#bea6b4
color14=#91c3bd
color15=#f0ecdc
