# Eclipse
foreground=#dce3ed
background=#0e1116
cursor=#f6c45f

color0=#0a0d12
color1=#ff6366
color2=#85df5e
color3=#f1c655
color4=#5fb9ff
color5=#cea5ff
color6=#3addc4
color7=#b7c0ce

color8=#5c6675
color9=#ff8688
color10=#a0ec7e
color11=#fad77c
color12=#84ccff
color13=#ddbfff
color14=#68ead3
color15=#f4f8fd
