# Graphite
foreground=#d2d6dc
background=#1c1e22
cursor=#c4cedb

color0=#15171a
color1=#e58888
color2=#a7c59f
color3=#cec59d
color4=#8db4d0
color5=#baabcb
color6=#a8c6d4
color7=#b4b9c0

color8=#7e8590
color9=#f19f9f
color10=#b9d5b1
color11=#cfba97
color12=#a5c6de
color13=#ccbedd
color14=#bcd6e2
color15=#eceff3
