# Last Broadcast
foreground=#f2efe8
background=#08090d
cursor=#ffca72

color0=#b7b5b0
color1=#ff806f
color2=#79d09e
color3=#efcb69
color4=#8bb4ed
color5=#d5a2e5
color6=#80d3da
color7=#f2efe8

color8=#cac7c1
color9=#ff9c8d
color10=#99ddb5
color11=#f6dc8b
color12=#aac9f3
color13=#e4bbed
color14=#a2e1e5
color15=#fffdf8
