# Patina Dark Soft
foreground=#dbd7ca
background=#1a1a1a
cursor=#dbd7ca

color0=#2e2e2e
color1=#cb7676
color2=#549c7d
color3=#e6cc77
color4=#6db3c2
color5=#c98a7d
color6=#5da9a7
color7=#dbd7ca

color8=#585858
color9=#cb7676
color10=#549c7d
color11=#e6cc77
color12=#6db3c2
color13=#c98a7d
color14=#5da9a7
color15=#dbd7ca
