

color_0 = ffff ffff ffff
color_1 = 0000 0000 0000
color_2 = 8888 8888 8888
color_3 = bbbb bbbb bbbb
color_4 = 9999 9999 9999
color_5 = dddd dddd dddd
color_6 = aaaa aaaa aaaa
color_7 = bbbb bbbb bbbb
color_8 = ffff ffff ffff
color_9 = dddd dddd dddd
color_10 = cccc cccc cccc
color_11 = eeee eeee eeee
color_12 = aaaa aaaa aaaa
color_13 = cccc cccc cccc
color_14 = 4040 4040 4040
color_15 = ffff ffff ffff
color_16 = ffff ffff ffff
color_17 = 0000 0000 0000
color_18 = 8888 8888 8888
color_19 = bbbb bbbb bbbb
color_20 = 9999 9999 9999
color_21 = dddd dddd dddd
color_22 = aaaa aaaa aaaa
color_23 = bbbb bbbb bbbb
color_24 = ffff ffff ffff
color_25 = dddd dddd dddd
color_26 = cccc cccc cccc
color_27 = eeee eeee eeee
color_28 = aaaa aaaa aaaa
color_29 = cccc cccc cccc
color_30 = 4040 4040 4040
color_31 = ffff ffff ffff
color_256 = 0000 0000 0000
color_257 = cccc cccc cccc
color_258 = cccc cccc cccc
color_259 = 0000 0000 0000
color_260 = dddd dddd dddd
color_261 = 8888 8888 8888
color_262 = bbbb bbbb bbbb
color_263 = bbbb bbbb bbbb
color_264 = ffff ffff ffff
color_265 = 9999 9999 9999
