#!/usr/bin/env ruby
#
# Usage: iterm2xrdb FILE...
# Usage: cat FILE... | iterm2xrdb
# Usage: iterm2xrdb < INPUT
#
# Converts iTerm2 color schemes into xrdb(1) format, as a set of `#define`s,
# and prints the result to STDOUT.  Reads STDIN if no input files are given.
#
# Written in 2013 by Suraj N. Kurapati <https://github.com/sunaku>

puts ARGF.read.scan(%r{>(.+?)</}).flatten(1).slice_before(/\bColor$/).map {
  |color, *pairs| "#define #{ color.gsub(/\W/, ?_) } #" + Hash[*pairs].
  values_at('Red Component', 'Green Component', 'Blue Component').
  map { |intensity| sprintf '%02x', (intensity.to_f * 255).round }.join
}.to_a
