;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(0,0,0,1)
fgcolor=rgb(255,255,255)
palette_color_0=rgb(0,0,0)
palette_color_1=rgb(255,128,128)
palette_color_10=rgb(179,255,228)
palette_color_11=rgb(96,165,250)
palette_color_12=rgb(176,176,176)
palette_color_13=rgb(147,197,253)
palette_color_14=rgb(153,255,228)
palette_color_15=rgb(255,255,255)
palette_color_2=rgb(153,255,228)
palette_color_3=rgb(37,99,235)
palette_color_4=rgb(160,160,160)
palette_color_5=rgb(59,130,246)
palette_color_6=rgb(153,255,228)
palette_color_7=rgb(255,255,255)
palette_color_8=rgb(80,80,80)
palette_color_9=rgb(255,153,153)
color_preset=Atlas Ragnarok
