;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(251,246,251,1)
fgcolor=rgb(58,51,64)
palette_color_0=rgb(51,41,63)
palette_color_1=rgb(192,48,58)
palette_color_10=rgb(46,125,110)
palette_color_11=rgb(174,63,132)
palette_color_12=rgb(74,60,192)
palette_color_13=rgb(216,182,112)
palette_color_14=rgb(174,63,132)
palette_color_15=rgb(58,51,64)
palette_color_2=rgb(46,125,110)
palette_color_3=rgb(140,97,12)
palette_color_4=rgb(74,60,192)
palette_color_5=rgb(138,75,192)
palette_color_6=rgb(174,63,132)
palette_color_7=rgb(178,178,178)
palette_color_8=rgb(154,143,168)
palette_color_9=rgb(192,48,58)
color_preset=Aubade
