;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(244,249,255,1)
fgcolor=rgb(16,34,53)
palette_color_0=rgb(41,57,74)
palette_color_1=rgb(132,33,33)
palette_color_10=rgb(16,97,59)
palette_color_11=rgb(108,81,0)
palette_color_12=rgb(18,58,120)
palette_color_13=rgb(101,56,144)
palette_color_14=rgb(0,75,89)
palette_color_15=rgb(69,85,101)
palette_color_2=rgb(12,89,53)
palette_color_3=rgb(100,75,0)
palette_color_4=rgb(23,70,143)
palette_color_5=rgb(94,49,136)
palette_color_6=rgb(0,89,105)
palette_color_7=rgb(59,75,91)
palette_color_8=rgb(64,80,95)
palette_color_9=rgb(144,39,39)
color_preset=Cold Storage
