;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(249,129,40,1)
fgcolor=rgb(52,37,28)
palette_color_0=rgb(36,21,14)
palette_color_1=rgb(98,25,13)
palette_color_10=rgb(40,55,25)
palette_color_11=rgb(72,52,6)
palette_color_12=rgb(20,49,66)
palette_color_13=rgb(66,29,62)
palette_color_14=rgb(17,61,68)
palette_color_15=rgb(43,30,23)
palette_color_2=rgb(41,57,26)
palette_color_3=rgb(68,49,6)
palette_color_4=rgb(22,55,75)
palette_color_5=rgb(81,35,76)
palette_color_6=rgb(16,58,64)
palette_color_7=rgb(52,37,28)
palette_color_8=rgb(30,17,11)
palette_color_9=rgb(88,22,11)
color_preset=Great Pumpkin
