;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(248,250,252,1)
fgcolor=rgb(15,23,42)
palette_color_0=rgb(40,53,72)
palette_color_1=rgb(118,21,21)
palette_color_10=rgb(22,113,58)
palette_color_11=rgb(122,92,0)
palette_color_12=rgb(18,61,130)
palette_color_13=rgb(108,60,160)
palette_color_14=rgb(0,108,129)
palette_color_15=rgb(70,82,100)
palette_color_2=rgb(18,107,50)
palette_color_3=rgb(117,86,0)
palette_color_4=rgb(23,77,166)
palette_color_5=rgb(101,52,154)
palette_color_6=rgb(0,101,122)
palette_color_7=rgb(61,72,88)
palette_color_8=rgb(83,96,113)
palette_color_9=rgb(125,24,24)
color_preset=Horizons
