;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(6,35,41,1)
fgcolor=rgb(134,134,134)
palette_color_0=rgb(6,35,41)
palette_color_1=rgb(227,75,135)
palette_color_10=rgb(16,155,72)
palette_color_11=rgb(199,112,14)
palette_color_12=rgb(15,141,205)
palette_color_13=rgb(156,97,252)
palette_color_14=rgb(15,144,127)
palette_color_15=rgb(134,134,134)
palette_color_2=rgb(65,150,88)
palette_color_3=rgb(186,120,62)
palette_color_4=rgb(64,140,189)
palette_color_5=rgb(151,111,227)
palette_color_6=rgb(62,140,126)
palette_color_7=rgb(134,134,134)
palette_color_8=rgb(86,86,86)
palette_color_9=rgb(248,20,134)
color_preset=Isocon Dark
