;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(255,255,255,1)
fgcolor=rgb(0,0,0)
palette_color_0=rgb(0,0,0)
palette_color_1=rgb(192,22,80)
palette_color_10=rgb(26,110,28)
palette_color_11=rgb(156,104,0)
palette_color_12=rgb(47,94,158)
palette_color_13=rgb(77,45,154)
palette_color_14=rgb(47,94,158)
palette_color_15=rgb(10,14,20)
palette_color_2=rgb(26,110,28)
palette_color_3=rgb(156,104,0)
palette_color_4=rgb(47,94,158)
palette_color_5=rgb(77,45,154)
palette_color_6=rgb(47,94,158)
palette_color_7=rgb(46,44,48)
palette_color_8=rgb(153,153,153)
palette_color_9=rgb(192,22,80)
color_preset=Karma Light HC
