;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(10,16,24,1)
fgcolor=rgb(184,200,220)
palette_color_0=rgb(16,25,39)
palette_color_1=rgb(232,90,82)
palette_color_10=rgb(98,196,142)
palette_color_11=rgb(255,203,154)
palette_color_12=rgb(90,143,212)
palette_color_13=rgb(253,191,222)
palette_color_14=rgb(126,212,224)
palette_color_15=rgb(255,245,190)
palette_color_2=rgb(74,154,114)
palette_color_3=rgb(232,154,46)
palette_color_4=rgb(82,136,184)
palette_color_5=rgb(188,80,144)
palette_color_6=rgb(94,200,200)
palette_color_7=rgb(165,181,213)
palette_color_8=rgb(52,70,88)
palette_color_9=rgb(252,144,119)
color_preset=Keys Ocean Sunset
