;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(22,31,44,1)
fgcolor=rgb(232,238,242)
palette_color_0=rgb(28,37,51)
palette_color_1=rgb(197,87,63)
palette_color_10=rgb(136,170,163)
palette_color_11=rgb(240,205,108)
palette_color_12=rgb(130,164,204)
palette_color_13=rgb(176,155,192)
palette_color_14=rgb(160,194,208)
palette_color_15=rgb(250,251,252)
palette_color_2=rgb(106,142,133)
palette_color_3=rgb(226,189,92)
palette_color_4=rgb(94,135,179)
palette_color_5=rgb(155,134,168)
palette_color_6=rgb(130,168,184)
palette_color_7=rgb(232,238,242)
palette_color_8=rgb(74,86,106)
palette_color_9=rgb(224,112,80)
color_preset=London Embankment Dusk
