;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(14,12,14,1)
fgcolor=rgb(232,224,200)
palette_color_0=rgb(26,20,24)
palette_color_1=rgb(214,90,58)
palette_color_10=rgb(136,168,104)
palette_color_11=rgb(245,194,92)
palette_color_12=rgb(122,150,208)
palette_color_13=rgb(237,133,188)
palette_color_14=rgb(160,188,214)
palette_color_15=rgb(253,246,223)
palette_color_2=rgb(106,138,74)
palette_color_3=rgb(232,176,72)
palette_color_4=rgb(90,122,184)
palette_color_5=rgb(215,106,168)
palette_color_6=rgb(136,168,200)
palette_color_7=rgb(232,224,200)
palette_color_8=rgb(68,64,60)
palette_color_9=rgb(236,118,84)
color_preset=London Bonfire Night
