;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(10,7,20,1)
fgcolor=rgb(220,211,255)
palette_color_0=rgb(45,27,78)
palette_color_1=rgb(106,43,189)
palette_color_10=rgb(255,107,214)
palette_color_11=rgb(122,230,255)
palette_color_12=rgb(155,180,255)
palette_color_13=rgb(227,132,255)
palette_color_14=rgb(122,230,255)
palette_color_15=rgb(242,230,255)
palette_color_2=rgb(196,61,255)
palette_color_3=rgb(62,199,255)
palette_color_4=rgb(122,99,255)
palette_color_5=rgb(255,78,219)
palette_color_6=rgb(92,200,255)
palette_color_7=rgb(197,167,255)
palette_color_8=rgb(103,97,117)
palette_color_9=rgb(161,57,230)
color_preset=Prince of Darkness
