;Paste the following configurations in thecorresponding place in lxterminal.conf.
bgcolor=rgba(248,250,254,1)
fgcolor=rgb(84,77,64)
palette_color_0=rgb(248,250,254)
palette_color_1=rgb(31,170,158)
palette_color_10=rgb(90,31,138)
palette_color_11=rgb(15,91,162)
palette_color_12=rgb(178,59,0)
palette_color_13=rgb(33,140,0)
palette_color_14=rgb(179,46,31)
palette_color_15=rgb(0,0,0)
palette_color_2=rgb(115,61,154)
palette_color_3=rgb(46,112,173)
palette_color_4=rgb(181,90,15)
palette_color_5=rgb(62,157,33)
palette_color_6=rgb(189,76,61)
palette_color_7=rgb(84,77,64)
palette_color_8=rgb(176,169,153)
palette_color_9=rgb(0,158,145)
color_preset=X Helsinki
