# -*- conf -*-
# Abernathy

[colors-dark]
cursor=ffffff bbbbbb
background=111416
foreground=eeeeec
selection-foreground=333333
selection-background=eeeeec
regular0=000000  # black
regular1=cd0000  # red
regular2=00cd00  # green
regular3=cdcd00  # yellow
regular4=1093f5  # blue
regular5=cd00cd  # magenta
regular6=00cdcd  # cyan
regular7=faebd7  # white
bright0=404040   # bright black
bright1=ff0000   # bright red
bright2=00ff00   # bright green
bright3=ffff00   # bright yellow
bright4=11b5f6   # bright blue
bright5=ff00ff   # bright magenta
bright6=00ffff   # bright cyan
bright7=ffffff   # bright white
