# -*- conf -*-
# Adventure Time

[colors-dark]
cursor=08080a efbf38
background=1f1d45
foreground=f8dcc0
selection-foreground=f3d9c4
selection-background=706b4e
regular0=050404  # black
regular1=bd0013  # red
regular2=4ab118  # green
regular3=e7741e  # yellow
regular4=0f4ac6  # blue
regular5=665993  # magenta
regular6=70a598  # cyan
regular7=f8dcc0  # white
bright0=4e7cbf   # bright black
bright1=fc5f5a   # bright red
bright2=9eff6e   # bright green
bright3=efc11a   # bright yellow
bright4=1997c6   # bright blue
bright5=9b5953   # bright magenta
bright6=c8faf4   # bright cyan
bright7=f6f5fb   # bright white
