# -*- conf -*-
# Alabaster

[main]
initial-color-theme=light

[colors-light]
cursor=bfdbfe 007acc
background=f7f7f7
foreground=000000
selection-foreground=000000
selection-background=bfdbfe
regular0=000000  # black
regular1=aa3731  # red
regular2=448c27  # green
regular3=cb9000  # yellow
regular4=325cc0  # blue
regular5=7a3e9d  # magenta
regular6=0083b2  # cyan
regular7=b7b7b7  # white
bright0=777777   # bright black
bright1=f05050   # bright red
bright2=60cb00   # bright green
bright3=f2af50   # bright yellow
bright4=007acc   # bright blue
bright5=e64ce6   # bright magenta
bright6=00aacb   # bright cyan
bright7=f7f7f7   # bright white
