# -*- conf -*-
# Birds Of Paradise

[colors-dark]
cursor=8a7059 644a33
background=2a1f1d
foreground=e0dbb7
selection-foreground=e0dbbb
selection-background=563c27
regular0=573d26  # black
regular1=be2d26  # red
regular2=6ba18a  # green
regular3=e99d2a  # yellow
regular4=5a86ad  # blue
regular5=ac80a6  # magenta
regular6=74a6ad  # cyan
regular7=e0dbb7  # white
bright0=9b6c4a   # bright black
bright1=e84627   # bright red
bright2=95d8ba   # bright green
bright3=d0d150   # bright yellow
bright4=b8d3ed   # bright blue
bright5=d19ecb   # bright magenta
bright6=93cfd7   # bright cyan
bright7=fff9d5   # bright white
