# -*- conf -*-
# Black Metal (Immortal)

[colors-dark]
cursor=8e8e8e c1c1c1
background=000000
foreground=c1c1c1
selection-foreground=000000
selection-background=c1c1c1
regular0=000000  # black
regular1=5f8787  # red
regular2=7799bb  # green
regular3=556677  # yellow
regular4=888888  # blue
regular5=999999  # magenta
regular6=aaaaaa  # cyan
regular7=c1c1c1  # white
bright0=404040   # bright black
bright1=5f8787   # bright red
bright2=7799bb   # bright green
bright3=556677   # bright yellow
bright4=888888   # bright blue
bright5=999999   # bright magenta
bright6=aaaaaa   # bright cyan
bright7=c1c1c1   # bright white
