# -*- conf -*-
# Bluloco Dark

[colors-dark]
cursor=282c34 ffcc00
background=282c34
foreground=b9c0cb
selection-foreground=272b33
selection-background=b9c0ca
regular0=41444d  # black
regular1=fc2f52  # red
regular2=25a45c  # green
regular3=ff936a  # yellow
regular4=3476ff  # blue
regular5=7a82da  # magenta
regular6=4483aa  # cyan
regular7=cdd4e0  # white
bright0=8f9aae   # bright black
bright1=ff6480   # bright red
bright2=3fc56b   # bright green
bright3=f9c859   # bright yellow
bright4=10b1fe   # bright blue
bright5=ff78f8   # bright magenta
bright6=5fb9bc   # bright cyan
bright7=ffffff   # bright white
