# -*- conf -*-
# Catppuccin Frappe

[colors-dark]
cursor=303446 f2d5cf
background=303446
foreground=c6d0f5
selection-foreground=c6d0f5
selection-background=626880
regular0=51576d  # black
regular1=e78284  # red
regular2=a6d189  # green
regular3=e5c890  # yellow
regular4=8caaee  # blue
regular5=f4b8e4  # magenta
regular6=81c8be  # cyan
regular7=a5adce  # white
bright0=626880   # bright black
bright1=e67172   # bright red
bright2=8ec772   # bright green
bright3=d9ba73   # bright yellow
bright4=7b9ef0   # bright blue
bright5=f2a4db   # bright magenta
bright6=5abfb5   # bright cyan
bright7=b5bfe2   # bright white
