# -*- conf -*-
# Chalkboard

[colors-dark]
cursor=29262f d9e6f2
background=29262f
foreground=d9e6f2
selection-foreground=ffffff
selection-background=073642
regular0=000000  # black
regular1=c37372  # red
regular2=72c373  # green
regular3=c2c372  # yellow
regular4=7372c3  # blue
regular5=c372c2  # magenta
regular6=72c2c3  # cyan
regular7=d9d9d9  # white
bright0=585858   # bright black
bright1=dbaaaa   # bright red
bright2=aadbaa   # bright green
bright3=dadbaa   # bright yellow
bright4=aaaadb   # bright blue
bright5=dbaada   # bright magenta
bright6=aadadb   # bright cyan
bright7=ffffff   # bright white
