# -*- conf -*-
# Cutie Pro

[colors-dark]
cursor=181818 efc4cd
background=181818
foreground=d5d0c9
selection-foreground=d5d0c9
selection-background=363636
regular0=000000  # black
regular1=f56e7f  # red
regular2=bec975  # green
regular3=f58669  # yellow
regular4=42d9c5  # blue
regular5=d286b7  # magenta
regular6=37cb8a  # cyan
regular7=d5c3c3  # white
bright0=88847f   # bright black
bright1=e5a1a3   # bright red
bright2=e8d6a7   # bright green
bright3=f1bb79   # bright yellow
bright4=80c5de   # bright blue
bright5=b294bb   # bright magenta
bright6=9dccbb   # bright cyan
bright7=ffffff   # bright white
