# -*- conf -*-
# Django

[colors-dark]
cursor=f8f8f8 336442
background=0b2f20
foreground=f8f8f8
selection-foreground=f8f8f8
selection-background=245032
regular0=000000  # black
regular1=fd6209  # red
regular2=41a83e  # green
regular3=ffe862  # yellow
regular4=315d3f  # blue
regular5=f8f8f8  # magenta
regular6=9df39f  # cyan
regular7=ffffff  # white
bright0=585858   # bright black
bright1=ff943b   # bright red
bright2=73da70   # bright green
bright3=ffff94   # bright yellow
bright4=568264   # bright blue
bright5=ffffff   # bright magenta
bright6=cfffd1   # bright cyan
bright7=ffffff   # bright white
