# -*- conf -*-
# Elementary

[colors-dark]
cursor=ffffff bbbbbb
background=181818
foreground=efefef
selection-foreground=000000
selection-background=b5d5ff
regular0=242424  # black
regular1=d71c15  # red
regular2=5aa513  # green
regular3=fdb40c  # yellow
regular4=134899  # blue
regular5=e40038  # magenta
regular6=2595e1  # cyan
regular7=efefef  # white
bright0=4b4b4b   # bright black
bright1=fc1c18   # bright red
bright2=6bc219   # bright green
bright3=fec80e   # bright yellow
bright4=0955ff   # bright blue
bright5=fb0050   # bright magenta
bright6=3ea8fc   # bright cyan
bright7=8c00ec   # bright white
