# -*- conf -*-
# Espresso Libre

[colors-dark]
cursor=000000 ffffff
background=2a211c
foreground=b8a898
selection-foreground=ab9b8b
selection-background=c3dcff
regular0=000000  # black
regular1=cc0000  # red
regular2=1a921c  # green
regular3=f0e53a  # yellow
regular4=0066ff  # blue
regular5=c5656b  # magenta
regular6=06989a  # cyan
regular7=d3d7cf  # white
bright0=555753   # bright black
bright1=ef2929   # bright red
bright2=9aff87   # bright green
bright3=fffb5c   # bright yellow
bright4=43a8ed   # bright blue
bright5=ff818a   # bright magenta
bright6=34e2e2   # bright cyan
bright7=eeeeec   # bright white
