# -*- conf -*-
# Fairyfloss

[colors-dark]
cursor=060709 f8f8f0
background=5a5475
foreground=f8f8f2
selection-foreground=f6e1ce
selection-background=8077a8
regular0=040303  # black
regular1=f92672  # red
regular2=c2ffdf  # green
regular3=e6c000  # yellow
regular4=c2ffdf  # blue
regular5=ffb8d1  # magenta
regular6=c5a3ff  # cyan
regular7=f8f8f0  # white
bright0=6090cb   # bright black
bright1=ff857f   # bright red
bright2=c2ffdf   # bright green
bright3=ffea00   # bright yellow
bright4=c2ffdf   # bright blue
bright5=ffb8d1   # bright magenta
bright6=c5a3ff   # bright cyan
bright7=f8f8f0   # bright white
