# -*- conf -*-
# Farmhouse Light

[main]
initial-color-theme=light

[colors-light]
cursor=1d2027 006efe
background=e8e4e1
foreground=1d2027
selection-foreground=4d5658
selection-background=b3b1aa
regular0=1d2027  # black
regular1=8d0003  # red
regular2=3a7d00  # green
regular3=a95600  # yellow
regular4=092ccd  # blue
regular5=820046  # magenta
regular6=229256  # cyan
regular7=a8a4a1  # white
bright0=394047   # bright black
bright1=eb0009   # bright red
bright2=7ac100   # bright green
bright3=ea9a00   # bright yellow
bright4=006efe   # bright blue
bright5=bf3b7f   # bright magenta
bright6=00c649   # bright cyan
bright7=f4eef0   # bright white
