# -*- conf -*-
# Floraverse

[colors-dark]
cursor=ffffff bbbbbb
background=0e0d15
foreground=dbd1b9
selection-foreground=08002e
selection-background=f3e0b8
regular0=08002e  # black
regular1=7e1a46  # red
regular2=5d731a  # green
regular3=cd751c  # yellow
regular4=1d6da1  # blue
regular5=b7077e  # magenta
regular6=42a38c  # cyan
regular7=f3e0b8  # white
bright0=4c3866   # bright black
bright1=d02063   # bright red
bright2=b4ce59   # bright green
bright3=fac357   # bright yellow
bright4=40a4cf   # bright blue
bright5=f12aae   # bright magenta
bright6=62caa8   # bright cyan
bright7=fff5db   # bright white
