# -*- conf -*-
# Front End Delight

[colors-dark]
cursor=1b1c1d cdcdcd
background=1b1c1d
foreground=adadad
selection-foreground=1b1c1d
selection-background=ea6154
regular0=242526  # black
regular1=f8511b  # red
regular2=565747  # green
regular3=fa771d  # yellow
regular4=2c70b7  # blue
regular5=f02e4f  # magenta
regular6=3ca1a6  # cyan
regular7=adadad  # white
bright0=5fac6d   # bright black
bright1=f74319   # bright red
bright2=74ec4c   # bright green
bright3=fdc325   # bright yellow
bright4=3393ca   # bright blue
bright5=e75e4f   # bright magenta
bright6=4fbce6   # bright cyan
bright7=8c735b   # bright white
