# -*- conf -*-
# Ghostty Default Style Dark

[colors-dark]
cursor=353a44 ffffff
background=282c34
foreground=ffffff
selection-foreground=282c34
selection-background=ffffff
regular0=1d1f21  # black
regular1=cc6566  # red
regular2=b6bd68  # green
regular3=f0c674  # yellow
regular4=82a2be  # blue
regular5=b294bb  # magenta
regular6=8abeb7  # cyan
regular7=c4c8c6  # white
bright0=666666   # bright black
bright1=d54e53   # bright red
bright2=b9ca4b   # bright green
bright3=e7c547   # bright yellow
bright4=7aa6da   # bright blue
bright5=c397d8   # bright magenta
bright6=70c0b1   # bright cyan
bright7=eaeaea   # bright white
