# -*- conf -*-
# GitLab Dark

[colors-dark]
cursor=bfbfbf ffffff
background=28262b
foreground=ffffff
selection-foreground=28262b
selection-background=ad95e9
regular0=000000  # black
regular1=f57f6c  # red
regular2=52b87a  # green
regular3=d99530  # yellow
regular4=7fb6ed  # blue
regular5=f88aaf  # magenta
regular6=32c5d2  # cyan
regular7=ffffff  # white
bright0=666666   # bright black
bright1=fcb5aa   # bright red
bright2=91d4a8   # bright green
bright3=e9be74   # bright yellow
bright4=498dd1   # bright blue
bright5=fcacc5   # bright magenta
bright6=5edee3   # bright cyan
bright7=ffffff   # bright white
