# -*- conf -*-
# Gruvbox Light Hard

[main]
initial-color-theme=light

[colors-light]
cursor=f9f5d7 3c3836
background=f9f5d7
foreground=3c3836
selection-foreground=f9f5d7
selection-background=3c3836
regular0=f9f5d7  # black
regular1=cc241d  # red
regular2=98971a  # green
regular3=d79921  # yellow
regular4=458588  # blue
regular5=b16286  # magenta
regular6=689d6a  # cyan
regular7=7c6f64  # white
bright0=928374   # bright black
bright1=9d0006   # bright red
bright2=79740e   # bright green
bright3=b57614   # bright yellow
bright4=076678   # bright blue
bright5=8f3f71   # bright magenta
bright6=427b58   # bright cyan
bright7=3c3836   # bright white
