# -*- conf -*-
# Gruvbox Dark Hard

[colors-dark]
cursor=1d2021 ebdbb2
background=1d2021
foreground=ebdbb2
selection-foreground=ebdbb2
selection-background=665c54
regular0=1d2021  # black
regular1=cc241d  # red
regular2=98971a  # green
regular3=d79921  # yellow
regular4=458588  # blue
regular5=b16286  # magenta
regular6=689d6a  # cyan
regular7=a89984  # white
bright0=928374   # bright black
bright1=fb4934   # bright red
bright2=b8bb26   # bright green
bright3=fabd2f   # bright yellow
bright4=83a598   # bright blue
bright5=d3869b   # bright magenta
bright6=8ec07c   # bright cyan
bright7=ebdbb2   # bright white
