# -*- conf -*-
# Guezwhoz

[colors-dark]
cursor=1d1d1d 99d4b1
background=1d1d1d
foreground=d9d9d9
selection-foreground=58d6ce
selection-background=245354
regular0=333333  # black
regular1=e85181  # red
regular2=7ad694  # green
regular3=b7d074  # yellow
regular4=5aa0d6  # blue
regular5=9a90e0  # magenta
regular6=58d6ce  # cyan
regular7=d9d9d9  # white
bright0=808080   # bright black
bright1=e85181   # bright red
bright2=afd7af   # bright green
bright3=d1ed85   # bright yellow
bright4=64b2ed   # bright blue
bright5=a398ed   # bright magenta
bright6=61ede4   # bright cyan
bright7=ededed   # bright white
