# -*- conf -*-
# iTerm2 Smoooooth

[colors-dark]
cursor=000000 ffffff
background=15191f
foreground=dcdcdc
selection-foreground=000000
selection-background=b3d7ff
regular0=14191e  # black
regular1=b43c2a  # red
regular2=00c200  # green
regular3=c7c400  # yellow
regular4=2744c7  # blue
regular5=c040be  # magenta
regular6=00c5c7  # cyan
regular7=c7c7c7  # white
bright0=686868   # bright black
bright1=dd7975   # bright red
bright2=58e790   # bright green
bright3=ece100   # bright yellow
bright4=a7abf2   # bright blue
bright5=e17ee1   # bright magenta
bright6=60fdff   # bright cyan
bright7=ffffff   # bright white
