# -*- conf -*-
# iTerm2 Pastel Dark Background

[colors-dark]
cursor=8c8c8c ffb473
background=000000
foreground=c7c7c7
selection-foreground=f4f4f4
selection-background=454d96
regular0=626262  # black
regular1=ff8373  # red
regular2=b4fb73  # green
regular3=fffdc3  # yellow
regular4=a5d5fe  # blue
regular5=ff90fe  # magenta
regular6=d1d1fe  # cyan
regular7=f1f1f1  # white
bright0=8f8f8f   # bright black
bright1=ffc4be   # bright red
bright2=d6fcba   # bright green
bright3=fffed5   # bright yellow
bright4=c2e3ff   # bright blue
bright5=ffb2fe   # bright magenta
bright6=e6e6fe   # bright cyan
bright7=ffffff   # bright white
