# -*- conf -*-
# Jellybeans

[colors-dark]
cursor=ffffff ffa560
background=121212
foreground=dedede
selection-foreground=f4f4f4
selection-background=474e91
regular0=929292  # black
regular1=e27373  # red
regular2=94b979  # green
regular3=ffba7b  # yellow
regular4=97bedc  # blue
regular5=e1c0fa  # magenta
regular6=00988e  # cyan
regular7=dedede  # white
bright0=bdbdbd   # bright black
bright1=ffa1a1   # bright red
bright2=bddeab   # bright green
bright3=ffdca0   # bright yellow
bright4=b1d8f6   # bright blue
bright5=fbdaff   # bright magenta
bright6=1ab2a8   # bright cyan
bright7=ffffff   # bright white
