# -*- conf -*-
# JetBrains Darcula

[colors-dark]
cursor=000000 ffffff
background=202020
foreground=adadad
selection-foreground=adadad
selection-background=1a3272
regular0=000000  # black
regular1=fa5355  # red
regular2=126e00  # green
regular3=c2c300  # yellow
regular4=4581eb  # blue
regular5=fa54ff  # magenta
regular6=33c2c1  # cyan
regular7=adadad  # white
bright0=555555   # bright black
bright1=fb7172   # bright red
bright2=67ff4f   # bright green
bright3=ffff00   # bright yellow
bright4=6d9df1   # bright blue
bright5=fb82ff   # bright magenta
bright6=60d3d1   # bright cyan
bright7=eeeeee   # bright white
