# -*- conf -*-
# Kanagawabones

[colors-dark]
cursor=1f1f28 e6e0c2
background=1f1f28
foreground=ddd8bb
selection-foreground=ddd8bb
selection-background=49473e
regular0=1f1f28  # black
regular1=e46a78  # red
regular2=98bc6d  # green
regular3=e5c283  # yellow
regular4=7eb3c9  # blue
regular5=957fb8  # magenta
regular6=7eb3c9  # cyan
regular7=ddd8bb  # white
bright0=49495e   # bright black
bright1=ec818c   # bright red
bright2=9ec967   # bright green
bright3=f1c982   # bright yellow
bright4=7bc2df   # bright blue
bright5=a98fd2   # bright magenta
bright6=7bc2df   # bright cyan
bright7=a8a48d   # bright white
