# -*- conf -*-
# Material

[main]
initial-color-theme=light

[colors-light]
cursor=2e2e2d 16afca
background=eaeaea
foreground=232322
selection-foreground=4e4e4e
selection-background=c2c2c2
regular0=212121  # black
regular1=b7141f  # red
regular2=457b24  # green
regular3=f6981e  # yellow
regular4=134eb2  # blue
regular5=560088  # magenta
regular6=0e717c  # cyan
regular7=afafaf  # white
bright0=424242   # bright black
bright1=e83b3f   # bright red
bright2=7aba3a   # bright green
bright3=bfaa00   # bright yellow
bright4=54a4f3   # bright blue
bright5=aa4dbc   # bright magenta
bright6=26bbd1   # bright cyan
bright7=d9d9d9   # bright white
