# -*- conf -*-
# Melange Light

[main]
initial-color-theme=light

[colors-light]
cursor=f1f1f1 54433a
background=f1f1f1
foreground=54433a
selection-foreground=d9d3ce
selection-background=54433a
regular0=e9e1db  # black
regular1=c77b8b  # red
regular2=6e9b72  # green
regular3=bc5c00  # yellow
regular4=7892bd  # blue
regular5=be79bb  # magenta
regular6=739797  # cyan
regular7=7d6658  # white
bright0=a98a78   # bright black
bright1=bf0021   # bright red
bright2=3a684a   # bright green
bright3=a06d00   # bright yellow
bright4=465aa4   # bright blue
bright5=904180   # bright magenta
bright6=3d6568   # bright cyan
bright7=54433a   # bright white
