# -*- conf -*-
# Midnight In Mojave

[colors-dark]
cursor=1c1c1c 32d74b
background=1e1e1e
foreground=ffffff
selection-foreground=ffffff
selection-background=4a504d
regular0=1e1e1e  # black
regular1=ff453a  # red
regular2=32d74b  # green
regular3=ffd60a  # yellow
regular4=0a84ff  # blue
regular5=bf5af2  # magenta
regular6=5ac8fa  # cyan
regular7=ffffff  # white
bright0=515151   # bright black
bright1=ff453a   # bright red
bright2=32d74b   # bright green
bright3=ffd60a   # bright yellow
bright4=0a84ff   # bright blue
bright5=bf5af2   # bright magenta
bright6=5ac8fa   # bright cyan
bright7=ffffff   # bright white
