# -*- conf -*-
# Modus Vivendi
# made by Protesilaos Stavrou (https://protesilaos.com/)

[colors-dark]
cursor=000000 ffffff
background=000000
foreground=ffffff
selection-foreground=ffffff
selection-background=5a5a5a
regular0=000000  # black
regular1=ff5f59  # red
regular2=44bc44  # green
regular3=d0bc00  # yellow
regular4=2fafff  # blue
regular5=feacd0  # magenta
regular6=00d3d0  # cyan
regular7=a6a6a6  # white
bright0=595959   # bright black
bright1=ff7f9f   # bright red
bright2=00c06f   # bright green
bright3=fec43f   # bright yellow
bright4=79a8ff   # bright blue
bright5=b6a0ff   # bright magenta
bright6=6ae4b9   # bright cyan
bright7=ffffff   # bright white
