# -*- conf -*-
# Monokai Pro Light Sun

[main]
initial-color-theme=light

[colors-light]
cursor=a59ca0 72696d
background=f8efe7
foreground=2c232e
selection-foreground=2c232e
selection-background=beb5b3
regular0=f8efe7  # black
regular1=ce4770  # red
regular2=218871  # green
regular3=b16803  # yellow
regular4=d4572b  # blue
regular5=6851a2  # magenta
regular6=2473b6  # cyan
regular7=2c232e  # white
bright0=a59c9c   # bright black
bright1=ce4770   # bright red
bright2=218871   # bright green
bright3=b16803   # bright yellow
bright4=d4572b   # bright blue
bright5=6851a2   # bright magenta
bright6=2473b6   # bright cyan
bright7=2c232e   # bright white
