# -*- conf -*-
# Monokai Pro Machine

[colors-dark]
cursor=859190 b8c4c3
background=273136
foreground=f2fffc
selection-foreground=f2fffc
selection-background=545f62
regular0=273136  # black
regular1=ff6d7e  # red
regular2=a2e57b  # green
regular3=ffed72  # yellow
regular4=ffb270  # blue
regular5=baa0f8  # magenta
regular6=7cd5f1  # cyan
regular7=f2fffc  # white
bright0=6b7678   # bright black
bright1=ff6d7e   # bright red
bright2=a2e57b   # bright green
bright3=ffed72   # bright yellow
bright4=ffb270   # bright blue
bright5=baa0f8   # bright magenta
bright6=7cd5f1   # bright cyan
bright7=f2fffc   # bright white
