# -*- conf -*-
# Monokai Remastered

[colors-dark]
cursor=000000 fc971f
background=0c0c0c
foreground=d9d9d9
selection-foreground=ffffff
selection-background=343434
regular0=1a1a1a  # black
regular1=f4005f  # red
regular2=98e024  # green
regular3=fd971f  # yellow
regular4=9d65ff  # blue
regular5=f4005f  # magenta
regular6=58d1eb  # cyan
regular7=c4c5b5  # white
bright0=625e4c   # bright black
bright1=f4005f   # bright red
bright2=98e024   # bright green
bright3=e0d561   # bright yellow
bright4=9d65ff   # bright blue
bright5=f4005f   # bright magenta
bright6=58d1eb   # bright cyan
bright7=f6f6ef   # bright white
