# -*- conf -*-
# Moonfly

[colors-dark]
cursor=080808 9e9e9e
background=080808
foreground=bdbdbd
selection-foreground=080808
selection-background=b2ceee
regular0=323437  # black
regular1=ff5454  # red
regular2=8cc85f  # green
regular3=e3c78a  # yellow
regular4=80a0ff  # blue
regular5=cf87e8  # magenta
regular6=79dac8  # cyan
regular7=c6c6c6  # white
bright0=949494   # bright black
bright1=ff5189   # bright red
bright2=36c692   # bright green
bright3=c6c684   # bright yellow
bright4=74b2ff   # bright blue
bright5=ae81ff   # bright magenta
bright6=85dc85   # bright cyan
bright7=e4e4e4   # bright white
