# -*- conf -*-
# No Clown Fiesta Light

[main]
initial-color-theme=light

[colors-light]
cursor=d0d0d0 151515
background=e1e1e1
foreground=151515
selection-foreground=151515
selection-background=c6d5de
regular0=d6d6d6  # black
regular1=874e42  # red
regular2=677940  # green
regular3=b89058  # yellow
regular4=8ba1bf  # blue
regular5=aa759f  # magenta
regular6=3e5f66  # cyan
regular7=151515  # white
bright0=2b2b2b   # bright black
bright1=637786   # bright red
bright2=677940   # bright green
bright3=b89058   # bright yellow
bright4=93a2ab   # bright blue
bright5=aa759f   # bright magenta
bright6=99ab93   # bright cyan
bright7=373737   # bright white
