# -*- conf -*-
# Nocturnal Winter

[colors-dark]
cursor=a6a6a6 e6e5e5
background=0d0d17
foreground=e6e5e5
selection-foreground=000000
selection-background=adbdd0
regular0=4d4d4d  # black
regular1=f12d52  # red
regular2=09cd7e  # green
regular3=f5f17a  # yellow
regular4=3182e0  # blue
regular5=ff2b6d  # magenta
regular6=09c87a  # cyan
regular7=fcfcfc  # white
bright0=808080   # bright black
bright1=f16d86   # bright red
bright2=0ae78d   # bright green
bright3=fffc67   # bright yellow
bright4=6096ff   # bright blue
bright5=ff78a2   # bright magenta
bright6=0ae78d   # bright cyan
bright7=ffffff   # bright white
