# -*- conf -*-
# Nordfox

[colors-dark]
cursor=2e3440 cdcecf
background=2e3440
foreground=cdcecf
selection-foreground=cdcecf
selection-background=3e4a5b
regular0=3b4252  # black
regular1=bf616a  # red
regular2=a3be8c  # green
regular3=ebcb8b  # yellow
regular4=81a1c1  # blue
regular5=b48ead  # magenta
regular6=88c0d0  # cyan
regular7=e5e9f0  # white
bright0=53648d   # bright black
bright1=d06f79   # bright red
bright2=b1d196   # bright green
bright3=f0d399   # bright yellow
bright4=8cafd2   # bright blue
bright5=c895bf   # bright magenta
bright6=93ccdc   # bright cyan
bright7=e7ecf4   # bright white
