# -*- conf -*-
# One Double Light

[main]
initial-color-theme=light

[colors-light]
cursor=dbdfe5 1a1919
background=fafafa
foreground=383a43
selection-foreground=1a1919
selection-background=454e5e
regular0=454b58  # black
regular1=f74840  # red
regular2=25a343  # green
regular3=cc8100  # yellow
regular4=0087c1  # blue
regular5=b50da9  # magenta
regular6=009ab7  # cyan
regular7=c5b2b3  # white
bright0=0e131f   # bright black
bright1=ff3711   # bright red
bright2=00b90e   # bright green
bright3=ec9900   # bright yellow
bright4=1065de   # bright blue
bright5=e500d8   # bright magenta
bright6=00b4dd   # bright cyan
bright7=ffffff   # bright white
