# -*- conf -*-
# owl

[colors-dark]
cursor=2f2b2c dedede
background=2f2b2c
foreground=dedede
selection-foreground=2f2b2c
selection-background=dedede
regular0=302c2c  # black
regular1=5a5a5a  # red
regular2=989898  # green
regular3=cacaca  # yellow
regular4=656565  # blue
regular5=b1b1b1  # magenta
regular6=7f7f7f  # cyan
regular7=dedede  # white
bright0=5d595b   # bright black
bright1=da5b2c   # bright red
bright2=989898   # bright green
bright3=cacaca   # bright yellow
bright4=656565   # bright blue
bright5=b1b1b1   # bright magenta
bright6=7f7f7f   # bright cyan
bright7=ffffff   # bright white
