# -*- conf -*-
# Oxocarbon

[colors-dark]
cursor=000000 ffffff
background=161616
foreground=f2f4f8
selection-foreground=626262
selection-background=393939
regular0=161616  # black
regular1=00dfdb  # red
regular2=00b4ff  # green
regular3=ff4297  # yellow
regular4=00c15a  # blue
regular5=c693ff  # magenta
regular6=ff74b8  # cyan
regular7=f2f4f8  # white
bright0=585858   # bright black
bright1=00dfdb   # bright red
bright2=00b4ff   # bright green
bright3=ff4297   # bright yellow
bright4=00c15a   # bright blue
bright5=c693ff   # bright magenta
bright6=ff74b8   # bright cyan
bright7=f2f4f8   # bright white
