# -*- conf -*-
# Pencil Dark

[colors-dark]
cursor=f1f1f1 20bbfc
background=212121
foreground=f1f1f1
selection-foreground=989898
selection-background=b6d6fd
regular0=212121  # black
regular1=c30771  # red
regular2=10a778  # green
regular3=a89c14  # yellow
regular4=008ec4  # blue
regular5=5f4986  # magenta
regular6=20a5ba  # cyan
regular7=d9d9d9  # white
bright0=4f4f4f   # bright black
bright1=fb007a   # bright red
bright2=5fd7af   # bright green
bright3=f3e430   # bright yellow
bright4=20bbfc   # bright blue
bright5=6855de   # bright magenta
bright6=4fb8cc   # bright cyan
bright7=f1f1f1   # bright white
