# -*- conf -*-
# Poimandres White

[main]
initial-color-theme=light

[colors-light]
cursor=fefeff 969cbd
background=fefeff
foreground=969cbd
selection-foreground=3b3e48
selection-background=969cbd
regular0=fefeff  # black
regular1=ff2090  # red
regular2=01dab2  # green
regular3=e5ba4e  # yellow
regular4=8abacd  # blue
regular5=eb8394  # magenta
regular6=8abacd  # cyan
regular7=000000  # white
bright0=969cbd   # bright black
bright1=ff2090   # bright red
bright2=01dab2   # bright green
bright3=e5ba4e   # bright yellow
bright4=0ebfff   # bright blue
bright5=eb8394   # bright magenta
bright6=0ebfff   # bright cyan
bright7=000000   # bright white
