# -*- conf -*-
# Rebecca

[colors-dark]
cursor=292a44 b89bf9
background=292a44
foreground=e8e6ed
selection-foreground=f4f2f9
selection-background=663399
regular0=12131e  # black
regular1=dd7755  # red
regular2=04dbb5  # green
regular3=f2e7b7  # yellow
regular4=7aa5ff  # blue
regular5=bf9cf9  # magenta
regular6=56d3c2  # cyan
regular7=e4e3e9  # white
bright0=666699   # bright black
bright1=ff92cd   # bright red
bright2=01eac0   # bright green
bright3=fffca8   # bright yellow
bright4=69c0fa   # bright blue
bright5=c17ff8   # bright magenta
bright6=8bfde1   # bright cyan
bright7=f4f2f9   # bright white
