# -*- conf -*-
# Red Alert

[colors-dark]
cursor=762423 ffffff
background=762423
foreground=ffffff
selection-foreground=ffffff
selection-background=073642
regular0=000000  # black
regular1=d62e4e  # red
regular2=71be6b  # green
regular3=beb86b  # yellow
regular4=489bee  # blue
regular5=e979d7  # magenta
regular6=6bbeb8  # cyan
regular7=d6d6d6  # white
bright0=666666   # bright black
bright1=e02553   # bright red
bright2=aff08c   # bright green
bright3=dfddb7   # bright yellow
bright4=65aaf1   # bright blue
bright5=ddb7df   # bright magenta
bright6=b7dfdd   # bright cyan
bright7=ffffff   # bright white
