# -*- conf -*-
# Retro

[colors-dark]
cursor=000000 13a10e
background=000000
foreground=13a10e
selection-foreground=000000
selection-background=ffffff
regular0=13a10e  # black
regular1=13a10e  # red
regular2=13a10e  # green
regular3=13a10e  # yellow
regular4=13a10e  # blue
regular5=13a10e  # magenta
regular6=13a10e  # cyan
regular7=13a10e  # white
bright0=16ba10   # bright black
bright1=16ba10   # bright red
bright2=16ba10   # bright green
bright3=16ba10   # bright yellow
bright4=16ba10   # bright blue
bright5=16ba10   # bright magenta
bright6=16ba10   # bright cyan
bright7=16ba10   # bright white
