# -*- conf -*-
# Sakura

[colors-dark]
cursor=24242e ff65fd
background=18131e
foreground=dd7bdc
selection-foreground=24242e
selection-background=c05cbf
regular0=000000  # black
regular1=d52370  # red
regular2=41af1a  # green
regular3=bc7053  # yellow
regular4=6964ab  # blue
regular5=c71fbf  # magenta
regular6=939393  # cyan
regular7=998eac  # white
bright0=786d69   # bright black
bright1=f41d99   # bright red
bright2=22e529   # bright green
bright3=f59574   # bright yellow
bright4=9892f1   # bright blue
bright5=e90cdd   # bright magenta
bright6=eeeeee   # bright cyan
bright7=cbb6ff   # bright white
