# -*- conf -*-
# Selenized Black
# made by Jan Warchoł (https://github.com/jan-warchol/selenized)

[colors-dark]
cursor=181818 777777
background=181818
foreground=b9b9b9
selection-foreground=646464
selection-background=3b3b3b
regular0=252525  # black
regular1=ed4a46  # red
regular2=70b433  # green
regular3=dbb32d  # yellow
regular4=368aeb  # blue
regular5=eb6eb7  # magenta
regular6=3fc5b7  # cyan
regular7=b9b9b9  # white
bright0=777777   # bright black
bright1=ff5e56   # bright red
bright2=83c746   # bright green
bright3=efc541   # bright yellow
bright4=4f9cfe   # bright blue
bright5=ff81ca   # bright magenta
bright6=56d8c9   # bright cyan
bright7=dedede   # bright white
