# -*- conf -*-
# Shades Of Purple

[colors-dark]
cursor=98998e fad000
background=1e1d40
foreground=ffffff
selection-foreground=c2c2c2
selection-background=b362ff
regular0=000000  # black
regular1=d90429  # red
regular2=3ad900  # green
regular3=ffe700  # yellow
regular4=6943ff  # blue
regular5=ff2c70  # magenta
regular6=00c5c7  # cyan
regular7=c7c7c7  # white
bright0=686868   # bright black
bright1=f92a1c   # bright red
bright2=43d426   # bright green
bright3=f1d000   # bright yellow
bright4=6871ff   # bright blue
bright5=ff77ff   # bright magenta
bright6=79e8fb   # bright cyan
bright7=ffffff   # bright white
