# -*- conf -*-
# Slate

[colors-dark]
cursor=323232 87d3c4
background=222222
foreground=35b1d2
selection-foreground=2dffc0
selection-background=0f3754
regular0=222222  # black
regular1=e2a8bf  # red
regular2=81d778  # green
regular3=c4c9c0  # yellow
regular4=335856  # blue
regular5=a481d3  # magenta
regular6=15ab9c  # cyan
regular7=02c5e0  # white
bright0=ffffff   # bright black
bright1=ffcdd9   # bright red
bright2=beffa8   # bright green
bright3=d0ccca   # bright yellow
bright4=7ab0d2   # bright blue
bright5=c5a7d9   # bright magenta
bright6=8cdfe0   # bright cyan
bright7=e0e0e0   # bright white
