# -*- conf -*-
# Smyck

[colors-dark]
cursor=ffffff bbbbbb
background=1b1b1b
foreground=f7f7f7
selection-foreground=f7f7f7
selection-background=207483
regular0=000000  # black
regular1=b84131  # red
regular2=7da900  # green
regular3=c4a500  # yellow
regular4=62a3c4  # blue
regular5=ba8acc  # magenta
regular6=207383  # cyan
regular7=a1a1a1  # white
bright0=7a7a7a   # bright black
bright1=d6837c   # bright red
bright2=c4f137   # bright green
bright3=fee14d   # bright yellow
bright4=8dcff0   # bright blue
bright5=f79aff   # bright magenta
bright6=6ad9cf   # bright cyan
bright7=f7f7f7   # bright white
