# -*- conf -*-
# Snazzy Soft

[colors-dark]
cursor=282a36 eaeaea
background=282a36
foreground=eff0eb
selection-foreground=000000
selection-background=92bcd0
regular0=000000  # black
regular1=ff5c57  # red
regular2=5af78e  # green
regular3=f3f99d  # yellow
regular4=57c7ff  # blue
regular5=ff6ac1  # magenta
regular6=9aedfe  # cyan
regular7=f1f1f0  # white
bright0=686868   # bright black
bright1=ff5c57   # bright red
bright2=5af78e   # bright green
bright3=f3f99d   # bright yellow
bright4=57c7ff   # bright blue
bright5=ff6ac1   # bright magenta
bright6=9aedfe   # bright cyan
bright7=f1f1f0   # bright white
