# -*- conf -*-
# Snazzy

[colors-dark]
cursor=a9a9a9 e4e4e4
background=1e1f29
foreground=ebece6
selection-foreground=000000
selection-background=81aec6
regular0=000000  # black
regular1=fc4346  # red
regular2=50fb7c  # green
regular3=f0fb8c  # yellow
regular4=49baff  # blue
regular5=fc4cb4  # magenta
regular6=8be9fe  # cyan
regular7=ededec  # white
bright0=555555   # bright black
bright1=fc4346   # bright red
bright2=50fb7c   # bright green
bright3=f0fb8c   # bright yellow
bright4=49baff   # bright blue
bright5=fc4cb4   # bright magenta
bright6=8be9fe   # bright cyan
bright7=ededec   # bright white
