# -*- conf -*-
# Srcery

[colors-dark]
cursor=1c1b19 fbb829
background=1c1b19
foreground=fce8c3
selection-foreground=1c1b19
selection-background=fce8c3
regular0=1c1b19  # black
regular1=ef2f27  # red
regular2=519f50  # green
regular3=fbb829  # yellow
regular4=2c78bf  # blue
regular5=e02c6d  # magenta
regular6=0aaeb3  # cyan
regular7=baa67f  # white
bright0=918175   # bright black
bright1=f75341   # bright red
bright2=98bc37   # bright green
bright3=fed06e   # bright yellow
bright4=68a8e4   # bright blue
bright5=ff5c8f   # bright magenta
bright6=2be4d0   # bright cyan
bright7=fce8c3   # bright white
