# -*- conf -*-
# Sundried

[colors-dark]
cursor=191717 ffffff
background=1a1818
foreground=c9c9c9
selection-foreground=c9c9c9
selection-background=302b2a
regular0=302b2a  # black
regular1=a7463d  # red
regular2=587744  # green
regular3=9d602a  # yellow
regular4=485b98  # blue
regular5=864651  # magenta
regular6=9c814f  # cyan
regular7=c9c9c9  # white
bright0=4d4e48   # bright black
bright1=aa000c   # bright red
bright2=128c21   # bright green
bright3=fc6a21   # bright yellow
bright4=7999f7   # bright blue
bright5=fd8aa1   # bright magenta
bright6=fad484   # bright cyan
bright7=ffffff   # bright white
