# -*- conf -*-
# Tearout

[colors-dark]
cursor=141415 d7c483
background=34392d
foreground=f4d2ae
selection-foreground=000000
selection-background=e4c47a
regular0=685742  # black
regular1=cc967b  # red
regular2=97976d  # green
regular3=6c9861  # yellow
regular4=b5955e  # blue
regular5=c9a554  # magenta
regular6=d7c483  # cyan
regular7=b5955e  # white
bright0=75644f   # bright black
bright1=cc967b   # bright red
bright2=97976d   # bright green
bright3=6c9861   # bright yellow
bright4=b5955e   # bright blue
bright5=c9a554   # bright magenta
bright6=d7c483   # bright cyan
bright7=b5955e   # bright white
