# -*- conf -*-
# Terminal Basic

[main]
initial-color-theme=light

[colors-light]
cursor=000000 7f7f7f
background=ffffff
foreground=000000
selection-foreground=000000
selection-background=a4c9ff
regular0=000000  # black
regular1=990000  # red
regular2=00a600  # green
regular3=999900  # yellow
regular4=0000b2  # blue
regular5=b200b2  # magenta
regular6=00a6b2  # cyan
regular7=bfbfbf  # white
bright0=666666   # bright black
bright1=e50000   # bright red
bright2=00d900   # bright green
bright3=bfbf00   # bright yellow
bright4=0000ff   # bright blue
bright5=e500e5   # bright magenta
bright6=00d8d8   # bright cyan
bright7=e5e5e5   # bright white
