# -*- conf -*-
# TokyoNight Moon

[colors-dark]
cursor=222436 c8d3f5
background=222436
foreground=c8d3f5
selection-foreground=c8d3f5
selection-background=2d3f76
regular0=1b1d2b  # black
regular1=ff757f  # red
regular2=c3e88d  # green
regular3=ffc777  # yellow
regular4=82aaff  # blue
regular5=c099ff  # magenta
regular6=86e1fc  # cyan
regular7=828bb8  # white
bright0=444a73   # bright black
bright1=ff757f   # bright red
bright2=c3e88d   # bright green
bright3=ffc777   # bright yellow
bright4=82aaff   # bright blue
bright5=c099ff   # bright magenta
bright6=86e1fc   # bright cyan
bright7=c8d3f5   # bright white
