# -*- conf -*-
# Tomorrow Night Eighties

[colors-dark]
cursor=2d2d2d cccccc
background=2d2d2d
foreground=cccccc
selection-foreground=cccccc
selection-background=515151
regular0=000000  # black
regular1=f2777a  # red
regular2=99cc99  # green
regular3=ffcc66  # yellow
regular4=6699cc  # blue
regular5=cc99cc  # magenta
regular6=66cccc  # cyan
regular7=ffffff  # white
bright0=595959   # bright black
bright1=f2777a   # bright red
bright2=99cc99   # bright green
bright3=ffcc66   # bright yellow
bright4=6699cc   # bright blue
bright5=cc99cc   # bright magenta
bright6=66cccc   # bright cyan
bright7=ffffff   # bright white
