# -*- conf -*-
# Ubuntu

[colors-dark]
cursor=ffffff bbbbbb
background=300a24
foreground=eeeeec
selection-foreground=000000
selection-background=b5d5ff
regular0=2e3436  # black
regular1=cc0000  # red
regular2=4e9a06  # green
regular3=c4a000  # yellow
regular4=3465a4  # blue
regular5=75507b  # magenta
regular6=06989a  # cyan
regular7=d3d7cf  # white
bright0=555753   # bright black
bright1=ef2929   # bright red
bright2=8ae234   # bright green
bright3=fce94f   # bright yellow
bright4=729fcf   # bright blue
bright5=ad7fa8   # bright magenta
bright6=34e2e2   # bright cyan
bright7=eeeeec   # bright white
