# -*- conf -*-
# Whimsy

[colors-dark]
cursor=535178 b3b0d6
background=29283b
foreground=b3b0d6
selection-foreground=ffffff
selection-background=3d3c58
regular0=535178  # black
regular1=ef6487  # red
regular2=5eca89  # green
regular3=fdd877  # yellow
regular4=65aef7  # blue
regular5=aa7ff0  # magenta
regular6=43c1be  # cyan
regular7=ffffff  # white
bright0=535178   # bright black
bright1=ef6487   # bright red
bright2=5eca89   # bright green
bright3=fdd877   # bright yellow
bright4=65aef7   # bright blue
bright5=aa7ff0   # bright magenta
bright6=43c1be   # bright cyan
bright7=ffffff   # bright white
