# -*- conf -*-
# Wilmersdorf

[colors-dark]
cursor=1f2024 7ebebd
background=282b33
foreground=c6c6c6
selection-foreground=c6c6c6
selection-background=1f2024
regular0=34373e  # black
regular1=e06383  # red
regular2=7ebebd  # green
regular3=cccccc  # yellow
regular4=a6c1e0  # blue
regular5=e1c1ee  # magenta
regular6=5b94ab  # cyan
regular7=ababab  # white
bright0=50545d   # bright black
bright1=fa7193   # bright red
bright2=8fd7d6   # bright green
bright3=d1dfff   # bright yellow
bright4=b2cff0   # bright blue
bright5=efccfd   # bright magenta
bright6=69abc5   # bright cyan
bright7=d3d3d3   # bright white
