# -*- conf -*-
# Wryan

[colors-dark]
cursor=000000 9e9ecb
background=101010
foreground=999993
selection-foreground=ffffff
selection-background=4d4d4d
regular0=333333  # black
regular1=8c4665  # red
regular2=287373  # green
regular3=7c7c99  # yellow
regular4=395573  # blue
regular5=5e468c  # magenta
regular6=31658c  # cyan
regular7=899ca1  # white
bright0=3d3d3d   # bright black
bright1=bf4d80   # bright red
bright2=53a6a6   # bright green
bright3=9e9ecb   # bright yellow
bright4=477ab3   # bright blue
bright5=7e62b3   # bright magenta
bright6=6096bf   # bright cyan
bright7=c0c0c0   # bright white
