# -*- conf -*-
# Zenbones Dark

[colors-dark]
cursor=1c1917 c4cacf
background=1c1917
foreground=b4bdc3
selection-foreground=b4bdc3
selection-background=3d4042
regular0=1c1917  # black
regular1=de6e7c  # red
regular2=819b69  # green
regular3=b77e64  # yellow
regular4=6099c0  # blue
regular5=b279a7  # magenta
regular6=66a5ad  # cyan
regular7=b4bdc3  # white
bright0=4d4540   # bright black
bright1=e8838f   # bright red
bright2=8bae68   # bright green
bright3=d68c67   # bright yellow
bright4=61abda   # bright blue
bright5=cf86c1   # bright magenta
bright6=65b8c1   # bright cyan
bright7=888f94   # bright white
